/**
	* \file VecWznmVCall.cpp
	* vector VecWznmVCall (implementation)
	* \copyright (C) 2016-2020 MPSI Technologies GmbH
	* \author Alexander Wirthmueller (auto-generation)
	* \date created: 28 Nov 2020
  */
// IP header --- ABOVE

#include "VecWznmVCall.h"

using namespace std;
using namespace Sbecore;
using namespace Xmlio;

/******************************************************************************
 namespace VecWznmVCall
 ******************************************************************************/

uint VecWznmVCall::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "callwznmapp.vereq") return CALLWZNMAPP_VEREQ;
	if (s == "callwznmappmod") return CALLWZNMAPPMOD;
	if (s == "callwznmappmod.vereq") return CALLWZNMAPPMOD_VEREQ;
	if (s == "callwznmappupd.refeq") return CALLWZNMAPPUPD_REFEQ;
	if (s == "callwznmbitjmod.blkaitmeq") return CALLWZNMBITJMOD_BLKAITMEQ;
	if (s == "callwznmblk.reteq") return CALLWZNMBLK_RETEQ;
	if (s == "callwznmblk.reueq") return CALLWZNMBLK_REUEQ;
	if (s == "callwznmblk.vereq") return CALLWZNMBLK_VEREQ;
	if (s == "callwznmblkaitmmod.blkeq") return CALLWZNMBLKAITMMOD_BLKEQ;
	if (s == "callwznmblkaitmmod.clueq") return CALLWZNMBLKAITMMOD_CLUEQ;
	if (s == "callwznmblkmod") return CALLWZNMBLKMOD;
	if (s == "callwznmblkmod.retreueq") return CALLWZNMBLKMOD_RETREUEQ;
	if (s == "callwznmblkmod.vereq") return CALLWZNMBLKMOD_VEREQ;
	if (s == "callwznmblkupd.refeq") return CALLWZNMBLKUPD_REFEQ;
	if (s == "callwznmboolvalpreset") return CALLWZNMBOOLVALPRESET;
	if (s == "callwznmcal.reteq") return CALLWZNMCAL_RETEQ;
	if (s == "callwznmcal.reueq") return CALLWZNMCAL_REUEQ;
	if (s == "callwznmcal.typeq") return CALLWZNMCAL_TYPEQ;
	if (s == "callwznmcal.vereq") return CALLWZNMCAL_VEREQ;
	if (s == "callwznmcalmod") return CALLWZNMCALMOD;
	if (s == "callwznmcalmod.retreueq") return CALLWZNMCALMOD_RETREUEQ;
	if (s == "callwznmcalmod.vereq") return CALLWZNMCALMOD_VEREQ;
	if (s == "callwznmcalrstbmod.caleq") return CALLWZNMCALRSTBMOD_CALEQ;
	if (s == "callwznmcalrstbmod.stbeq") return CALLWZNMCALRSTBMOD_STBEQ;
	if (s == "callwznmcalupd.refeq") return CALLWZNMCALUPD_REFEQ;
	if (s == "callwznmcar.jobeq") return CALLWZNMCAR_JOBEQ;
	if (s == "callwznmcar.mdleq") return CALLWZNMCAR_MDLEQ;
	if (s == "callwznmcar.reteq") return CALLWZNMCAR_RETEQ;
	if (s == "callwznmcar.reueq") return CALLWZNMCAR_REUEQ;
	if (s == "callwznmcarjtitmod.careq") return CALLWZNMCARJTITMOD_CAREQ;
	if (s == "callwznmcarmod") return CALLWZNMCARMOD;
	if (s == "callwznmcarmod.mdleq") return CALLWZNMCARMOD_MDLEQ;
	if (s == "callwznmcarmod.retreueq") return CALLWZNMCARMOD_RETREUEQ;
	if (s == "callwznmcarupd.refeq") return CALLWZNMCARUPD_REFEQ;
	if (s == "callwznmchk.caleq") return CALLWZNMCHK_CALEQ;
	if (s == "callwznmchk.tcoeq") return CALLWZNMCHK_TCOEQ;
	if (s == "callwznmchkmod") return CALLWZNMCHKMOD;
	if (s == "callwznmchkmod.tbleq") return CALLWZNMCHKMOD_TBLEQ;
	if (s == "callwznmchkupd.refeq") return CALLWZNMCHKUPD_REFEQ;
	if (s == "callwznmclaimchg") return CALLWZNMCLAIMCHG;
	if (s == "callwznmcmp.insbs") return CALLWZNMCMP_INSBS;
	if (s == "callwznmcmp.typeq") return CALLWZNMCMP_TYPEQ;
	if (s == "callwznmcmp.vereq") return CALLWZNMCMP_VEREQ;
	if (s == "callwznmcmpmod") return CALLWZNMCMPMOD;
	if (s == "callwznmcmpmod.vereq") return CALLWZNMCMPMOD_VEREQ;
	if (s == "callwznmcmprlibmod.cmpeq") return CALLWZNMCMPRLIBMOD_CMPEQ;
	if (s == "callwznmcmprlibmod.libeq") return CALLWZNMCMPRLIBMOD_LIBEQ;
	if (s == "callwznmcmpropkmod.cmpeq") return CALLWZNMCMPROPKMOD_CMPEQ;
	if (s == "callwznmcmpropkmod.opkeq") return CALLWZNMCMPROPKMOD_OPKEQ;
	if (s == "callwznmcmpupd.refeq") return CALLWZNMCMPUPD_REFEQ;
	if (s == "callwznmcon.clueq") return CALLWZNMCON_CLUEQ;
	if (s == "callwznmcon.fedeq") return CALLWZNMCON_FEDEQ;
	if (s == "callwznmcon.hkteq") return CALLWZNMCON_HKTEQ;
	if (s == "callwznmcon.hkueq") return CALLWZNMCON_HKUEQ;
	if (s == "callwznmcon.insbs") return CALLWZNMCON_INSBS;
	if (s == "callwznmcon.reteq") return CALLWZNMCON_RETEQ;
	if (s == "callwznmcon.reueq") return CALLWZNMCON_REUEQ;
	if (s == "callwznmcon.shseq") return CALLWZNMCON_SHSEQ;
	if (s == "callwznmcon.stseq") return CALLWZNMCON_STSEQ;
	if (s == "callwznmcon.supeq") return CALLWZNMCON_SUPEQ;
	if (s == "callwznmcon.typeq") return CALLWZNMCON_TYPEQ;
	if (s == "callwznmconaparmod.coneq") return CALLWZNMCONAPARMOD_CONEQ;
	if (s == "callwznmconaparmod.loceq") return CALLWZNMCONAPARMOD_LOCEQ;
	if (s == "callwznmconjmod.coneq") return CALLWZNMCONJMOD_CONEQ;
	if (s == "callwznmconjtitmod.coneq") return CALLWZNMCONJTITMOD_CONEQ;
	if (s == "callwznmconmod") return CALLWZNMCONMOD;
	if (s == "callwznmconmod.clueq") return CALLWZNMCONMOD_CLUEQ;
	if (s == "callwznmconmod.hkthkueq") return CALLWZNMCONMOD_HKTHKUEQ;
	if (s == "callwznmconmod.retreueq") return CALLWZNMCONMOD_RETREUEQ;
	if (s == "callwznmconmod.supeq") return CALLWZNMCONMOD_SUPEQ;
	if (s == "callwznmconupd.refeq") return CALLWZNMCONUPD_REFEQ;
	if (s == "callwznmcpb.insbs") return CALLWZNMCPB_INSBS;
	if (s == "callwznmcpb.tpleq") return CALLWZNMCPB_TPLEQ;
	if (s == "callwznmcpb.vereq") return CALLWZNMCPB_VEREQ;
	if (s == "callwznmcpbaparmod.cpbeq") return CALLWZNMCPBAPARMOD_CPBEQ;
	if (s == "callwznmcpbmod") return CALLWZNMCPBMOD;
	if (s == "callwznmcpbmod.tpleq") return CALLWZNMCPBMOD_TPLEQ;
	if (s == "callwznmcpbmod.vereq") return CALLWZNMCPBMOD_VEREQ;
	if (s == "callwznmcpbupd.refeq") return CALLWZNMCPBUPD_REFEQ;
	if (s == "callwznmcrdactive") return CALLWZNMCRDACTIVE;
	if (s == "callwznmcrdclose") return CALLWZNMCRDCLOSE;
	if (s == "callwznmcrdopen") return CALLWZNMCRDOPEN;
	if (s == "callwznmctlaparmod.usreq") return CALLWZNMCTLAPARMOD_USREQ;
	if (s == "callwznmdatchg") return CALLWZNMDATCHG;
	if (s == "callwznmdblvalpreset") return CALLWZNMDBLVALPRESET;
	if (s == "callwznmdlg.careq") return CALLWZNMDLG_CAREQ;
	if (s == "callwznmdlg.jobeq") return CALLWZNMDLG_JOBEQ;
	if (s == "callwznmdlg.reteq") return CALLWZNMDLG_RETEQ;
	if (s == "callwznmdlg.reueq") return CALLWZNMDLG_REUEQ;
	if (s == "callwznmdlgclose") return CALLWZNMDLGCLOSE;
	if (s == "callwznmdlgmod") return CALLWZNMDLGMOD;
	if (s == "callwznmdlgmod.careq") return CALLWZNMDLGMOD_CAREQ;
	if (s == "callwznmdlgmod.retreueq") return CALLWZNMDLGMOD_RETREUEQ;
	if (s == "callwznmdlgrqrymod.dlgeq") return CALLWZNMDLGRQRYMOD_DLGEQ;
	if (s == "callwznmdlgrqrymod.qryeq") return CALLWZNMDLGRQRYMOD_QRYEQ;
	if (s == "callwznmdlgupd.refeq") return CALLWZNMDLGUPD_REFEQ;
	if (s == "callwznmerr.vereq") return CALLWZNMERR_VEREQ;
	if (s == "callwznmerrjtitmod.erreq") return CALLWZNMERRJTITMOD_ERREQ;
	if (s == "callwznmerrmod") return CALLWZNMERRMOD;
	if (s == "callwznmerrmod.vereq") return CALLWZNMERRMOD_VEREQ;
	if (s == "callwznmerrupd.refeq") return CALLWZNMERRUPD_REFEQ;
	if (s == "callwznmevt.appeq") return CALLWZNMEVT_APPEQ;
	if (s == "callwznmevtmod") return CALLWZNMEVTMOD;
	if (s == "callwznmevtmod.appeq") return CALLWZNMEVTMOD_APPEQ;
	if (s == "callwznmevtupd.refeq") return CALLWZNMEVTUPD_REFEQ;
	if (s == "callwznmfed.srteq") return CALLWZNMFED_SRTEQ;
	if (s == "callwznmfed.srueq") return CALLWZNMFED_SRUEQ;
	if (s == "callwznmfedmod") return CALLWZNMFEDMOD;
	if (s == "callwznmfedmod.srtsrueq") return CALLWZNMFEDMOD_SRTSRUEQ;
	if (s == "callwznmfedupd.refeq") return CALLWZNMFEDUPD_REFEQ;
	if (s == "callwznmfil.clueq") return CALLWZNMFIL_CLUEQ;
	if (s == "callwznmfil.reteq") return CALLWZNMFIL_RETEQ;
	if (s == "callwznmfil.reueq") return CALLWZNMFIL_REUEQ;
	if (s == "callwznmfilmod") return CALLWZNMFILMOD;
	if (s == "callwznmfilmod.clueq") return CALLWZNMFILMOD_CLUEQ;
	if (s == "callwznmfilmod.retreueq") return CALLWZNMFILMOD_RETREUEQ;
	if (s == "callwznmfilupd.refeq") return CALLWZNMFILUPD_REFEQ;
	if (s == "callwznmhusrrunvmod.crdusreq") return CALLWZNMHUSRRUNVMOD_CRDUSREQ;
	if (s == "callwznmiel.im2eq") return CALLWZNMIEL_IM2EQ;
	if (s == "callwznmiel.imeeq") return CALLWZNMIEL_IMEEQ;
	if (s == "callwznmiel.psteq") return CALLWZNMIEL_PSTEQ;
	if (s == "callwznmiel.stbeq") return CALLWZNMIEL_STBEQ;
	if (s == "callwznmiel.viteq") return CALLWZNMIEL_VITEQ;
	if (s == "callwznmieljstbmod.ieleq") return CALLWZNMIELJSTBMOD_IELEQ;
	if (s == "callwznmielmod") return CALLWZNMIELMOD;
	if (s == "callwznmielmod.imeeq") return CALLWZNMIELMOD_IMEEQ;
	if (s == "callwznmielmod.tcoeq") return CALLWZNMIELMOD_TCOEQ;
	if (s == "callwznmielupd.refeq") return CALLWZNMIELUPD_REFEQ;
	if (s == "callwznmiex.jobeq") return CALLWZNMIEX_JOBEQ;
	if (s == "callwznmiex.vereq") return CALLWZNMIEX_VEREQ;
	if (s == "callwznmiexjtitmod.iexeq") return CALLWZNMIEXJTITMOD_IEXEQ;
	if (s == "callwznmiexmod") return CALLWZNMIEXMOD;
	if (s == "callwznmiexmod.vereq") return CALLWZNMIEXMOD_VEREQ;
	if (s == "callwznmiexupd.refeq") return CALLWZNMIEXUPD_REFEQ;
	if (s == "callwznmime.iexeq") return CALLWZNMIME_IEXEQ;
	if (s == "callwznmime.supeq") return CALLWZNMIME_SUPEQ;
	if (s == "callwznmimemod") return CALLWZNMIMEMOD;
	if (s == "callwznmimemod.iexeq") return CALLWZNMIMEMOD_IEXEQ;
	if (s == "callwznmimemod.supeq") return CALLWZNMIMEMOD_SUPEQ;
	if (s == "callwznmimemod.tbleq") return CALLWZNMIMEMOD_TBLEQ;
	if (s == "callwznmimeupd.refeq") return CALLWZNMIMEUPD_REFEQ;
	if (s == "callwznmintvalpreset") return CALLWZNMINTVALPRESET;
	if (s == "callwznmixpreset") return CALLWZNMIXPRESET;
	if (s == "callwznmjob.reteq") return CALLWZNMJOB_RETEQ;
	if (s == "callwznmjob.reueq") return CALLWZNMJOB_REUEQ;
	if (s == "callwznmjob.typeq") return CALLWZNMJOB_TYPEQ;
	if (s == "callwznmjob.vereq") return CALLWZNMJOB_VEREQ;
	if (s == "callwznmjobacmdmod.jobeq") return CALLWZNMJOBACMDMOD_JOBEQ;
	if (s == "callwznmjobavarmod.clueq") return CALLWZNMJOBAVARMOD_CLUEQ;
	if (s == "callwznmjobavarmod.jobeq") return CALLWZNMJOBAVARMOD_JOBEQ;
	if (s == "callwznmjobmod") return CALLWZNMJOBMOD;
	if (s == "callwznmjobmod.retreueq") return CALLWZNMJOBMOD_RETREUEQ;
	if (s == "callwznmjobmod.vereq") return CALLWZNMJOBMOD_VEREQ;
	if (s == "callwznmjobrjobmod.subeq") return CALLWZNMJOBRJOBMOD_SUBEQ;
	if (s == "callwznmjobrjobmod.supeq") return CALLWZNMJOBRJOBMOD_SUPEQ;
	if (s == "callwznmjobropkmod.jobeq") return CALLWZNMJOBROPKMOD_JOBEQ;
	if (s == "callwznmjobropkmod.opkeq") return CALLWZNMJOBROPKMOD_OPKEQ;
	if (s == "callwznmjobropxmod.jobeq") return CALLWZNMJOBROPXMOD_JOBEQ;
	if (s == "callwznmjobropxmod.opxeq") return CALLWZNMJOBROPXMOD_OPXEQ;
	if (s == "callwznmjobupd.refeq") return CALLWZNMJOBUPD_REFEQ;
	if (s == "callwznmklkjkeymod.klsakeyeq") return CALLWZNMKLKJKEYMOD_KLSAKEYEQ;
	if (s == "callwznmklsakeymod.klseq") return CALLWZNMKLSAKEYMOD_KLSEQ;
	if (s == "callwznmklsakeymod.klsmtburfeq") return CALLWZNMKLSAKEYMOD_KLSMTBURFEQ;
	if (s == "callwznmlibamkfmod.libeq") return CALLWZNMLIBAMKFMOD_LIBEQ;
	if (s == "callwznmlibamkfmod.mcheq") return CALLWZNMLIBAMKFMOD_MCHEQ;
	if (s == "callwznmlibapklmod.libeq") return CALLWZNMLIBAPKLMOD_LIBEQ;
	if (s == "callwznmlibapklmod.mcheq") return CALLWZNMLIBAPKLMOD_MCHEQ;
	if (s == "callwznmlibmod") return CALLWZNMLIBMOD;
	if (s == "callwznmlibropkmod.libeq") return CALLWZNMLIBROPKMOD_LIBEQ;
	if (s == "callwznmlibropkmod.opkeq") return CALLWZNMLIBROPKMOD_OPKEQ;
	if (s == "callwznmlibupd.refeq") return CALLWZNMLIBUPD_REFEQ;
	if (s == "callwznmlocjtitmod.loceq") return CALLWZNMLOCJTITMOD_LOCEQ;
	if (s == "callwznmlocmod") return CALLWZNMLOCMOD;
	if (s == "callwznmlocrvermod.loceq") return CALLWZNMLOCRVERMOD_LOCEQ;
	if (s == "callwznmlocrvermod.vereq") return CALLWZNMLOCRVERMOD_VEREQ;
	if (s == "callwznmlocupd.refeq") return CALLWZNMLOCUPD_REFEQ;
	if (s == "callwznmlog") return CALLWZNMLOG;
	if (s == "callwznmlogout") return CALLWZNMLOGOUT;
	if (s == "callwznmmch.ccheq") return CALLWZNMMCH_CCHEQ;
	if (s == "callwznmmch.supeq") return CALLWZNMMCH_SUPEQ;
	if (s == "callwznmmchamkfmod.mcheq") return CALLWZNMMCHAMKFMOD_MCHEQ;
	if (s == "callwznmmchaparmod.mcheq") return CALLWZNMMCHAPARMOD_MCHEQ;
	if (s == "callwznmmchmod") return CALLWZNMMCHMOD;
	if (s == "callwznmmchmod.supeq") return CALLWZNMMCHMOD_SUPEQ;
	if (s == "callwznmmchupd.refeq") return CALLWZNMMCHUPD_REFEQ;
	if (s == "callwznmmdl.vereq") return CALLWZNMMDL_VEREQ;
	if (s == "callwznmmdljmod.mdleq") return CALLWZNMMDLJMOD_MDLEQ;
	if (s == "callwznmmdlmod") return CALLWZNMMDLMOD;
	if (s == "callwznmmdlmod.vereq") return CALLWZNMMDLMOD_VEREQ;
	if (s == "callwznmmdlupd.refeq") return CALLWZNMMDLUPD_REFEQ;
	if (s == "callwznmmonstatchg") return CALLWZNMMONSTATCHG;
	if (s == "callwznmmtd.jobeq") return CALLWZNMMTD_JOBEQ;
	if (s == "callwznmmtdaipamod.mtdeq") return CALLWZNMMTDAIPAMOD_MTDEQ;
	if (s == "callwznmmtdarpamod.mtdeq") return CALLWZNMMTDARPAMOD_MTDEQ;
	if (s == "callwznmmtdmod") return CALLWZNMMTDMOD;
	if (s == "callwznmmtdmod.jobeq") return CALLWZNMMTDMOD_JOBEQ;
	if (s == "callwznmmtdupd.refeq") return CALLWZNMMTDUPD_REFEQ;
	if (s == "callwznmnodechg") return CALLWZNMNODECHG;
	if (s == "callwznmopk.sqkeq") return CALLWZNMOPK_SQKEQ;
	if (s == "callwznmopk.vereq") return CALLWZNMOPK_VEREQ;
	if (s == "callwznmopkainvmod.clueq") return CALLWZNMOPKAINVMOD_CLUEQ;
	if (s == "callwznmopkainvmod.opkeq") return CALLWZNMOPKAINVMOD_OPKEQ;
	if (s == "callwznmopkaretmod.clueq") return CALLWZNMOPKARETMOD_CLUEQ;
	if (s == "callwznmopkaretmod.opkeq") return CALLWZNMOPKARETMOD_OPKEQ;
	if (s == "callwznmopkmod") return CALLWZNMOPKMOD;
	if (s == "callwznmopkmod.vereq") return CALLWZNMOPKMOD_VEREQ;
	if (s == "callwznmopkupd.refeq") return CALLWZNMOPKUPD_REFEQ;
	if (s == "callwznmopx.opkeq") return CALLWZNMOPX_OPKEQ;
	if (s == "callwznmopx.sqkeq") return CALLWZNMOPX_SQKEQ;
	if (s == "callwznmopxainvmod.clueq") return CALLWZNMOPXAINVMOD_CLUEQ;
	if (s == "callwznmopxainvmod.opxeq") return CALLWZNMOPXAINVMOD_OPXEQ;
	if (s == "callwznmopxaretmod.clueq") return CALLWZNMOPXARETMOD_CLUEQ;
	if (s == "callwznmopxaretmod.opxeq") return CALLWZNMOPXARETMOD_OPXEQ;
	if (s == "callwznmopxmod") return CALLWZNMOPXMOD;
	if (s == "callwznmopxmod.opkeq") return CALLWZNMOPXMOD_OPKEQ;
	if (s == "callwznmopxupd.refeq") return CALLWZNMOPXUPD_REFEQ;
	if (s == "callwznmpnl.careq") return CALLWZNMPNL_CAREQ;
	if (s == "callwznmpnl.jobeq") return CALLWZNMPNL_JOBEQ;
	if (s == "callwznmpnl.reteq") return CALLWZNMPNL_RETEQ;
	if (s == "callwznmpnl.reueq") return CALLWZNMPNL_REUEQ;
	if (s == "callwznmpnlmod") return CALLWZNMPNLMOD;
	if (s == "callwznmpnlmod.careq") return CALLWZNMPNLMOD_CAREQ;
	if (s == "callwznmpnlmod.retreueq") return CALLWZNMPNLMOD_RETREUEQ;
	if (s == "callwznmpnlrqrymod.pnleq") return CALLWZNMPNLRQRYMOD_PNLEQ;
	if (s == "callwznmpnlrqrymod.qryeq") return CALLWZNMPNLRQRYMOD_QRYEQ;
	if (s == "callwznmpnlupd.refeq") return CALLWZNMPNLUPD_REFEQ;
	if (s == "callwznmprj.vereq") return CALLWZNMPRJ_VEREQ;
	if (s == "callwznmprjmod") return CALLWZNMPRJMOD;
	if (s == "callwznmprjupd.refeq") return CALLWZNMPRJUPD_REFEQ;
	if (s == "callwznmprsadetmod.prseq") return CALLWZNMPRSADETMOD_PRSEQ;
	if (s == "callwznmprsjlnmmod.prseq") return CALLWZNMPRSJLNMMOD_PRSEQ;
	if (s == "callwznmprsmod") return CALLWZNMPRSMOD;
	if (s == "callwznmprsrprjmod.prjeq") return CALLWZNMPRSRPRJMOD_PRJEQ;
	if (s == "callwznmprsrprjmod.prseq") return CALLWZNMPRSRPRJMOD_PRSEQ;
	if (s == "callwznmprsupd.refeq") return CALLWZNMPRSUPD_REFEQ;
	if (s == "callwznmpst.reteq") return CALLWZNMPST_RETEQ;
	if (s == "callwznmpst.reueq") return CALLWZNMPST_REUEQ;
	if (s == "callwznmpst.vereq") return CALLWZNMPST_VEREQ;
	if (s == "callwznmpstjtitmod.psteq") return CALLWZNMPSTJTITMOD_PSTEQ;
	if (s == "callwznmpstmod") return CALLWZNMPSTMOD;
	if (s == "callwznmpstmod.retreueq") return CALLWZNMPSTMOD_RETREUEQ;
	if (s == "callwznmpstmod.vereq") return CALLWZNMPSTMOD_VEREQ;
	if (s == "callwznmpstupd.refeq") return CALLWZNMPSTUPD_REFEQ;
	if (s == "callwznmqco.qryeq") return CALLWZNMQCO_QRYEQ;
	if (s == "callwznmqco.stbeq") return CALLWZNMQCO_STBEQ;
	if (s == "callwznmqcojstbmod.qcoeq") return CALLWZNMQCOJSTBMOD_QCOEQ;
	if (s == "callwznmqcomod") return CALLWZNMQCOMOD;
	if (s == "callwznmqcomod.qryeq") return CALLWZNMQCOMOD_QRYEQ;
	if (s == "callwznmqcomod.tcoeq") return CALLWZNMQCOMOD_TCOEQ;
	if (s == "callwznmqcoupd.refeq") return CALLWZNMQCOUPD_REFEQ;
	if (s == "callwznmqmd.psteq") return CALLWZNMQMD_PSTEQ;
	if (s == "callwznmqmd.qryeq") return CALLWZNMQMD_QRYEQ;
	if (s == "callwznmqmd.reteq") return CALLWZNMQMD_RETEQ;
	if (s == "callwznmqmd.reueq") return CALLWZNMQMD_REUEQ;
	if (s == "callwznmqmdmod") return CALLWZNMQMDMOD;
	if (s == "callwznmqmdmod.psteq") return CALLWZNMQMDMOD_PSTEQ;
	if (s == "callwznmqmdmod.qryeq") return CALLWZNMQMDMOD_QRYEQ;
	if (s == "callwznmqmdmod.retreueq") return CALLWZNMQMDMOD_RETREUEQ;
	if (s == "callwznmqmdupd.refeq") return CALLWZNMQMDUPD_REFEQ;
	if (s == "callwznmqry.jobeq") return CALLWZNMQRY_JOBEQ;
	if (s == "callwznmqry.supeq") return CALLWZNMQRY_SUPEQ;
	if (s == "callwznmqry.vereq") return CALLWZNMQRY_VEREQ;
	if (s == "callwznmqryacsemod.qmdeq") return CALLWZNMQRYACSEMOD_QMDEQ;
	if (s == "callwznmqryacsemod.qryeq") return CALLWZNMQRYACSEMOD_QRYEQ;
	if (s == "callwznmqryaordmod.qryeq") return CALLWZNMQRYAORDMOD_QRYEQ;
	if (s == "callwznmqrymod") return CALLWZNMQRYMOD;
	if (s == "callwznmqrymod.supeq") return CALLWZNMQRYMOD_SUPEQ;
	if (s == "callwznmqrymod.vereq") return CALLWZNMQRYMOD_VEREQ;
	if (s == "callwznmqryrtblmod.qryeq") return CALLWZNMQRYRTBLMOD_QRYEQ;
	if (s == "callwznmqryrtblmod.tbleq") return CALLWZNMQRYRTBLMOD_TBLEQ;
	if (s == "callwznmqryupd.refeq") return CALLWZNMQRYUPD_REFEQ;
	if (s == "callwznmrecaccess") return CALLWZNMRECACCESS;
	if (s == "callwznmrefpreset") return CALLWZNMREFPRESET;
	if (s == "callwznmrefspreset") return CALLWZNMREFSPRESET;
	if (s == "callwznmrel.clueq") return CALLWZNMREL_CLUEQ;
	if (s == "callwznmrel.frseq") return CALLWZNMREL_FRSEQ;
	if (s == "callwznmrel.supeq") return CALLWZNMREL_SUPEQ;
	if (s == "callwznmrel.toseq") return CALLWZNMREL_TOSEQ;
	if (s == "callwznmrel.vereq") return CALLWZNMREL_VEREQ;
	if (s == "callwznmrelatitmod.loceq") return CALLWZNMRELATITMOD_LOCEQ;
	if (s == "callwznmrelatitmod.releq") return CALLWZNMRELATITMOD_RELEQ;
	if (s == "callwznmrelmod") return CALLWZNMRELMOD;
	if (s == "callwznmrelmod.clueq") return CALLWZNMRELMOD_CLUEQ;
	if (s == "callwznmrelmod.frteq") return CALLWZNMRELMOD_FRTEQ;
	if (s == "callwznmrelmod.supeq") return CALLWZNMRELMOD_SUPEQ;
	if (s == "callwznmrelmod.toteq") return CALLWZNMRELMOD_TOTEQ;
	if (s == "callwznmrelmod.vereq") return CALLWZNMRELMOD_VEREQ;
	if (s == "callwznmrelupd.refeq") return CALLWZNMRELUPD_REFEQ;
	if (s == "callwznmreptrstart") return CALLWZNMREPTRSTART;
	if (s == "callwznmreptrstop") return CALLWZNMREPTRSTOP;
	if (s == "callwznmrls.cmpeq") return CALLWZNMRLS_CMPEQ;
	if (s == "callwznmrls.mcheq") return CALLWZNMRLS_MCHEQ;
	if (s == "callwznmrlsmod") return CALLWZNMRLSMOD;
	if (s == "callwznmrlsmod.cmpeq") return CALLWZNMRLSMOD_CMPEQ;
	if (s == "callwznmrlsmod.mcheq") return CALLWZNMRLSMOD_MCHEQ;
	if (s == "callwznmrlsupd.refeq") return CALLWZNMRLSUPD_REFEQ;
	if (s == "callwznmrtbmod") return CALLWZNMRTBMOD;
	if (s == "callwznmrtbmod.retreueq") return CALLWZNMRTBMOD_RETREUEQ;
	if (s == "callwznmrtbmod.rtjeq") return CALLWZNMRTBMOD_RTJEQ;
	if (s == "callwznmrtbupd.refeq") return CALLWZNMRTBUPD_REFEQ;
	if (s == "callwznmrtdmod") return CALLWZNMRTDMOD;
	if (s == "callwznmrtdmod.blkeq") return CALLWZNMRTDMOD_BLKEQ;
	if (s == "callwznmrtdmod.rtjeq") return CALLWZNMRTDMOD_RTJEQ;
	if (s == "callwznmrtdupd.refeq") return CALLWZNMRTDUPD_REFEQ;
	if (s == "callwznmrtj.appeq") return CALLWZNMRTJ_APPEQ;
	if (s == "callwznmrtj.jobeq") return CALLWZNMRTJ_JOBEQ;
	if (s == "callwznmrtj.supeq") return CALLWZNMRTJ_SUPEQ;
	if (s == "callwznmrtjmod") return CALLWZNMRTJMOD;
	if (s == "callwznmrtjmod.appeq") return CALLWZNMRTJMOD_APPEQ;
	if (s == "callwznmrtjmod.jobeq") return CALLWZNMRTJMOD_JOBEQ;
	if (s == "callwznmrtjmod.supeq") return CALLWZNMRTJMOD_SUPEQ;
	if (s == "callwznmrtjupd.refeq") return CALLWZNMRTJUPD_REFEQ;
	if (s == "callwznmsbs.careq") return CALLWZNMSBS_CAREQ;
	if (s == "callwznmsbs.psteq") return CALLWZNMSBS_PSTEQ;
	if (s == "callwznmsbsatitmod.loceq") return CALLWZNMSBSATITMOD_LOCEQ;
	if (s == "callwznmsbsatitmod.sbseq") return CALLWZNMSBSATITMOD_SBSEQ;
	if (s == "callwznmsbsmod") return CALLWZNMSBSMOD;
	if (s == "callwznmsbsmod.tbleq") return CALLWZNMSBSMOD_TBLEQ;
	if (s == "callwznmsbsrsbsmod.asbeq") return CALLWZNMSBSRSBSMOD_ASBEQ;
	if (s == "callwznmsbsrsbsmod.bsbeq") return CALLWZNMSBSRSBSMOD_BSBEQ;
	if (s == "callwznmsbsupd.refeq") return CALLWZNMSBSUPD_REFEQ;
	if (s == "callwznmseq.appeq") return CALLWZNMSEQ_APPEQ;
	if (s == "callwznmseqmod") return CALLWZNMSEQMOD;
	if (s == "callwznmseqmod.appeq") return CALLWZNMSEQMOD_APPEQ;
	if (s == "callwznmsequpd.refeq") return CALLWZNMSEQUPD_REFEQ;
	if (s == "callwznmsesmod") return CALLWZNMSESMOD;
	if (s == "callwznmsesmod.usreq") return CALLWZNMSESMOD_USREQ;
	if (s == "callwznmsesupd.refeq") return CALLWZNMSESUPD_REFEQ;
	if (s == "callwznmsge.fnxeq") return CALLWZNMSGE_FNXEQ;
	if (s == "callwznmsge.jobeq") return CALLWZNMSGE_JOBEQ;
	if (s == "callwznmsge.snxeq") return CALLWZNMSGE_SNXEQ;
	if (s == "callwznmsge.sqkeq") return CALLWZNMSGE_SQKEQ;
	if (s == "callwznmsgechg") return CALLWZNMSGECHG;
	if (s == "callwznmsgemod") return CALLWZNMSGEMOD;
	if (s == "callwznmsgemod.jobeq") return CALLWZNMSGEMOD_JOBEQ;
	if (s == "callwznmsgeupd.refeq") return CALLWZNMSGEUPD_REFEQ;
	if (s == "callwznmshrdatchg") return CALLWZNMSHRDATCHG;
	if (s == "callwznmsnsmod") return CALLWZNMSNSMOD;
	if (s == "callwznmsnsmod.caleq") return CALLWZNMSNSMOD_CALEQ;
	if (s == "callwznmsnsmod.jobeq") return CALLWZNMSNSMOD_JOBEQ;
	if (s == "callwznmsnsupd.refeq") return CALLWZNMSNSUPD_REFEQ;
	if (s == "callwznmsqkjtitmod.sqkeq") return CALLWZNMSQKJTITMOD_SQKEQ;
	if (s == "callwznmsqkmod") return CALLWZNMSQKMOD;
	if (s == "callwznmsqkmod.retreueq") return CALLWZNMSQKMOD_RETREUEQ;
	if (s == "callwznmsqkrstbmod.sqkeq") return CALLWZNMSQKRSTBMOD_SQKEQ;
	if (s == "callwznmsqkrstbmod.stbeq") return CALLWZNMSQKRSTBMOD_STBEQ;
	if (s == "callwznmsqkupd.refeq") return CALLWZNMSQKUPD_REFEQ;
	if (s == "callwznmsrefpreset") return CALLWZNMSREFPRESET;
	if (s == "callwznmstatchg") return CALLWZNMSTATCHG;
	if (s == "callwznmstb.sbseq") return CALLWZNMSTB_SBSEQ;
	if (s == "callwznmstb.tcoeq") return CALLWZNMSTB_TCOEQ;
	if (s == "callwznmstbmod") return CALLWZNMSTBMOD;
	if (s == "callwznmstbmod.tbleq") return CALLWZNMSTBMOD_TBLEQ;
	if (s == "callwznmstbrstbmod.subeq") return CALLWZNMSTBRSTBMOD_SUBEQ;
	if (s == "callwznmstbrstbmod.supeq") return CALLWZNMSTBRSTBMOD_SUPEQ;
	if (s == "callwznmstbupd.refeq") return CALLWZNMSTBUPD_REFEQ;
	if (s == "callwznmste.seqeq") return CALLWZNMSTE_SEQEQ;
	if (s == "callwznmsteaactmod.steeq") return CALLWZNMSTEAACTMOD_STEEQ;
	if (s == "callwznmsteatrgmod.steeq") return CALLWZNMSTEATRGMOD_STEEQ;
	if (s == "callwznmstemod") return CALLWZNMSTEMOD;
	if (s == "callwznmstemod.seqeq") return CALLWZNMSTEMOD_SEQEQ;
	if (s == "callwznmsteupd.refeq") return CALLWZNMSTEUPD_REFEQ;
	if (s == "callwznmstgchg") return CALLWZNMSTGCHG;
	if (s == "callwznmstrjcndmod.steatrgeq") return CALLWZNMSTRJCNDMOD_STEATRGEQ;
	if (s == "callwznmstubchg") return CALLWZNMSTUBCHG;
	if (s == "callwznmsuspsess") return CALLWZNMSUSPSESS;
	if (s == "callwznmtag.cpbeq") return CALLWZNMTAG_CPBEQ;
	if (s == "callwznmtagjtitmod.tageq") return CALLWZNMTAGJTITMOD_TAGEQ;
	if (s == "callwznmtagmod") return CALLWZNMTAGMOD;
	if (s == "callwznmtagmod.cpbeq") return CALLWZNMTAGMOD_CPBEQ;
	if (s == "callwznmtagupd.refeq") return CALLWZNMTAGUPD_REFEQ;
	if (s == "callwznmtbl.careq") return CALLWZNMTBL_CAREQ;
	if (s == "callwznmtbl.insbs") return CALLWZNMTBL_INSBS;
	if (s == "callwznmtbl.psteq") return CALLWZNMTBL_PSTEQ;
	if (s == "callwznmtbl.reteq") return CALLWZNMTBL_RETEQ;
	if (s == "callwznmtbl.reueq") return CALLWZNMTBL_REUEQ;
	if (s == "callwznmtbl.typeq") return CALLWZNMTBL_TYPEQ;
	if (s == "callwznmtbl.vereq") return CALLWZNMTBL_VEREQ;
	if (s == "callwznmtblalfcmod.tbleq") return CALLWZNMTBLALFCMOD_TBLEQ;
	if (s == "callwznmtblatitmod.loceq") return CALLWZNMTBLATITMOD_LOCEQ;
	if (s == "callwznmtblatitmod.tbleq") return CALLWZNMTBLATITMOD_TBLEQ;
	if (s == "callwznmtblmod") return CALLWZNMTBLMOD;
	if (s == "callwznmtblmod.retreueq") return CALLWZNMTBLMOD_RETREUEQ;
	if (s == "callwznmtblmod.vereq") return CALLWZNMTBLMOD_VEREQ;
	if (s == "callwznmtblrvecmod.tbleq") return CALLWZNMTBLRVECMOD_TBLEQ;
	if (s == "callwznmtblrvecmod.veceq") return CALLWZNMTBLRVECMOD_VECEQ;
	if (s == "callwznmtblupd.refeq") return CALLWZNMTBLUPD_REFEQ;
	if (s == "callwznmtco.fcteq") return CALLWZNMTCO_FCTEQ;
	if (s == "callwznmtco.fcueq") return CALLWZNMTCO_FCUEQ;
	if (s == "callwznmtco.insbs") return CALLWZNMTCO_INSBS;
	if (s == "callwznmtco.releq") return CALLWZNMTCO_RELEQ;
	if (s == "callwznmtco.sbseq") return CALLWZNMTCO_SBSEQ;
	if (s == "callwznmtco.tbl.insbs") return CALLWZNMTCO_TBL_INSBS;
	if (s == "callwznmtco.tbleq") return CALLWZNMTCO_TBLEQ;
	if (s == "callwznmtcoatitmod.loceq") return CALLWZNMTCOATITMOD_LOCEQ;
	if (s == "callwznmtcoatitmod.tcoeq") return CALLWZNMTCOATITMOD_TCOEQ;
	if (s == "callwznmtcomod") return CALLWZNMTCOMOD;
	if (s == "callwznmtcomod.fctfcueq") return CALLWZNMTCOMOD_FCTFCUEQ;
	if (s == "callwznmtcomod.releq") return CALLWZNMTCOMOD_RELEQ;
	if (s == "callwznmtcomod.tbleq") return CALLWZNMTCOMOD_TBLEQ;
	if (s == "callwznmtcoupd.refeq") return CALLWZNMTCOUPD_REFEQ;
	if (s == "callwznmtxtvalpreset") return CALLWZNMTXTVALPRESET;
	if (s == "callwznmusgaaccmod.usgeq") return CALLWZNMUSGAACCMOD_USGEQ;
	if (s == "callwznmusgmod") return CALLWZNMUSGMOD;
	if (s == "callwznmusgupd.refeq") return CALLWZNMUSGUPD_REFEQ;
	if (s == "callwznmusr.prseq") return CALLWZNMUSR_PRSEQ;
	if (s == "callwznmusr.usgeq") return CALLWZNMUSR_USGEQ;
	if (s == "callwznmusraaccmod.usreq") return CALLWZNMUSRAACCMOD_USREQ;
	if (s == "callwznmusrjstemod.usreq") return CALLWZNMUSRJSTEMOD_USREQ;
	if (s == "callwznmusrmod") return CALLWZNMUSRMOD;
	if (s == "callwznmusrrusgmod.usgeq") return CALLWZNMUSRRUSGMOD_USGEQ;
	if (s == "callwznmusrrusgmod.usreq") return CALLWZNMUSRRUSGMOD_USREQ;
	if (s == "callwznmusrupd.refeq") return CALLWZNMUSRUPD_REFEQ;
	if (s == "callwznmvec.hkteq") return CALLWZNMVEC_HKTEQ;
	if (s == "callwznmvec.hkueq") return CALLWZNMVEC_HKUEQ;
	if (s == "callwznmvec.insbs") return CALLWZNMVEC_INSBS;
	if (s == "callwznmvec.psteq") return CALLWZNMVEC_PSTEQ;
	if (s == "callwznmvec.typeq") return CALLWZNMVEC_TYPEQ;
	if (s == "callwznmvec.vereq") return CALLWZNMVEC_VEREQ;
	if (s == "callwznmvecatitmod.loceq") return CALLWZNMVECATITMOD_LOCEQ;
	if (s == "callwznmvecatitmod.veceq") return CALLWZNMVECATITMOD_VECEQ;
	if (s == "callwznmvecmod") return CALLWZNMVECMOD;
	if (s == "callwznmvecmod.hkthkueq") return CALLWZNMVECMOD_HKTHKUEQ;
	if (s == "callwznmvecmod.vereq") return CALLWZNMVECMOD_VEREQ;
	if (s == "callwznmvecupd.refeq") return CALLWZNMVECUPD_REFEQ;
	if (s == "callwznmver.bvreq") return CALLWZNMVER_BVREQ;
	if (s == "callwznmver.loceq") return CALLWZNMVER_LOCEQ;
	if (s == "callwznmver.prjeq") return CALLWZNMVER_PRJEQ;
	if (s == "callwznmver.steeq") return CALLWZNMVER_STEEQ;
	if (s == "callwznmverjmod.vereq") return CALLWZNMVERJMOD_VEREQ;
	if (s == "callwznmverjstemod.vereq") return CALLWZNMVERJSTEMOD_VEREQ;
	if (s == "callwznmvermod") return CALLWZNMVERMOD;
	if (s == "callwznmvermod.bvreq") return CALLWZNMVERMOD_BVREQ;
	if (s == "callwznmvermod.prjeq") return CALLWZNMVERMOD_PRJEQ;
	if (s == "callwznmverupd.refeq") return CALLWZNMVERUPD_REFEQ;
	if (s == "callwznmvit.veceq") return CALLWZNMVIT_VECEQ;
	if (s == "callwznmvitjmod.viteq") return CALLWZNMVITJMOD_VITEQ;
	if (s == "callwznmvitmod") return CALLWZNMVITMOD;
	if (s == "callwznmvitmod.veceq") return CALLWZNMVITMOD_VECEQ;
	if (s == "callwznmvitupd.refeq") return CALLWZNMVITUPD_REFEQ;

	return(0);
};

string VecWznmVCall::getSref(
			const uint ix
		) {
	if (ix == CALLWZNMAPP_VEREQ) return("CallWznmApp.verEq");
	if (ix == CALLWZNMAPPMOD) return("CallWznmAppMod");
	if (ix == CALLWZNMAPPMOD_VEREQ) return("CallWznmAppMod.verEq");
	if (ix == CALLWZNMAPPUPD_REFEQ) return("CallWznmAppUpd.refEq");
	if (ix == CALLWZNMBITJMOD_BLKAITMEQ) return("CallWznmBitJMod.blkAitmEq");
	if (ix == CALLWZNMBLK_RETEQ) return("CallWznmBlk.retEq");
	if (ix == CALLWZNMBLK_REUEQ) return("CallWznmBlk.reuEq");
	if (ix == CALLWZNMBLK_VEREQ) return("CallWznmBlk.verEq");
	if (ix == CALLWZNMBLKAITMMOD_BLKEQ) return("CallWznmBlkAitmMod.blkEq");
	if (ix == CALLWZNMBLKAITMMOD_CLUEQ) return("CallWznmBlkAitmMod.cluEq");
	if (ix == CALLWZNMBLKMOD) return("CallWznmBlkMod");
	if (ix == CALLWZNMBLKMOD_RETREUEQ) return("CallWznmBlkMod.retReuEq");
	if (ix == CALLWZNMBLKMOD_VEREQ) return("CallWznmBlkMod.verEq");
	if (ix == CALLWZNMBLKUPD_REFEQ) return("CallWznmBlkUpd.refEq");
	if (ix == CALLWZNMBOOLVALPRESET) return("CallWznmBoolvalPreSet");
	if (ix == CALLWZNMCAL_RETEQ) return("CallWznmCal.retEq");
	if (ix == CALLWZNMCAL_REUEQ) return("CallWznmCal.reuEq");
	if (ix == CALLWZNMCAL_TYPEQ) return("CallWznmCal.typEq");
	if (ix == CALLWZNMCAL_VEREQ) return("CallWznmCal.verEq");
	if (ix == CALLWZNMCALMOD) return("CallWznmCalMod");
	if (ix == CALLWZNMCALMOD_RETREUEQ) return("CallWznmCalMod.retReuEq");
	if (ix == CALLWZNMCALMOD_VEREQ) return("CallWznmCalMod.verEq");
	if (ix == CALLWZNMCALRSTBMOD_CALEQ) return("CallWznmCalRstbMod.calEq");
	if (ix == CALLWZNMCALRSTBMOD_STBEQ) return("CallWznmCalRstbMod.stbEq");
	if (ix == CALLWZNMCALUPD_REFEQ) return("CallWznmCalUpd.refEq");
	if (ix == CALLWZNMCAR_JOBEQ) return("CallWznmCar.jobEq");
	if (ix == CALLWZNMCAR_MDLEQ) return("CallWznmCar.mdlEq");
	if (ix == CALLWZNMCAR_RETEQ) return("CallWznmCar.retEq");
	if (ix == CALLWZNMCAR_REUEQ) return("CallWznmCar.reuEq");
	if (ix == CALLWZNMCARJTITMOD_CAREQ) return("CallWznmCarJtitMod.carEq");
	if (ix == CALLWZNMCARMOD) return("CallWznmCarMod");
	if (ix == CALLWZNMCARMOD_MDLEQ) return("CallWznmCarMod.mdlEq");
	if (ix == CALLWZNMCARMOD_RETREUEQ) return("CallWznmCarMod.retReuEq");
	if (ix == CALLWZNMCARUPD_REFEQ) return("CallWznmCarUpd.refEq");
	if (ix == CALLWZNMCHK_CALEQ) return("CallWznmChk.calEq");
	if (ix == CALLWZNMCHK_TCOEQ) return("CallWznmChk.tcoEq");
	if (ix == CALLWZNMCHKMOD) return("CallWznmChkMod");
	if (ix == CALLWZNMCHKMOD_TBLEQ) return("CallWznmChkMod.tblEq");
	if (ix == CALLWZNMCHKUPD_REFEQ) return("CallWznmChkUpd.refEq");
	if (ix == CALLWZNMCLAIMCHG) return("CallWznmClaimChg");
	if (ix == CALLWZNMCMP_INSBS) return("CallWznmCmp.inSbs");
	if (ix == CALLWZNMCMP_TYPEQ) return("CallWznmCmp.typEq");
	if (ix == CALLWZNMCMP_VEREQ) return("CallWznmCmp.verEq");
	if (ix == CALLWZNMCMPMOD) return("CallWznmCmpMod");
	if (ix == CALLWZNMCMPMOD_VEREQ) return("CallWznmCmpMod.verEq");
	if (ix == CALLWZNMCMPRLIBMOD_CMPEQ) return("CallWznmCmpRlibMod.cmpEq");
	if (ix == CALLWZNMCMPRLIBMOD_LIBEQ) return("CallWznmCmpRlibMod.libEq");
	if (ix == CALLWZNMCMPROPKMOD_CMPEQ) return("CallWznmCmpRopkMod.cmpEq");
	if (ix == CALLWZNMCMPROPKMOD_OPKEQ) return("CallWznmCmpRopkMod.opkEq");
	if (ix == CALLWZNMCMPUPD_REFEQ) return("CallWznmCmpUpd.refEq");
	if (ix == CALLWZNMCON_CLUEQ) return("CallWznmCon.cluEq");
	if (ix == CALLWZNMCON_FEDEQ) return("CallWznmCon.fedEq");
	if (ix == CALLWZNMCON_HKTEQ) return("CallWznmCon.hktEq");
	if (ix == CALLWZNMCON_HKUEQ) return("CallWznmCon.hkuEq");
	if (ix == CALLWZNMCON_INSBS) return("CallWznmCon.inSbs");
	if (ix == CALLWZNMCON_RETEQ) return("CallWznmCon.retEq");
	if (ix == CALLWZNMCON_REUEQ) return("CallWznmCon.reuEq");
	if (ix == CALLWZNMCON_SHSEQ) return("CallWznmCon.shsEq");
	if (ix == CALLWZNMCON_STSEQ) return("CallWznmCon.stsEq");
	if (ix == CALLWZNMCON_SUPEQ) return("CallWznmCon.supEq");
	if (ix == CALLWZNMCON_TYPEQ) return("CallWznmCon.typEq");
	if (ix == CALLWZNMCONAPARMOD_CONEQ) return("CallWznmConAparMod.conEq");
	if (ix == CALLWZNMCONAPARMOD_LOCEQ) return("CallWznmConAparMod.locEq");
	if (ix == CALLWZNMCONJMOD_CONEQ) return("CallWznmConJMod.conEq");
	if (ix == CALLWZNMCONJTITMOD_CONEQ) return("CallWznmConJtitMod.conEq");
	if (ix == CALLWZNMCONMOD) return("CallWznmConMod");
	if (ix == CALLWZNMCONMOD_CLUEQ) return("CallWznmConMod.cluEq");
	if (ix == CALLWZNMCONMOD_HKTHKUEQ) return("CallWznmConMod.hktHkuEq");
	if (ix == CALLWZNMCONMOD_RETREUEQ) return("CallWznmConMod.retReuEq");
	if (ix == CALLWZNMCONMOD_SUPEQ) return("CallWznmConMod.supEq");
	if (ix == CALLWZNMCONUPD_REFEQ) return("CallWznmConUpd.refEq");
	if (ix == CALLWZNMCPB_INSBS) return("CallWznmCpb.inSbs");
	if (ix == CALLWZNMCPB_TPLEQ) return("CallWznmCpb.tplEq");
	if (ix == CALLWZNMCPB_VEREQ) return("CallWznmCpb.verEq");
	if (ix == CALLWZNMCPBAPARMOD_CPBEQ) return("CallWznmCpbAparMod.cpbEq");
	if (ix == CALLWZNMCPBMOD) return("CallWznmCpbMod");
	if (ix == CALLWZNMCPBMOD_TPLEQ) return("CallWznmCpbMod.tplEq");
	if (ix == CALLWZNMCPBMOD_VEREQ) return("CallWznmCpbMod.verEq");
	if (ix == CALLWZNMCPBUPD_REFEQ) return("CallWznmCpbUpd.refEq");
	if (ix == CALLWZNMCRDACTIVE) return("CallWznmCrdActive");
	if (ix == CALLWZNMCRDCLOSE) return("CallWznmCrdClose");
	if (ix == CALLWZNMCRDOPEN) return("CallWznmCrdOpen");
	if (ix == CALLWZNMCTLAPARMOD_USREQ) return("CallWznmCtlAparMod.usrEq");
	if (ix == CALLWZNMDATCHG) return("CallWznmDatChg");
	if (ix == CALLWZNMDBLVALPRESET) return("CallWznmDblvalPreSet");
	if (ix == CALLWZNMDLG_CAREQ) return("CallWznmDlg.carEq");
	if (ix == CALLWZNMDLG_JOBEQ) return("CallWznmDlg.jobEq");
	if (ix == CALLWZNMDLG_RETEQ) return("CallWznmDlg.retEq");
	if (ix == CALLWZNMDLG_REUEQ) return("CallWznmDlg.reuEq");
	if (ix == CALLWZNMDLGCLOSE) return("CallWznmDlgClose");
	if (ix == CALLWZNMDLGMOD) return("CallWznmDlgMod");
	if (ix == CALLWZNMDLGMOD_CAREQ) return("CallWznmDlgMod.carEq");
	if (ix == CALLWZNMDLGMOD_RETREUEQ) return("CallWznmDlgMod.retReuEq");
	if (ix == CALLWZNMDLGRQRYMOD_DLGEQ) return("CallWznmDlgRqryMod.dlgEq");
	if (ix == CALLWZNMDLGRQRYMOD_QRYEQ) return("CallWznmDlgRqryMod.qryEq");
	if (ix == CALLWZNMDLGUPD_REFEQ) return("CallWznmDlgUpd.refEq");
	if (ix == CALLWZNMERR_VEREQ) return("CallWznmErr.verEq");
	if (ix == CALLWZNMERRJTITMOD_ERREQ) return("CallWznmErrJtitMod.errEq");
	if (ix == CALLWZNMERRMOD) return("CallWznmErrMod");
	if (ix == CALLWZNMERRMOD_VEREQ) return("CallWznmErrMod.verEq");
	if (ix == CALLWZNMERRUPD_REFEQ) return("CallWznmErrUpd.refEq");
	if (ix == CALLWZNMEVT_APPEQ) return("CallWznmEvt.appEq");
	if (ix == CALLWZNMEVTMOD) return("CallWznmEvtMod");
	if (ix == CALLWZNMEVTMOD_APPEQ) return("CallWznmEvtMod.appEq");
	if (ix == CALLWZNMEVTUPD_REFEQ) return("CallWznmEvtUpd.refEq");
	if (ix == CALLWZNMFED_SRTEQ) return("CallWznmFed.srtEq");
	if (ix == CALLWZNMFED_SRUEQ) return("CallWznmFed.sruEq");
	if (ix == CALLWZNMFEDMOD) return("CallWznmFedMod");
	if (ix == CALLWZNMFEDMOD_SRTSRUEQ) return("CallWznmFedMod.srtSruEq");
	if (ix == CALLWZNMFEDUPD_REFEQ) return("CallWznmFedUpd.refEq");
	if (ix == CALLWZNMFIL_CLUEQ) return("CallWznmFil.cluEq");
	if (ix == CALLWZNMFIL_RETEQ) return("CallWznmFil.retEq");
	if (ix == CALLWZNMFIL_REUEQ) return("CallWznmFil.reuEq");
	if (ix == CALLWZNMFILMOD) return("CallWznmFilMod");
	if (ix == CALLWZNMFILMOD_CLUEQ) return("CallWznmFilMod.cluEq");
	if (ix == CALLWZNMFILMOD_RETREUEQ) return("CallWznmFilMod.retReuEq");
	if (ix == CALLWZNMFILUPD_REFEQ) return("CallWznmFilUpd.refEq");
	if (ix == CALLWZNMHUSRRUNVMOD_CRDUSREQ) return("CallWznmHusrRunvMod.crdUsrEq");
	if (ix == CALLWZNMIEL_IM2EQ) return("CallWznmIel.im2Eq");
	if (ix == CALLWZNMIEL_IMEEQ) return("CallWznmIel.imeEq");
	if (ix == CALLWZNMIEL_PSTEQ) return("CallWznmIel.pstEq");
	if (ix == CALLWZNMIEL_STBEQ) return("CallWznmIel.stbEq");
	if (ix == CALLWZNMIEL_VITEQ) return("CallWznmIel.vitEq");
	if (ix == CALLWZNMIELJSTBMOD_IELEQ) return("CallWznmIelJstbMod.ielEq");
	if (ix == CALLWZNMIELMOD) return("CallWznmIelMod");
	if (ix == CALLWZNMIELMOD_IMEEQ) return("CallWznmIelMod.imeEq");
	if (ix == CALLWZNMIELMOD_TCOEQ) return("CallWznmIelMod.tcoEq");
	if (ix == CALLWZNMIELUPD_REFEQ) return("CallWznmIelUpd.refEq");
	if (ix == CALLWZNMIEX_JOBEQ) return("CallWznmIex.jobEq");
	if (ix == CALLWZNMIEX_VEREQ) return("CallWznmIex.verEq");
	if (ix == CALLWZNMIEXJTITMOD_IEXEQ) return("CallWznmIexJtitMod.iexEq");
	if (ix == CALLWZNMIEXMOD) return("CallWznmIexMod");
	if (ix == CALLWZNMIEXMOD_VEREQ) return("CallWznmIexMod.verEq");
	if (ix == CALLWZNMIEXUPD_REFEQ) return("CallWznmIexUpd.refEq");
	if (ix == CALLWZNMIME_IEXEQ) return("CallWznmIme.iexEq");
	if (ix == CALLWZNMIME_SUPEQ) return("CallWznmIme.supEq");
	if (ix == CALLWZNMIMEMOD) return("CallWznmImeMod");
	if (ix == CALLWZNMIMEMOD_IEXEQ) return("CallWznmImeMod.iexEq");
	if (ix == CALLWZNMIMEMOD_SUPEQ) return("CallWznmImeMod.supEq");
	if (ix == CALLWZNMIMEMOD_TBLEQ) return("CallWznmImeMod.tblEq");
	if (ix == CALLWZNMIMEUPD_REFEQ) return("CallWznmImeUpd.refEq");
	if (ix == CALLWZNMINTVALPRESET) return("CallWznmIntvalPreSet");
	if (ix == CALLWZNMIXPRESET) return("CallWznmIxPreSet");
	if (ix == CALLWZNMJOB_RETEQ) return("CallWznmJob.retEq");
	if (ix == CALLWZNMJOB_REUEQ) return("CallWznmJob.reuEq");
	if (ix == CALLWZNMJOB_TYPEQ) return("CallWznmJob.typEq");
	if (ix == CALLWZNMJOB_VEREQ) return("CallWznmJob.verEq");
	if (ix == CALLWZNMJOBACMDMOD_JOBEQ) return("CallWznmJobAcmdMod.jobEq");
	if (ix == CALLWZNMJOBAVARMOD_CLUEQ) return("CallWznmJobAvarMod.cluEq");
	if (ix == CALLWZNMJOBAVARMOD_JOBEQ) return("CallWznmJobAvarMod.jobEq");
	if (ix == CALLWZNMJOBMOD) return("CallWznmJobMod");
	if (ix == CALLWZNMJOBMOD_RETREUEQ) return("CallWznmJobMod.retReuEq");
	if (ix == CALLWZNMJOBMOD_VEREQ) return("CallWznmJobMod.verEq");
	if (ix == CALLWZNMJOBRJOBMOD_SUBEQ) return("CallWznmJobRjobMod.subEq");
	if (ix == CALLWZNMJOBRJOBMOD_SUPEQ) return("CallWznmJobRjobMod.supEq");
	if (ix == CALLWZNMJOBROPKMOD_JOBEQ) return("CallWznmJobRopkMod.jobEq");
	if (ix == CALLWZNMJOBROPKMOD_OPKEQ) return("CallWznmJobRopkMod.opkEq");
	if (ix == CALLWZNMJOBROPXMOD_JOBEQ) return("CallWznmJobRopxMod.jobEq");
	if (ix == CALLWZNMJOBROPXMOD_OPXEQ) return("CallWznmJobRopxMod.opxEq");
	if (ix == CALLWZNMJOBUPD_REFEQ) return("CallWznmJobUpd.refEq");
	if (ix == CALLWZNMKLKJKEYMOD_KLSAKEYEQ) return("CallWznmKlkJkeyMod.klsAkeyEq");
	if (ix == CALLWZNMKLSAKEYMOD_KLSEQ) return("CallWznmKlsAkeyMod.klsEq");
	if (ix == CALLWZNMKLSAKEYMOD_KLSMTBURFEQ) return("CallWznmKlsAkeyMod.klsMtbUrfEq");
	if (ix == CALLWZNMLIBAMKFMOD_LIBEQ) return("CallWznmLibAmkfMod.libEq");
	if (ix == CALLWZNMLIBAMKFMOD_MCHEQ) return("CallWznmLibAmkfMod.mchEq");
	if (ix == CALLWZNMLIBAPKLMOD_LIBEQ) return("CallWznmLibApklMod.libEq");
	if (ix == CALLWZNMLIBAPKLMOD_MCHEQ) return("CallWznmLibApklMod.mchEq");
	if (ix == CALLWZNMLIBMOD) return("CallWznmLibMod");
	if (ix == CALLWZNMLIBROPKMOD_LIBEQ) return("CallWznmLibRopkMod.libEq");
	if (ix == CALLWZNMLIBROPKMOD_OPKEQ) return("CallWznmLibRopkMod.opkEq");
	if (ix == CALLWZNMLIBUPD_REFEQ) return("CallWznmLibUpd.refEq");
	if (ix == CALLWZNMLOCJTITMOD_LOCEQ) return("CallWznmLocJtitMod.locEq");
	if (ix == CALLWZNMLOCMOD) return("CallWznmLocMod");
	if (ix == CALLWZNMLOCRVERMOD_LOCEQ) return("CallWznmLocRverMod.locEq");
	if (ix == CALLWZNMLOCRVERMOD_VEREQ) return("CallWznmLocRverMod.verEq");
	if (ix == CALLWZNMLOCUPD_REFEQ) return("CallWznmLocUpd.refEq");
	if (ix == CALLWZNMLOG) return("CallWznmLog");
	if (ix == CALLWZNMLOGOUT) return("CallWznmLogout");
	if (ix == CALLWZNMMCH_CCHEQ) return("CallWznmMch.cchEq");
	if (ix == CALLWZNMMCH_SUPEQ) return("CallWznmMch.supEq");
	if (ix == CALLWZNMMCHAMKFMOD_MCHEQ) return("CallWznmMchAmkfMod.mchEq");
	if (ix == CALLWZNMMCHAPARMOD_MCHEQ) return("CallWznmMchAparMod.mchEq");
	if (ix == CALLWZNMMCHMOD) return("CallWznmMchMod");
	if (ix == CALLWZNMMCHMOD_SUPEQ) return("CallWznmMchMod.supEq");
	if (ix == CALLWZNMMCHUPD_REFEQ) return("CallWznmMchUpd.refEq");
	if (ix == CALLWZNMMDL_VEREQ) return("CallWznmMdl.verEq");
	if (ix == CALLWZNMMDLJMOD_MDLEQ) return("CallWznmMdlJMod.mdlEq");
	if (ix == CALLWZNMMDLMOD) return("CallWznmMdlMod");
	if (ix == CALLWZNMMDLMOD_VEREQ) return("CallWznmMdlMod.verEq");
	if (ix == CALLWZNMMDLUPD_REFEQ) return("CallWznmMdlUpd.refEq");
	if (ix == CALLWZNMMONSTATCHG) return("CallWznmMonstatChg");
	if (ix == CALLWZNMMTD_JOBEQ) return("CallWznmMtd.jobEq");
	if (ix == CALLWZNMMTDAIPAMOD_MTDEQ) return("CallWznmMtdAipaMod.mtdEq");
	if (ix == CALLWZNMMTDARPAMOD_MTDEQ) return("CallWznmMtdArpaMod.mtdEq");
	if (ix == CALLWZNMMTDMOD) return("CallWznmMtdMod");
	if (ix == CALLWZNMMTDMOD_JOBEQ) return("CallWznmMtdMod.jobEq");
	if (ix == CALLWZNMMTDUPD_REFEQ) return("CallWznmMtdUpd.refEq");
	if (ix == CALLWZNMNODECHG) return("CallWznmNodeChg");
	if (ix == CALLWZNMOPK_SQKEQ) return("CallWznmOpk.sqkEq");
	if (ix == CALLWZNMOPK_VEREQ) return("CallWznmOpk.verEq");
	if (ix == CALLWZNMOPKAINVMOD_CLUEQ) return("CallWznmOpkAinvMod.cluEq");
	if (ix == CALLWZNMOPKAINVMOD_OPKEQ) return("CallWznmOpkAinvMod.opkEq");
	if (ix == CALLWZNMOPKARETMOD_CLUEQ) return("CallWznmOpkAretMod.cluEq");
	if (ix == CALLWZNMOPKARETMOD_OPKEQ) return("CallWznmOpkAretMod.opkEq");
	if (ix == CALLWZNMOPKMOD) return("CallWznmOpkMod");
	if (ix == CALLWZNMOPKMOD_VEREQ) return("CallWznmOpkMod.verEq");
	if (ix == CALLWZNMOPKUPD_REFEQ) return("CallWznmOpkUpd.refEq");
	if (ix == CALLWZNMOPX_OPKEQ) return("CallWznmOpx.opkEq");
	if (ix == CALLWZNMOPX_SQKEQ) return("CallWznmOpx.sqkEq");
	if (ix == CALLWZNMOPXAINVMOD_CLUEQ) return("CallWznmOpxAinvMod.cluEq");
	if (ix == CALLWZNMOPXAINVMOD_OPXEQ) return("CallWznmOpxAinvMod.opxEq");
	if (ix == CALLWZNMOPXARETMOD_CLUEQ) return("CallWznmOpxAretMod.cluEq");
	if (ix == CALLWZNMOPXARETMOD_OPXEQ) return("CallWznmOpxAretMod.opxEq");
	if (ix == CALLWZNMOPXMOD) return("CallWznmOpxMod");
	if (ix == CALLWZNMOPXMOD_OPKEQ) return("CallWznmOpxMod.opkEq");
	if (ix == CALLWZNMOPXUPD_REFEQ) return("CallWznmOpxUpd.refEq");
	if (ix == CALLWZNMPNL_CAREQ) return("CallWznmPnl.carEq");
	if (ix == CALLWZNMPNL_JOBEQ) return("CallWznmPnl.jobEq");
	if (ix == CALLWZNMPNL_RETEQ) return("CallWznmPnl.retEq");
	if (ix == CALLWZNMPNL_REUEQ) return("CallWznmPnl.reuEq");
	if (ix == CALLWZNMPNLMOD) return("CallWznmPnlMod");
	if (ix == CALLWZNMPNLMOD_CAREQ) return("CallWznmPnlMod.carEq");
	if (ix == CALLWZNMPNLMOD_RETREUEQ) return("CallWznmPnlMod.retReuEq");
	if (ix == CALLWZNMPNLRQRYMOD_PNLEQ) return("CallWznmPnlRqryMod.pnlEq");
	if (ix == CALLWZNMPNLRQRYMOD_QRYEQ) return("CallWznmPnlRqryMod.qryEq");
	if (ix == CALLWZNMPNLUPD_REFEQ) return("CallWznmPnlUpd.refEq");
	if (ix == CALLWZNMPRJ_VEREQ) return("CallWznmPrj.verEq");
	if (ix == CALLWZNMPRJMOD) return("CallWznmPrjMod");
	if (ix == CALLWZNMPRJUPD_REFEQ) return("CallWznmPrjUpd.refEq");
	if (ix == CALLWZNMPRSADETMOD_PRSEQ) return("CallWznmPrsAdetMod.prsEq");
	if (ix == CALLWZNMPRSJLNMMOD_PRSEQ) return("CallWznmPrsJlnmMod.prsEq");
	if (ix == CALLWZNMPRSMOD) return("CallWznmPrsMod");
	if (ix == CALLWZNMPRSRPRJMOD_PRJEQ) return("CallWznmPrsRprjMod.prjEq");
	if (ix == CALLWZNMPRSRPRJMOD_PRSEQ) return("CallWznmPrsRprjMod.prsEq");
	if (ix == CALLWZNMPRSUPD_REFEQ) return("CallWznmPrsUpd.refEq");
	if (ix == CALLWZNMPST_RETEQ) return("CallWznmPst.retEq");
	if (ix == CALLWZNMPST_REUEQ) return("CallWznmPst.reuEq");
	if (ix == CALLWZNMPST_VEREQ) return("CallWznmPst.verEq");
	if (ix == CALLWZNMPSTJTITMOD_PSTEQ) return("CallWznmPstJtitMod.pstEq");
	if (ix == CALLWZNMPSTMOD) return("CallWznmPstMod");
	if (ix == CALLWZNMPSTMOD_RETREUEQ) return("CallWznmPstMod.retReuEq");
	if (ix == CALLWZNMPSTMOD_VEREQ) return("CallWznmPstMod.verEq");
	if (ix == CALLWZNMPSTUPD_REFEQ) return("CallWznmPstUpd.refEq");
	if (ix == CALLWZNMQCO_QRYEQ) return("CallWznmQco.qryEq");
	if (ix == CALLWZNMQCO_STBEQ) return("CallWznmQco.stbEq");
	if (ix == CALLWZNMQCOJSTBMOD_QCOEQ) return("CallWznmQcoJstbMod.qcoEq");
	if (ix == CALLWZNMQCOMOD) return("CallWznmQcoMod");
	if (ix == CALLWZNMQCOMOD_QRYEQ) return("CallWznmQcoMod.qryEq");
	if (ix == CALLWZNMQCOMOD_TCOEQ) return("CallWznmQcoMod.tcoEq");
	if (ix == CALLWZNMQCOUPD_REFEQ) return("CallWznmQcoUpd.refEq");
	if (ix == CALLWZNMQMD_PSTEQ) return("CallWznmQmd.pstEq");
	if (ix == CALLWZNMQMD_QRYEQ) return("CallWznmQmd.qryEq");
	if (ix == CALLWZNMQMD_RETEQ) return("CallWznmQmd.retEq");
	if (ix == CALLWZNMQMD_REUEQ) return("CallWznmQmd.reuEq");
	if (ix == CALLWZNMQMDMOD) return("CallWznmQmdMod");
	if (ix == CALLWZNMQMDMOD_PSTEQ) return("CallWznmQmdMod.pstEq");
	if (ix == CALLWZNMQMDMOD_QRYEQ) return("CallWznmQmdMod.qryEq");
	if (ix == CALLWZNMQMDMOD_RETREUEQ) return("CallWznmQmdMod.retReuEq");
	if (ix == CALLWZNMQMDUPD_REFEQ) return("CallWznmQmdUpd.refEq");
	if (ix == CALLWZNMQRY_JOBEQ) return("CallWznmQry.jobEq");
	if (ix == CALLWZNMQRY_SUPEQ) return("CallWznmQry.supEq");
	if (ix == CALLWZNMQRY_VEREQ) return("CallWznmQry.verEq");
	if (ix == CALLWZNMQRYACSEMOD_QMDEQ) return("CallWznmQryAcseMod.qmdEq");
	if (ix == CALLWZNMQRYACSEMOD_QRYEQ) return("CallWznmQryAcseMod.qryEq");
	if (ix == CALLWZNMQRYAORDMOD_QRYEQ) return("CallWznmQryAordMod.qryEq");
	if (ix == CALLWZNMQRYMOD) return("CallWznmQryMod");
	if (ix == CALLWZNMQRYMOD_SUPEQ) return("CallWznmQryMod.supEq");
	if (ix == CALLWZNMQRYMOD_VEREQ) return("CallWznmQryMod.verEq");
	if (ix == CALLWZNMQRYRTBLMOD_QRYEQ) return("CallWznmQryRtblMod.qryEq");
	if (ix == CALLWZNMQRYRTBLMOD_TBLEQ) return("CallWznmQryRtblMod.tblEq");
	if (ix == CALLWZNMQRYUPD_REFEQ) return("CallWznmQryUpd.refEq");
	if (ix == CALLWZNMRECACCESS) return("CallWznmRecaccess");
	if (ix == CALLWZNMREFPRESET) return("CallWznmRefPreSet");
	if (ix == CALLWZNMREFSPRESET) return("CallWznmRefsPreSet");
	if (ix == CALLWZNMREL_CLUEQ) return("CallWznmRel.cluEq");
	if (ix == CALLWZNMREL_FRSEQ) return("CallWznmRel.frsEq");
	if (ix == CALLWZNMREL_SUPEQ) return("CallWznmRel.supEq");
	if (ix == CALLWZNMREL_TOSEQ) return("CallWznmRel.tosEq");
	if (ix == CALLWZNMREL_VEREQ) return("CallWznmRel.verEq");
	if (ix == CALLWZNMRELATITMOD_LOCEQ) return("CallWznmRelAtitMod.locEq");
	if (ix == CALLWZNMRELATITMOD_RELEQ) return("CallWznmRelAtitMod.relEq");
	if (ix == CALLWZNMRELMOD) return("CallWznmRelMod");
	if (ix == CALLWZNMRELMOD_CLUEQ) return("CallWznmRelMod.cluEq");
	if (ix == CALLWZNMRELMOD_FRTEQ) return("CallWznmRelMod.frtEq");
	if (ix == CALLWZNMRELMOD_SUPEQ) return("CallWznmRelMod.supEq");
	if (ix == CALLWZNMRELMOD_TOTEQ) return("CallWznmRelMod.totEq");
	if (ix == CALLWZNMRELMOD_VEREQ) return("CallWznmRelMod.verEq");
	if (ix == CALLWZNMRELUPD_REFEQ) return("CallWznmRelUpd.refEq");
	if (ix == CALLWZNMREPTRSTART) return("CallWznmReptrStart");
	if (ix == CALLWZNMREPTRSTOP) return("CallWznmReptrStop");
	if (ix == CALLWZNMRLS_CMPEQ) return("CallWznmRls.cmpEq");
	if (ix == CALLWZNMRLS_MCHEQ) return("CallWznmRls.mchEq");
	if (ix == CALLWZNMRLSMOD) return("CallWznmRlsMod");
	if (ix == CALLWZNMRLSMOD_CMPEQ) return("CallWznmRlsMod.cmpEq");
	if (ix == CALLWZNMRLSMOD_MCHEQ) return("CallWznmRlsMod.mchEq");
	if (ix == CALLWZNMRLSUPD_REFEQ) return("CallWznmRlsUpd.refEq");
	if (ix == CALLWZNMRTBMOD) return("CallWznmRtbMod");
	if (ix == CALLWZNMRTBMOD_RETREUEQ) return("CallWznmRtbMod.retReuEq");
	if (ix == CALLWZNMRTBMOD_RTJEQ) return("CallWznmRtbMod.rtjEq");
	if (ix == CALLWZNMRTBUPD_REFEQ) return("CallWznmRtbUpd.refEq");
	if (ix == CALLWZNMRTDMOD) return("CallWznmRtdMod");
	if (ix == CALLWZNMRTDMOD_BLKEQ) return("CallWznmRtdMod.blkEq");
	if (ix == CALLWZNMRTDMOD_RTJEQ) return("CallWznmRtdMod.rtjEq");
	if (ix == CALLWZNMRTDUPD_REFEQ) return("CallWznmRtdUpd.refEq");
	if (ix == CALLWZNMRTJ_APPEQ) return("CallWznmRtj.appEq");
	if (ix == CALLWZNMRTJ_JOBEQ) return("CallWznmRtj.jobEq");
	if (ix == CALLWZNMRTJ_SUPEQ) return("CallWznmRtj.supEq");
	if (ix == CALLWZNMRTJMOD) return("CallWznmRtjMod");
	if (ix == CALLWZNMRTJMOD_APPEQ) return("CallWznmRtjMod.appEq");
	if (ix == CALLWZNMRTJMOD_JOBEQ) return("CallWznmRtjMod.jobEq");
	if (ix == CALLWZNMRTJMOD_SUPEQ) return("CallWznmRtjMod.supEq");
	if (ix == CALLWZNMRTJUPD_REFEQ) return("CallWznmRtjUpd.refEq");
	if (ix == CALLWZNMSBS_CAREQ) return("CallWznmSbs.carEq");
	if (ix == CALLWZNMSBS_PSTEQ) return("CallWznmSbs.pstEq");
	if (ix == CALLWZNMSBSATITMOD_LOCEQ) return("CallWznmSbsAtitMod.locEq");
	if (ix == CALLWZNMSBSATITMOD_SBSEQ) return("CallWznmSbsAtitMod.sbsEq");
	if (ix == CALLWZNMSBSMOD) return("CallWznmSbsMod");
	if (ix == CALLWZNMSBSMOD_TBLEQ) return("CallWznmSbsMod.tblEq");
	if (ix == CALLWZNMSBSRSBSMOD_ASBEQ) return("CallWznmSbsRsbsMod.asbEq");
	if (ix == CALLWZNMSBSRSBSMOD_BSBEQ) return("CallWznmSbsRsbsMod.bsbEq");
	if (ix == CALLWZNMSBSUPD_REFEQ) return("CallWznmSbsUpd.refEq");
	if (ix == CALLWZNMSEQ_APPEQ) return("CallWznmSeq.appEq");
	if (ix == CALLWZNMSEQMOD) return("CallWznmSeqMod");
	if (ix == CALLWZNMSEQMOD_APPEQ) return("CallWznmSeqMod.appEq");
	if (ix == CALLWZNMSEQUPD_REFEQ) return("CallWznmSeqUpd.refEq");
	if (ix == CALLWZNMSESMOD) return("CallWznmSesMod");
	if (ix == CALLWZNMSESMOD_USREQ) return("CallWznmSesMod.usrEq");
	if (ix == CALLWZNMSESUPD_REFEQ) return("CallWznmSesUpd.refEq");
	if (ix == CALLWZNMSGE_FNXEQ) return("CallWznmSge.fnxEq");
	if (ix == CALLWZNMSGE_JOBEQ) return("CallWznmSge.jobEq");
	if (ix == CALLWZNMSGE_SNXEQ) return("CallWznmSge.snxEq");
	if (ix == CALLWZNMSGE_SQKEQ) return("CallWznmSge.sqkEq");
	if (ix == CALLWZNMSGECHG) return("CallWznmSgeChg");
	if (ix == CALLWZNMSGEMOD) return("CallWznmSgeMod");
	if (ix == CALLWZNMSGEMOD_JOBEQ) return("CallWznmSgeMod.jobEq");
	if (ix == CALLWZNMSGEUPD_REFEQ) return("CallWznmSgeUpd.refEq");
	if (ix == CALLWZNMSHRDATCHG) return("CallWznmShrdatChg");
	if (ix == CALLWZNMSNSMOD) return("CallWznmSnsMod");
	if (ix == CALLWZNMSNSMOD_CALEQ) return("CallWznmSnsMod.calEq");
	if (ix == CALLWZNMSNSMOD_JOBEQ) return("CallWznmSnsMod.jobEq");
	if (ix == CALLWZNMSNSUPD_REFEQ) return("CallWznmSnsUpd.refEq");
	if (ix == CALLWZNMSQKJTITMOD_SQKEQ) return("CallWznmSqkJtitMod.sqkEq");
	if (ix == CALLWZNMSQKMOD) return("CallWznmSqkMod");
	if (ix == CALLWZNMSQKMOD_RETREUEQ) return("CallWznmSqkMod.retReuEq");
	if (ix == CALLWZNMSQKRSTBMOD_SQKEQ) return("CallWznmSqkRstbMod.sqkEq");
	if (ix == CALLWZNMSQKRSTBMOD_STBEQ) return("CallWznmSqkRstbMod.stbEq");
	if (ix == CALLWZNMSQKUPD_REFEQ) return("CallWznmSqkUpd.refEq");
	if (ix == CALLWZNMSREFPRESET) return("CallWznmSrefPreSet");
	if (ix == CALLWZNMSTATCHG) return("CallWznmStatChg");
	if (ix == CALLWZNMSTB_SBSEQ) return("CallWznmStb.sbsEq");
	if (ix == CALLWZNMSTB_TCOEQ) return("CallWznmStb.tcoEq");
	if (ix == CALLWZNMSTBMOD) return("CallWznmStbMod");
	if (ix == CALLWZNMSTBMOD_TBLEQ) return("CallWznmStbMod.tblEq");
	if (ix == CALLWZNMSTBRSTBMOD_SUBEQ) return("CallWznmStbRstbMod.subEq");
	if (ix == CALLWZNMSTBRSTBMOD_SUPEQ) return("CallWznmStbRstbMod.supEq");
	if (ix == CALLWZNMSTBUPD_REFEQ) return("CallWznmStbUpd.refEq");
	if (ix == CALLWZNMSTE_SEQEQ) return("CallWznmSte.seqEq");
	if (ix == CALLWZNMSTEAACTMOD_STEEQ) return("CallWznmSteAactMod.steEq");
	if (ix == CALLWZNMSTEATRGMOD_STEEQ) return("CallWznmSteAtrgMod.steEq");
	if (ix == CALLWZNMSTEMOD) return("CallWznmSteMod");
	if (ix == CALLWZNMSTEMOD_SEQEQ) return("CallWznmSteMod.seqEq");
	if (ix == CALLWZNMSTEUPD_REFEQ) return("CallWznmSteUpd.refEq");
	if (ix == CALLWZNMSTGCHG) return("CallWznmStgChg");
	if (ix == CALLWZNMSTRJCNDMOD_STEATRGEQ) return("CallWznmStrJcndMod.steAtrgEq");
	if (ix == CALLWZNMSTUBCHG) return("CallWznmStubChg");
	if (ix == CALLWZNMSUSPSESS) return("CallWznmSuspsess");
	if (ix == CALLWZNMTAG_CPBEQ) return("CallWznmTag.cpbEq");
	if (ix == CALLWZNMTAGJTITMOD_TAGEQ) return("CallWznmTagJtitMod.tagEq");
	if (ix == CALLWZNMTAGMOD) return("CallWznmTagMod");
	if (ix == CALLWZNMTAGMOD_CPBEQ) return("CallWznmTagMod.cpbEq");
	if (ix == CALLWZNMTAGUPD_REFEQ) return("CallWznmTagUpd.refEq");
	if (ix == CALLWZNMTBL_CAREQ) return("CallWznmTbl.carEq");
	if (ix == CALLWZNMTBL_INSBS) return("CallWznmTbl.inSbs");
	if (ix == CALLWZNMTBL_PSTEQ) return("CallWznmTbl.pstEq");
	if (ix == CALLWZNMTBL_RETEQ) return("CallWznmTbl.retEq");
	if (ix == CALLWZNMTBL_REUEQ) return("CallWznmTbl.reuEq");
	if (ix == CALLWZNMTBL_TYPEQ) return("CallWznmTbl.typEq");
	if (ix == CALLWZNMTBL_VEREQ) return("CallWznmTbl.verEq");
	if (ix == CALLWZNMTBLALFCMOD_TBLEQ) return("CallWznmTblAlfcMod.tblEq");
	if (ix == CALLWZNMTBLATITMOD_LOCEQ) return("CallWznmTblAtitMod.locEq");
	if (ix == CALLWZNMTBLATITMOD_TBLEQ) return("CallWznmTblAtitMod.tblEq");
	if (ix == CALLWZNMTBLMOD) return("CallWznmTblMod");
	if (ix == CALLWZNMTBLMOD_RETREUEQ) return("CallWznmTblMod.retReuEq");
	if (ix == CALLWZNMTBLMOD_VEREQ) return("CallWznmTblMod.verEq");
	if (ix == CALLWZNMTBLRVECMOD_TBLEQ) return("CallWznmTblRvecMod.tblEq");
	if (ix == CALLWZNMTBLRVECMOD_VECEQ) return("CallWznmTblRvecMod.vecEq");
	if (ix == CALLWZNMTBLUPD_REFEQ) return("CallWznmTblUpd.refEq");
	if (ix == CALLWZNMTCO_FCTEQ) return("CallWznmTco.fctEq");
	if (ix == CALLWZNMTCO_FCUEQ) return("CallWznmTco.fcuEq");
	if (ix == CALLWZNMTCO_INSBS) return("CallWznmTco.inSbs");
	if (ix == CALLWZNMTCO_RELEQ) return("CallWznmTco.relEq");
	if (ix == CALLWZNMTCO_SBSEQ) return("CallWznmTco.sbsEq");
	if (ix == CALLWZNMTCO_TBL_INSBS) return("CallWznmTco.tbl.inSbs");
	if (ix == CALLWZNMTCO_TBLEQ) return("CallWznmTco.tblEq");
	if (ix == CALLWZNMTCOATITMOD_LOCEQ) return("CallWznmTcoAtitMod.locEq");
	if (ix == CALLWZNMTCOATITMOD_TCOEQ) return("CallWznmTcoAtitMod.tcoEq");
	if (ix == CALLWZNMTCOMOD) return("CallWznmTcoMod");
	if (ix == CALLWZNMTCOMOD_FCTFCUEQ) return("CallWznmTcoMod.fctFcuEq");
	if (ix == CALLWZNMTCOMOD_RELEQ) return("CallWznmTcoMod.relEq");
	if (ix == CALLWZNMTCOMOD_TBLEQ) return("CallWznmTcoMod.tblEq");
	if (ix == CALLWZNMTCOUPD_REFEQ) return("CallWznmTcoUpd.refEq");
	if (ix == CALLWZNMTXTVALPRESET) return("CallWznmTxtvalPreSet");
	if (ix == CALLWZNMUSGAACCMOD_USGEQ) return("CallWznmUsgAaccMod.usgEq");
	if (ix == CALLWZNMUSGMOD) return("CallWznmUsgMod");
	if (ix == CALLWZNMUSGUPD_REFEQ) return("CallWznmUsgUpd.refEq");
	if (ix == CALLWZNMUSR_PRSEQ) return("CallWznmUsr.prsEq");
	if (ix == CALLWZNMUSR_USGEQ) return("CallWznmUsr.usgEq");
	if (ix == CALLWZNMUSRAACCMOD_USREQ) return("CallWznmUsrAaccMod.usrEq");
	if (ix == CALLWZNMUSRJSTEMOD_USREQ) return("CallWznmUsrJsteMod.usrEq");
	if (ix == CALLWZNMUSRMOD) return("CallWznmUsrMod");
	if (ix == CALLWZNMUSRRUSGMOD_USGEQ) return("CallWznmUsrRusgMod.usgEq");
	if (ix == CALLWZNMUSRRUSGMOD_USREQ) return("CallWznmUsrRusgMod.usrEq");
	if (ix == CALLWZNMUSRUPD_REFEQ) return("CallWznmUsrUpd.refEq");
	if (ix == CALLWZNMVEC_HKTEQ) return("CallWznmVec.hktEq");
	if (ix == CALLWZNMVEC_HKUEQ) return("CallWznmVec.hkuEq");
	if (ix == CALLWZNMVEC_INSBS) return("CallWznmVec.inSbs");
	if (ix == CALLWZNMVEC_PSTEQ) return("CallWznmVec.pstEq");
	if (ix == CALLWZNMVEC_TYPEQ) return("CallWznmVec.typEq");
	if (ix == CALLWZNMVEC_VEREQ) return("CallWznmVec.verEq");
	if (ix == CALLWZNMVECATITMOD_LOCEQ) return("CallWznmVecAtitMod.locEq");
	if (ix == CALLWZNMVECATITMOD_VECEQ) return("CallWznmVecAtitMod.vecEq");
	if (ix == CALLWZNMVECMOD) return("CallWznmVecMod");
	if (ix == CALLWZNMVECMOD_HKTHKUEQ) return("CallWznmVecMod.hktHkuEq");
	if (ix == CALLWZNMVECMOD_VEREQ) return("CallWznmVecMod.verEq");
	if (ix == CALLWZNMVECUPD_REFEQ) return("CallWznmVecUpd.refEq");
	if (ix == CALLWZNMVER_BVREQ) return("CallWznmVer.bvrEq");
	if (ix == CALLWZNMVER_LOCEQ) return("CallWznmVer.locEq");
	if (ix == CALLWZNMVER_PRJEQ) return("CallWznmVer.prjEq");
	if (ix == CALLWZNMVER_STEEQ) return("CallWznmVer.steEq");
	if (ix == CALLWZNMVERJMOD_VEREQ) return("CallWznmVerJMod.verEq");
	if (ix == CALLWZNMVERJSTEMOD_VEREQ) return("CallWznmVerJsteMod.verEq");
	if (ix == CALLWZNMVERMOD) return("CallWznmVerMod");
	if (ix == CALLWZNMVERMOD_BVREQ) return("CallWznmVerMod.bvrEq");
	if (ix == CALLWZNMVERMOD_PRJEQ) return("CallWznmVerMod.prjEq");
	if (ix == CALLWZNMVERUPD_REFEQ) return("CallWznmVerUpd.refEq");
	if (ix == CALLWZNMVIT_VECEQ) return("CallWznmVit.vecEq");
	if (ix == CALLWZNMVITJMOD_VITEQ) return("CallWznmVitJMod.vitEq");
	if (ix == CALLWZNMVITMOD) return("CallWznmVitMod");
	if (ix == CALLWZNMVITMOD_VECEQ) return("CallWznmVitMod.vecEq");
	if (ix == CALLWZNMVITUPD_REFEQ) return("CallWznmVitUpd.refEq");

	return("");
};
