/**
	* \file VecWznmVJob.cpp
	* vector VecWznmVJob (implementation)
	* \author Alexander Wirthmueller
	* \date created: 11 Jul 2020
	* \date modified: 11 Jul 2020
	*/

#include "VecWznmVJob.h"

using namespace std;
using namespace Sbecore;
using namespace Xmlio;

/******************************************************************************
 namespace VecWznmVJob
 ******************************************************************************/

uint VecWznmVJob::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "crdwznmapp") return CRDWZNMAPP;
	if (s == "crdwznmblk") return CRDWZNMBLK;
	if (s == "crdwznmcal") return CRDWZNMCAL;
	if (s == "crdwznmcap") return CRDWZNMCAP;
	if (s == "crdwznmcar") return CRDWZNMCAR;
	if (s == "crdwznmchk") return CRDWZNMCHK;
	if (s == "crdwznmcmp") return CRDWZNMCMP;
	if (s == "crdwznmcon") return CRDWZNMCON;
	if (s == "crdwznmctp") return CRDWZNMCTP;
	if (s == "crdwznmdlg") return CRDWZNMDLG;
	if (s == "crdwznmerr") return CRDWZNMERR;
	if (s == "crdwznmfil") return CRDWZNMFIL;
	if (s == "crdwznmiel") return CRDWZNMIEL;
	if (s == "crdwznmiex") return CRDWZNMIEX;
	if (s == "crdwznmime") return CRDWZNMIME;
	if (s == "crdwznmjob") return CRDWZNMJOB;
	if (s == "crdwznmlib") return CRDWZNMLIB;
	if (s == "crdwznmloc") return CRDWZNMLOC;
	if (s == "crdwznmmch") return CRDWZNMMCH;
	if (s == "crdwznmmdl") return CRDWZNMMDL;
	if (s == "crdwznmmtd") return CRDWZNMMTD;
	if (s == "crdwznmmty") return CRDWZNMMTY;
	if (s == "crdwznmnav") return CRDWZNMNAV;
	if (s == "crdwznmopk") return CRDWZNMOPK;
	if (s == "crdwznmopx") return CRDWZNMOPX;
	if (s == "crdwznmpnl") return CRDWZNMPNL;
	if (s == "crdwznmprj") return CRDWZNMPRJ;
	if (s == "crdwznmprs") return CRDWZNMPRS;
	if (s == "crdwznmpst") return CRDWZNMPST;
	if (s == "crdwznmqco") return CRDWZNMQCO;
	if (s == "crdwznmqmd") return CRDWZNMQMD;
	if (s == "crdwznmqry") return CRDWZNMQRY;
	if (s == "crdwznmrel") return CRDWZNMREL;
	if (s == "crdwznmrls") return CRDWZNMRLS;
	if (s == "crdwznmrtj") return CRDWZNMRTJ;
	if (s == "crdwznmsbs") return CRDWZNMSBS;
	if (s == "crdwznmseq") return CRDWZNMSEQ;
	if (s == "crdwznmsge") return CRDWZNMSGE;
	if (s == "crdwznmstb") return CRDWZNMSTB;
	if (s == "crdwznmste") return CRDWZNMSTE;
	if (s == "crdwznmtag") return CRDWZNMTAG;
	if (s == "crdwznmtbl") return CRDWZNMTBL;
	if (s == "crdwznmtco") return CRDWZNMTCO;
	if (s == "crdwznmusg") return CRDWZNMUSG;
	if (s == "crdwznmusr") return CRDWZNMUSR;
	if (s == "crdwznmutl") return CRDWZNMUTL;
	if (s == "crdwznmvec") return CRDWZNMVEC;
	if (s == "crdwznmver") return CRDWZNMVER;
	if (s == "crdwznmvit") return CRDWZNMVIT;
	if (s == "dlgwznmappimpstr") return DLGWZNMAPPIMPSTR;
	if (s == "dlgwznmappnew") return DLGWZNMAPPNEW;
	if (s == "dlgwznmappwrite") return DLGWZNMAPPWRITE;
	if (s == "dlgwznmfildownload") return DLGWZNMFILDOWNLOAD;
	if (s == "dlgwznmfilnew") return DLGWZNMFILNEW;
	if (s == "dlgwznmnavloaini") return DLGWZNMNAVLOAINI;
	if (s == "dlgwznmnavmnglic") return DLGWZNMNAVMNGLIC;
	if (s == "dlgwznmprjimpex") return DLGWZNMPRJIMPEX;
	if (s == "dlgwznmprjnew") return DLGWZNMPRJNEW;
	if (s == "dlgwznmrlsfinreptr") return DLGWZNMRLSFINREPTR;
	if (s == "dlgwznmrlsstareptr") return DLGWZNMRLSSTAREPTR;
	if (s == "dlgwznmrlswrite") return DLGWZNMRLSWRITE;
	if (s == "dlgwznmusrmngkeypair") return DLGWZNMUSRMNGKEYPAIR;
	if (s == "dlgwznmutlextrip") return DLGWZNMUTLEXTRIP;
	if (s == "dlgwznmutliexconv") return DLGWZNMUTLIEXCONV;
	if (s == "dlgwznmutlmrgip") return DLGWZNMUTLMRGIP;
	if (s == "dlgwznmverbscui") return DLGWZNMVERBSCUI;
	if (s == "dlgwznmvercustjob") return DLGWZNMVERCUSTJOB;
	if (s == "dlgwznmvercustjtr") return DLGWZNMVERCUSTJTR;
	if (s == "dlgwznmvercustui") return DLGWZNMVERCUSTUI;
	if (s == "dlgwznmverdbstr") return DLGWZNMVERDBSTR;
	if (s == "dlgwznmverdeploy") return DLGWZNMVERDEPLOY;
	if (s == "dlgwznmverfinmod") return DLGWZNMVERFINMOD;
	if (s == "dlgwznmvergenjtr") return DLGWZNMVERGENJTR;
	if (s == "dlgwznmvergenui") return DLGWZNMVERGENUI;
	if (s == "dlgwznmverglobal") return DLGWZNMVERGLOBAL;
	if (s == "dlgwznmverimpexp") return DLGWZNMVERIMPEXP;
	if (s == "dlgwznmvernew") return DLGWZNMVERNEW;
	if (s == "dlgwznmveroppack") return DLGWZNMVEROPPACK;
	if (s == "dlgwznmverwrstkit") return DLGWZNMVERWRSTKIT;
	if (s == "jobwznmiexapp") return JOBWZNMIEXAPP;
	if (s == "jobwznmiexbui") return JOBWZNMIEXBUI;
	if (s == "jobwznmiexdbs") return JOBWZNMIEXDBS;
	if (s == "jobwznmiexdpl") return JOBWZNMIEXDPL;
	if (s == "jobwznmiexgbl") return JOBWZNMIEXGBL;
	if (s == "jobwznmiexiex") return JOBWZNMIEXIEX;
	if (s == "jobwznmiexini") return JOBWZNMIEXINI;
	if (s == "jobwznmiexjob") return JOBWZNMIEXJOB;
	if (s == "jobwznmiexjtr") return JOBWZNMIEXJTR;
	if (s == "jobwznmiexopk") return JOBWZNMIEXOPK;
	if (s == "jobwznmiexprj") return JOBWZNMIEXPRJ;
	if (s == "jobwznmiexuix") return JOBWZNMIEXUIX;
	if (s == "jobwznmlicense") return JOBWZNMLICENSE;
	if (s == "pnlwznmapp1nrtjob") return PNLWZNMAPP1NRTJOB;
	if (s == "pnlwznmappapp1nsequence") return PNLWZNMAPPAPP1NSEQUENCE;
	if (s == "pnlwznmappdetail") return PNLWZNMAPPDETAIL;
	if (s == "pnlwznmappheadbar") return PNLWZNMAPPHEADBAR;
	if (s == "pnlwznmapplist") return PNLWZNMAPPLIST;
	if (s == "pnlwznmapprec") return PNLWZNMAPPREC;
	if (s == "pnlwznmappref1nfile") return PNLWZNMAPPREF1NFILE;
	if (s == "pnlwznmblk1nrtdpch") return PNLWZNMBLK1NRTDPCH;
	if (s == "pnlwznmblkaitem") return PNLWZNMBLKAITEM;
	if (s == "pnlwznmblkdetail") return PNLWZNMBLKDETAIL;
	if (s == "pnlwznmblkheadbar") return PNLWZNMBLKHEADBAR;
	if (s == "pnlwznmblklist") return PNLWZNMBLKLIST;
	if (s == "pnlwznmblkrec") return PNLWZNMBLKREC;
	if (s == "pnlwznmblkref1nrtblock") return PNLWZNMBLKREF1NRTBLOCK;
	if (s == "pnlwznmcal1nsensitivity") return PNLWZNMCAL1NSENSITIVITY;
	if (s == "pnlwznmcaldetail") return PNLWZNMCALDETAIL;
	if (s == "pnlwznmcalheadbar") return PNLWZNMCALHEADBAR;
	if (s == "pnlwznmcallist") return PNLWZNMCALLIST;
	if (s == "pnlwznmcalmnstub") return PNLWZNMCALMNSTUB;
	if (s == "pnlwznmcalrec") return PNLWZNMCALREC;
	if (s == "pnlwznmcapapar") return PNLWZNMCAPAPAR;
	if (s == "pnlwznmcapdetail") return PNLWZNMCAPDETAIL;
	if (s == "pnlwznmcapheadbar") return PNLWZNMCAPHEADBAR;
	if (s == "pnlwznmcaplist") return PNLWZNMCAPLIST;
	if (s == "pnlwznmcaprec") return PNLWZNMCAPREC;
	if (s == "pnlwznmcar1ndialog") return PNLWZNMCAR1NDIALOG;
	if (s == "pnlwznmcarcar1npanel") return PNLWZNMCARCAR1NPANEL;
	if (s == "pnlwznmcardetail") return PNLWZNMCARDETAIL;
	if (s == "pnlwznmcarheadbar") return PNLWZNMCARHEADBAR;
	if (s == "pnlwznmcarhk1ncontrol") return PNLWZNMCARHK1NCONTROL;
	if (s == "pnlwznmcarlist") return PNLWZNMCARLIST;
	if (s == "pnlwznmcarrec") return PNLWZNMCARREC;
	if (s == "pnlwznmchkdetail") return PNLWZNMCHKDETAIL;
	if (s == "pnlwznmchkheadbar") return PNLWZNMCHKHEADBAR;
	if (s == "pnlwznmchklist") return PNLWZNMCHKLIST;
	if (s == "pnlwznmchkrec") return PNLWZNMCHKREC;
	if (s == "pnlwznmchkref1ncall") return PNLWZNMCHKREF1NCALL;
	if (s == "pnlwznmcmp1nrelease") return PNLWZNMCMP1NRELEASE;
	if (s == "pnlwznmcmpdetail") return PNLWZNMCMPDETAIL;
	if (s == "pnlwznmcmpheadbar") return PNLWZNMCMPHEADBAR;
	if (s == "pnlwznmcmplist") return PNLWZNMCMPLIST;
	if (s == "pnlwznmcmpmnlibrary") return PNLWZNMCMPMNLIBRARY;
	if (s == "pnlwznmcmpmnoppack") return PNLWZNMCMPMNOPPACK;
	if (s == "pnlwznmcmprec") return PNLWZNMCMPREC;
	if (s == "pnlwznmconapar") return PNLWZNMCONAPAR;
	if (s == "pnlwznmcondetail") return PNLWZNMCONDETAIL;
	if (s == "pnlwznmconfedref1nrtblock") return PNLWZNMCONFEDREF1NRTBLOCK;
	if (s == "pnlwznmconheadbar") return PNLWZNMCONHEADBAR;
	if (s == "pnlwznmconlist") return PNLWZNMCONLIST;
	if (s == "pnlwznmconrec") return PNLWZNMCONREC;
	if (s == "pnlwznmconsup1ncontrol") return PNLWZNMCONSUP1NCONTROL;
	if (s == "pnlwznmctp1ntag") return PNLWZNMCTP1NTAG;
	if (s == "pnlwznmctpapar") return PNLWZNMCTPAPAR;
	if (s == "pnlwznmctpdetail") return PNLWZNMCTPDETAIL;
	if (s == "pnlwznmctpheadbar") return PNLWZNMCTPHEADBAR;
	if (s == "pnlwznmctpkkey") return PNLWZNMCTPKKEY;
	if (s == "pnlwznmctpkparkey") return PNLWZNMCTPKPARKEY;
	if (s == "pnlwznmctplist") return PNLWZNMCTPLIST;
	if (s == "pnlwznmctprec") return PNLWZNMCTPREC;
	if (s == "pnlwznmctptpl1ncapability") return PNLWZNMCTPTPL1NCAPABILITY;
	if (s == "pnlwznmdlgdetail") return PNLWZNMDLGDETAIL;
	if (s == "pnlwznmdlgheadbar") return PNLWZNMDLGHEADBAR;
	if (s == "pnlwznmdlghk1ncontrol") return PNLWZNMDLGHK1NCONTROL;
	if (s == "pnlwznmdlglist") return PNLWZNMDLGLIST;
	if (s == "pnlwznmdlgmnquery") return PNLWZNMDLGMNQUERY;
	if (s == "pnlwznmdlgrec") return PNLWZNMDLGREC;
	if (s == "pnlwznmdlgref1ncontrol") return PNLWZNMDLGREF1NCONTROL;
	if (s == "pnlwznmerrdetail") return PNLWZNMERRDETAIL;
	if (s == "pnlwznmerrheadbar") return PNLWZNMERRHEADBAR;
	if (s == "pnlwznmerrlist") return PNLWZNMERRLIST;
	if (s == "pnlwznmerrrec") return PNLWZNMERRREC;
	if (s == "pnlwznmfildetail") return PNLWZNMFILDETAIL;
	if (s == "pnlwznmfilheadbar") return PNLWZNMFILHEADBAR;
	if (s == "pnlwznmfillist") return PNLWZNMFILLIST;
	if (s == "pnlwznmfilrec") return PNLWZNMFILREC;
	if (s == "pnlwznmieldetail") return PNLWZNMIELDETAIL;
	if (s == "pnlwznmielheadbar") return PNLWZNMIELHEADBAR;
	if (s == "pnlwznmiellist") return PNLWZNMIELLIST;
	if (s == "pnlwznmielrec") return PNLWZNMIELREC;
	if (s == "pnlwznmiex1nimpexp") return PNLWZNMIEX1NIMPEXP;
	if (s == "pnlwznmiexdetail") return PNLWZNMIEXDETAIL;
	if (s == "pnlwznmiexheadbar") return PNLWZNMIEXHEADBAR;
	if (s == "pnlwznmiexhk1nvector") return PNLWZNMIEXHK1NVECTOR;
	if (s == "pnlwznmiexlist") return PNLWZNMIEXLIST;
	if (s == "pnlwznmiexrec") return PNLWZNMIEXREC;
	if (s == "pnlwznmiexref1ndialog") return PNLWZNMIEXREF1NDIALOG;
	if (s == "pnlwznmimedetail") return PNLWZNMIMEDETAIL;
	if (s == "pnlwznmimeheadbar") return PNLWZNMIMEHEADBAR;
	if (s == "pnlwznmimehk1nvector") return PNLWZNMIMEHK1NVECTOR;
	if (s == "pnlwznmimeime1nimpexpcol") return PNLWZNMIMEIME1NIMPEXPCOL;
	if (s == "pnlwznmimelist") return PNLWZNMIMELIST;
	if (s == "pnlwznmimerec") return PNLWZNMIMEREC;
	if (s == "pnlwznmimesup1nimpexp") return PNLWZNMIMESUP1NIMPEXP;
	if (s == "pnlwznmjob1nmethod") return PNLWZNMJOB1NMETHOD;
	if (s == "pnlwznmjob1nrtjob") return PNLWZNMJOB1NRTJOB;
	if (s == "pnlwznmjob1nsensitivity") return PNLWZNMJOB1NSENSITIVITY;
	if (s == "pnlwznmjobacmd") return PNLWZNMJOBACMD;
	if (s == "pnlwznmjobavar") return PNLWZNMJOBAVAR;
	if (s == "pnlwznmjobdetail") return PNLWZNMJOBDETAIL;
	if (s == "pnlwznmjobheadbar") return PNLWZNMJOBHEADBAR;
	if (s == "pnlwznmjobhk1nvector") return PNLWZNMJOBHK1NVECTOR;
	if (s == "pnlwznmjobjob1nstage") return PNLWZNMJOBJOB1NSTAGE;
	if (s == "pnlwznmjoblist") return PNLWZNMJOBLIST;
	if (s == "pnlwznmjobmnop") return PNLWZNMJOBMNOP;
	if (s == "pnlwznmjobmnoppack") return PNLWZNMJOBMNOPPACK;
	if (s == "pnlwznmjobrec") return PNLWZNMJOBREC;
	if (s == "pnlwznmjobref1nblock") return PNLWZNMJOBREF1NBLOCK;
	if (s == "pnlwznmjobsubmnjob") return PNLWZNMJOBSUBMNJOB;
	if (s == "pnlwznmjobsupmnjob") return PNLWZNMJOBSUPMNJOB;
	if (s == "pnlwznmlibamakefile") return PNLWZNMLIBAMAKEFILE;
	if (s == "pnlwznmlibapkglist") return PNLWZNMLIBAPKGLIST;
	if (s == "pnlwznmlibdetail") return PNLWZNMLIBDETAIL;
	if (s == "pnlwznmlibheadbar") return PNLWZNMLIBHEADBAR;
	if (s == "pnlwznmliblist") return PNLWZNMLIBLIST;
	if (s == "pnlwznmlibmncomponent") return PNLWZNMLIBMNCOMPONENT;
	if (s == "pnlwznmlibmnoppack") return PNLWZNMLIBMNOPPACK;
	if (s == "pnlwznmlibrec") return PNLWZNMLIBREC;
	if (s == "pnlwznmlibref1nfile") return PNLWZNMLIBREF1NFILE;
	if (s == "pnlwznmlocdetail") return PNLWZNMLOCDETAIL;
	if (s == "pnlwznmlocheadbar") return PNLWZNMLOCHEADBAR;
	if (s == "pnlwznmloclist") return PNLWZNMLOCLIST;
	if (s == "pnlwznmlocmnversion") return PNLWZNMLOCMNVERSION;
	if (s == "pnlwznmlocrec") return PNLWZNMLOCREC;
	if (s == "pnlwznmmch1nrelease") return PNLWZNMMCH1NRELEASE;
	if (s == "pnlwznmmchapar") return PNLWZNMMCHAPAR;
	if (s == "pnlwznmmchdetail") return PNLWZNMMCHDETAIL;
	if (s == "pnlwznmmchheadbar") return PNLWZNMMCHHEADBAR;
	if (s == "pnlwznmmchlist") return PNLWZNMMCHLIST;
	if (s == "pnlwznmmchrec") return PNLWZNMMCHREC;
	if (s == "pnlwznmmdldetail") return PNLWZNMMDLDETAIL;
	if (s == "pnlwznmmdlheadbar") return PNLWZNMMDLHEADBAR;
	if (s == "pnlwznmmdllist") return PNLWZNMMDLLIST;
	if (s == "pnlwznmmdlmdl1ncard") return PNLWZNMMDLMDL1NCARD;
	if (s == "pnlwznmmdlrec") return PNLWZNMMDLREC;
	if (s == "pnlwznmmdlref1npanel") return PNLWZNMMDLREF1NPANEL;
	if (s == "pnlwznmmtdainvpar") return PNLWZNMMTDAINVPAR;
	if (s == "pnlwznmmtdaretpar") return PNLWZNMMTDARETPAR;
	if (s == "pnlwznmmtddetail") return PNLWZNMMTDDETAIL;
	if (s == "pnlwznmmtdheadbar") return PNLWZNMMTDHEADBAR;
	if (s == "pnlwznmmtdlist") return PNLWZNMMTDLIST;
	if (s == "pnlwznmmtdrec") return PNLWZNMMTDREC;
	if (s == "pnlwznmmty1nmachine") return PNLWZNMMTY1NMACHINE;
	if (s == "pnlwznmmtyamakefile") return PNLWZNMMTYAMAKEFILE;
	if (s == "pnlwznmmtydetail") return PNLWZNMMTYDETAIL;
	if (s == "pnlwznmmtyheadbar") return PNLWZNMMTYHEADBAR;
	if (s == "pnlwznmmtylist") return PNLWZNMMTYLIST;
	if (s == "pnlwznmmtyrec") return PNLWZNMMTYREC;
	if (s == "pnlwznmnavadmin") return PNLWZNMNAVADMIN;
	if (s == "pnlwznmnavappdev") return PNLWZNMNAVAPPDEV;
	if (s == "pnlwznmnavauxfct") return PNLWZNMNAVAUXFCT;
	if (s == "pnlwznmnavcomp") return PNLWZNMNAVCOMP;
	if (s == "pnlwznmnavdbstr") return PNLWZNMNAVDBSTR;
	if (s == "pnlwznmnavdeploy") return PNLWZNMNAVDEPLOY;
	if (s == "pnlwznmnavglobal") return PNLWZNMNAVGLOBAL;
	if (s == "pnlwznmnavheadbar") return PNLWZNMNAVHEADBAR;
	if (s == "pnlwznmnavjob") return PNLWZNMNAVJOB;
	if (s == "pnlwznmnavpre") return PNLWZNMNAVPRE;
	if (s == "pnlwznmnavproject") return PNLWZNMNAVPROJECT;
	if (s == "pnlwznmnavuix") return PNLWZNMNAVUIX;
	if (s == "pnlwznmopk1nop") return PNLWZNMOPK1NOP;
	if (s == "pnlwznmopkainvarg") return PNLWZNMOPKAINVARG;
	if (s == "pnlwznmopkaretval") return PNLWZNMOPKARETVAL;
	if (s == "pnlwznmopkdetail") return PNLWZNMOPKDETAIL;
	if (s == "pnlwznmopkheadbar") return PNLWZNMOPKHEADBAR;
	if (s == "pnlwznmopklist") return PNLWZNMOPKLIST;
	if (s == "pnlwznmopkmncomponent") return PNLWZNMOPKMNCOMPONENT;
	if (s == "pnlwznmopkmnjob") return PNLWZNMOPKMNJOB;
	if (s == "pnlwznmopkmnlibrary") return PNLWZNMOPKMNLIBRARY;
	if (s == "pnlwznmopkrec") return PNLWZNMOPKREC;
	if (s == "pnlwznmopkref1nblock") return PNLWZNMOPKREF1NBLOCK;
	if (s == "pnlwznmopksqkmnstub") return PNLWZNMOPKSQKMNSTUB;
	if (s == "pnlwznmopxainvarg") return PNLWZNMOPXAINVARG;
	if (s == "pnlwznmopxaretval") return PNLWZNMOPXARETVAL;
	if (s == "pnlwznmopxdetail") return PNLWZNMOPXDETAIL;
	if (s == "pnlwznmopxheadbar") return PNLWZNMOPXHEADBAR;
	if (s == "pnlwznmopxlist") return PNLWZNMOPXLIST;
	if (s == "pnlwznmopxmnjob") return PNLWZNMOPXMNJOB;
	if (s == "pnlwznmopxrec") return PNLWZNMOPXREC;
	if (s == "pnlwznmopxref1nblock") return PNLWZNMOPXREF1NBLOCK;
	if (s == "pnlwznmopxsqkmnstub") return PNLWZNMOPXSQKMNSTUB;
	if (s == "pnlwznmpnldetail") return PNLWZNMPNLDETAIL;
	if (s == "pnlwznmpnlheadbar") return PNLWZNMPNLHEADBAR;
	if (s == "pnlwznmpnlhk1ncontrol") return PNLWZNMPNLHK1NCONTROL;
	if (s == "pnlwznmpnllist") return PNLWZNMPNLLIST;
	if (s == "pnlwznmpnlmnquery") return PNLWZNMPNLMNQUERY;
	if (s == "pnlwznmpnlrec") return PNLWZNMPNLREC;
	if (s == "pnlwznmprj1nversion") return PNLWZNMPRJ1NVERSION;
	if (s == "pnlwznmprjdetail") return PNLWZNMPRJDETAIL;
	if (s == "pnlwznmprjheadbar") return PNLWZNMPRJHEADBAR;
	if (s == "pnlwznmprjlist") return PNLWZNMPRJLIST;
	if (s == "pnlwznmprjmnperson") return PNLWZNMPRJMNPERSON;
	if (s == "pnlwznmprjrec") return PNLWZNMPRJREC;
	if (s == "pnlwznmprsadetail") return PNLWZNMPRSADETAIL;
	if (s == "pnlwznmprsdetail") return PNLWZNMPRSDETAIL;
	if (s == "pnlwznmprsheadbar") return PNLWZNMPRSHEADBAR;
	if (s == "pnlwznmprslist") return PNLWZNMPRSLIST;
	if (s == "pnlwznmprsmnproject") return PNLWZNMPRSMNPROJECT;
	if (s == "pnlwznmprsrec") return PNLWZNMPRSREC;
	if (s == "pnlwznmpst1nquerymod") return PNLWZNMPST1NQUERYMOD;
	if (s == "pnlwznmpstdetail") return PNLWZNMPSTDETAIL;
	if (s == "pnlwznmpstheadbar") return PNLWZNMPSTHEADBAR;
	if (s == "pnlwznmpstlist") return PNLWZNMPSTLIST;
	if (s == "pnlwznmpstrec") return PNLWZNMPSTREC;
	if (s == "pnlwznmqcodetail") return PNLWZNMQCODETAIL;
	if (s == "pnlwznmqcoheadbar") return PNLWZNMQCOHEADBAR;
	if (s == "pnlwznmqcolist") return PNLWZNMQCOLIST;
	if (s == "pnlwznmqcorec") return PNLWZNMQCOREC;
	if (s == "pnlwznmqcoref1ncontrol") return PNLWZNMQCOREF1NCONTROL;
	if (s == "pnlwznmqmddetail") return PNLWZNMQMDDETAIL;
	if (s == "pnlwznmqmdheadbar") return PNLWZNMQMDHEADBAR;
	if (s == "pnlwznmqmdlist") return PNLWZNMQMDLIST;
	if (s == "pnlwznmqmdrec") return PNLWZNMQMDREC;
	if (s == "pnlwznmqry1nquerymod") return PNLWZNMQRY1NQUERYMOD;
	if (s == "pnlwznmqryaclause") return PNLWZNMQRYACLAUSE;
	if (s == "pnlwznmqryaorder") return PNLWZNMQRYAORDER;
	if (s == "pnlwznmqrydetail") return PNLWZNMQRYDETAIL;
	if (s == "pnlwznmqryheadbar") return PNLWZNMQRYHEADBAR;
	if (s == "pnlwznmqrylist") return PNLWZNMQRYLIST;
	if (s == "pnlwznmqrymndialog") return PNLWZNMQRYMNDIALOG;
	if (s == "pnlwznmqrymnpanel") return PNLWZNMQRYMNPANEL;
	if (s == "pnlwznmqrymntable") return PNLWZNMQRYMNTABLE;
	if (s == "pnlwznmqryqry1nquerycol") return PNLWZNMQRYQRY1NQUERYCOL;
	if (s == "pnlwznmqryrec") return PNLWZNMQRYREC;
	if (s == "pnlwznmqrysup1nquery") return PNLWZNMQRYSUP1NQUERY;
	if (s == "pnlwznmrel1ntablecol") return PNLWZNMREL1NTABLECOL;
	if (s == "pnlwznmrelatitle") return PNLWZNMRELATITLE;
	if (s == "pnlwznmreldetail") return PNLWZNMRELDETAIL;
	if (s == "pnlwznmrelheadbar") return PNLWZNMRELHEADBAR;
	if (s == "pnlwznmrellist") return PNLWZNMRELLIST;
	if (s == "pnlwznmrelrec") return PNLWZNMRELREC;
	if (s == "pnlwznmrelref1ncontrol") return PNLWZNMRELREF1NCONTROL;
	if (s == "pnlwznmrelref1ndialog") return PNLWZNMRELREF1NDIALOG;
	if (s == "pnlwznmrelref1npanel") return PNLWZNMRELREF1NPANEL;
	if (s == "pnlwznmrelsup1nrelation") return PNLWZNMRELSUP1NRELATION;
	if (s == "pnlwznmrlsdetail") return PNLWZNMRLSDETAIL;
	if (s == "pnlwznmrlsheadbar") return PNLWZNMRLSHEADBAR;
	if (s == "pnlwznmrlslist") return PNLWZNMRLSLIST;
	if (s == "pnlwznmrlsrec") return PNLWZNMRLSREC;
	if (s == "pnlwznmrtj1nrtblock") return PNLWZNMRTJ1NRTBLOCK;
	if (s == "pnlwznmrtj1nrtdpch") return PNLWZNMRTJ1NRTDPCH;
	if (s == "pnlwznmrtjdetail") return PNLWZNMRTJDETAIL;
	if (s == "pnlwznmrtjheadbar") return PNLWZNMRTJHEADBAR;
	if (s == "pnlwznmrtjlist") return PNLWZNMRTJLIST;
	if (s == "pnlwznmrtjrec") return PNLWZNMRTJREC;
	if (s == "pnlwznmrtjsup1nrtjob") return PNLWZNMRTJSUP1NRTJOB;
	if (s == "pnlwznmsbs1nstub") return PNLWZNMSBS1NSTUB;
	if (s == "pnlwznmsbs1ntablecol") return PNLWZNMSBS1NTABLECOL;
	if (s == "pnlwznmsbsasbmnsubset") return PNLWZNMSBSASBMNSUBSET;
	if (s == "pnlwznmsbsatitle") return PNLWZNMSBSATITLE;
	if (s == "pnlwznmsbsbsbmnsubset") return PNLWZNMSBSBSBMNSUBSET;
	if (s == "pnlwznmsbsdetail") return PNLWZNMSBSDETAIL;
	if (s == "pnlwznmsbsfrs1nrelation") return PNLWZNMSBSFRS1NRELATION;
	if (s == "pnlwznmsbsheadbar") return PNLWZNMSBSHEADBAR;
	if (s == "pnlwznmsbslist") return PNLWZNMSBSLIST;
	if (s == "pnlwznmsbspst1nquerymod") return PNLWZNMSBSPST1NQUERYMOD;
	if (s == "pnlwznmsbsrec") return PNLWZNMSBSREC;
	if (s == "pnlwznmsbstos1nrelation") return PNLWZNMSBSTOS1NRELATION;
	if (s == "pnlwznmseqdetail") return PNLWZNMSEQDETAIL;
	if (s == "pnlwznmseqheadbar") return PNLWZNMSEQHEADBAR;
	if (s == "pnlwznmseqlist") return PNLWZNMSEQLIST;
	if (s == "pnlwznmseqrec") return PNLWZNMSEQREC;
	if (s == "pnlwznmseqseq1nstate") return PNLWZNMSEQSEQ1NSTATE;
	if (s == "pnlwznmsge1nsensitivity") return PNLWZNMSGE1NSENSITIVITY;
	if (s == "pnlwznmsgedetail") return PNLWZNMSGEDETAIL;
	if (s == "pnlwznmsgeheadbar") return PNLWZNMSGEHEADBAR;
	if (s == "pnlwznmsgelist") return PNLWZNMSGELIST;
	if (s == "pnlwznmsgerec") return PNLWZNMSGEREC;
	if (s == "pnlwznmsgesqkmnstub") return PNLWZNMSGESQKMNSTUB;
	if (s == "pnlwznmstbdetail") return PNLWZNMSTBDETAIL;
	if (s == "pnlwznmstbheadbar") return PNLWZNMSTBHEADBAR;
	if (s == "pnlwznmstblist") return PNLWZNMSTBLIST;
	if (s == "pnlwznmstbmncall") return PNLWZNMSTBMNCALL;
	if (s == "pnlwznmstbmnsquawk") return PNLWZNMSTBMNSQUAWK;
	if (s == "pnlwznmstbrec") return PNLWZNMSTBREC;
	if (s == "pnlwznmstbsubmnstub") return PNLWZNMSTBSUBMNSTUB;
	if (s == "pnlwznmstbsupmnstub") return PNLWZNMSTBSUPMNSTUB;
	if (s == "pnlwznmsteastep") return PNLWZNMSTEASTEP;
	if (s == "pnlwznmstedetail") return PNLWZNMSTEDETAIL;
	if (s == "pnlwznmsteheadbar") return PNLWZNMSTEHEADBAR;
	if (s == "pnlwznmstelist") return PNLWZNMSTELIST;
	if (s == "pnlwznmsterec") return PNLWZNMSTEREC;
	if (s == "pnlwznmtagdetail") return PNLWZNMTAGDETAIL;
	if (s == "pnlwznmtagheadbar") return PNLWZNMTAGHEADBAR;
	if (s == "pnlwznmtaglist") return PNLWZNMTAGLIST;
	if (s == "pnlwznmtagrec") return PNLWZNMTAGREC;
	if (s == "pnlwznmtbl1ncheck") return PNLWZNMTBL1NCHECK;
	if (s == "pnlwznmtbl1nimpexp") return PNLWZNMTBL1NIMPEXP;
	if (s == "pnlwznmtbl1nstub") return PNLWZNMTBL1NSTUB;
	if (s == "pnlwznmtbl1nsubset") return PNLWZNMTBL1NSUBSET;
	if (s == "pnlwznmtblaloadfct") return PNLWZNMTBLALOADFCT;
	if (s == "pnlwznmtblatitle") return PNLWZNMTBLATITLE;
	if (s == "pnlwznmtbldetail") return PNLWZNMTBLDETAIL;
	if (s == "pnlwznmtblfct1ntablecol") return PNLWZNMTBLFCT1NTABLECOL;
	if (s == "pnlwznmtblfr1nrelation") return PNLWZNMTBLFR1NRELATION;
	if (s == "pnlwznmtblheadbar") return PNLWZNMTBLHEADBAR;
	if (s == "pnlwznmtblhk1nvector") return PNLWZNMTBLHK1NVECTOR;
	if (s == "pnlwznmtbllist") return PNLWZNMTBLLIST;
	if (s == "pnlwznmtblmnquery") return PNLWZNMTBLMNQUERY;
	if (s == "pnlwznmtblmnvector") return PNLWZNMTBLMNVECTOR;
	if (s == "pnlwznmtblpst1nquerymod") return PNLWZNMTBLPST1NQUERYMOD;
	if (s == "pnlwznmtblrec") return PNLWZNMTBLREC;
	if (s == "pnlwznmtblref1ncall") return PNLWZNMTBLREF1NCALL;
	if (s == "pnlwznmtblref1ndialog") return PNLWZNMTBLREF1NDIALOG;
	if (s == "pnlwznmtblref1npanel") return PNLWZNMTBLREF1NPANEL;
	if (s == "pnlwznmtblref1nquerymod") return PNLWZNMTBLREF1NQUERYMOD;
	if (s == "pnlwznmtblref1nrtblock") return PNLWZNMTBLREF1NRTBLOCK;
	if (s == "pnlwznmtblsrc1nfeed") return PNLWZNMTBLSRC1NFEED;
	if (s == "pnlwznmtbltbl1ntablecol") return PNLWZNMTBLTBL1NTABLECOL;
	if (s == "pnlwznmtblto1nrelation") return PNLWZNMTBLTO1NRELATION;
	if (s == "pnlwznmtco1ncheck") return PNLWZNMTCO1NCHECK;
	if (s == "pnlwznmtco1nimpexpcol") return PNLWZNMTCO1NIMPEXPCOL;
	if (s == "pnlwznmtco1nquerycol") return PNLWZNMTCO1NQUERYCOL;
	if (s == "pnlwznmtcoatitle") return PNLWZNMTCOATITLE;
	if (s == "pnlwznmtcodetail") return PNLWZNMTCODETAIL;
	if (s == "pnlwznmtcoheadbar") return PNLWZNMTCOHEADBAR;
	if (s == "pnlwznmtcolist") return PNLWZNMTCOLIST;
	if (s == "pnlwznmtcorec") return PNLWZNMTCOREC;
	if (s == "pnlwznmtcoref1ncontrol") return PNLWZNMTCOREF1NCONTROL;
	if (s == "pnlwznmtcoref1nquerymod") return PNLWZNMTCOREF1NQUERYMOD;
	if (s == "pnlwznmusgaaccess") return PNLWZNMUSGAACCESS;
	if (s == "pnlwznmusgdetail") return PNLWZNMUSGDETAIL;
	if (s == "pnlwznmusgheadbar") return PNLWZNMUSGHEADBAR;
	if (s == "pnlwznmusglist") return PNLWZNMUSGLIST;
	if (s == "pnlwznmusgmnuser") return PNLWZNMUSGMNUSER;
	if (s == "pnlwznmusgrec") return PNLWZNMUSGREC;
	if (s == "pnlwznmusr1nsession") return PNLWZNMUSR1NSESSION;
	if (s == "pnlwznmusraaccess") return PNLWZNMUSRAACCESS;
	if (s == "pnlwznmusrdetail") return PNLWZNMUSRDETAIL;
	if (s == "pnlwznmusrheadbar") return PNLWZNMUSRHEADBAR;
	if (s == "pnlwznmusrlist") return PNLWZNMUSRLIST;
	if (s == "pnlwznmusrmnusergroup") return PNLWZNMUSRMNUSERGROUP;
	if (s == "pnlwznmusrrec") return PNLWZNMUSRREC;
	if (s == "pnlwznmutlheadbar") return PNLWZNMUTLHEADBAR;
	if (s == "pnlwznmvecatitle") return PNLWZNMVECATITLE;
	if (s == "pnlwznmvecdetail") return PNLWZNMVECDETAIL;
	if (s == "pnlwznmvecfct1ntablecol") return PNLWZNMVECFCT1NTABLECOL;
	if (s == "pnlwznmvecheadbar") return PNLWZNMVECHEADBAR;
	if (s == "pnlwznmveclist") return PNLWZNMVECLIST;
	if (s == "pnlwznmvecmntable") return PNLWZNMVECMNTABLE;
	if (s == "pnlwznmvecpst1nquerymod") return PNLWZNMVECPST1NQUERYMOD;
	if (s == "pnlwznmvecrec") return PNLWZNMVECREC;
	if (s == "pnlwznmvecref1npanel") return PNLWZNMVECREF1NPANEL;
	if (s == "pnlwznmvecsrc1nfeed") return PNLWZNMVECSRC1NFEED;
	if (s == "pnlwznmvecvec1nvectoritem") return PNLWZNMVECVEC1NVECTORITEM;
	if (s == "pnlwznmver1nblock") return PNLWZNMVER1NBLOCK;
	if (s == "pnlwznmver1ncall") return PNLWZNMVER1NCALL;
	if (s == "pnlwznmver1ncapability") return PNLWZNMVER1NCAPABILITY;
	if (s == "pnlwznmver1ncomponent") return PNLWZNMVER1NCOMPONENT;
	if (s == "pnlwznmver1nimpexpcplx") return PNLWZNMVER1NIMPEXPCPLX;
	if (s == "pnlwznmver1njob") return PNLWZNMVER1NJOB;
	if (s == "pnlwznmver1noppack") return PNLWZNMVER1NOPPACK;
	if (s == "pnlwznmver1npreset") return PNLWZNMVER1NPRESET;
	if (s == "pnlwznmver1nquery") return PNLWZNMVER1NQUERY;
	if (s == "pnlwznmver1nrelation") return PNLWZNMVER1NRELATION;
	if (s == "pnlwznmver1ntable") return PNLWZNMVER1NTABLE;
	if (s == "pnlwznmver1nvector") return PNLWZNMVER1NVECTOR;
	if (s == "pnlwznmverbvr1nversion") return PNLWZNMVERBVR1NVERSION;
	if (s == "pnlwznmverdetail") return PNLWZNMVERDETAIL;
	if (s == "pnlwznmverheadbar") return PNLWZNMVERHEADBAR;
	if (s == "pnlwznmverlist") return PNLWZNMVERLIST;
	if (s == "pnlwznmvermnlocale") return PNLWZNMVERMNLOCALE;
	if (s == "pnlwznmverrec") return PNLWZNMVERREC;
	if (s == "pnlwznmverref1nfile") return PNLWZNMVERREF1NFILE;
	if (s == "pnlwznmverver1napp") return PNLWZNMVERVER1NAPP;
	if (s == "pnlwznmverver1nerror") return PNLWZNMVERVER1NERROR;
	if (s == "pnlwznmverver1nmodule") return PNLWZNMVERVER1NMODULE;
	if (s == "pnlwznmvitdetail") return PNLWZNMVITDETAIL;
	if (s == "pnlwznmvitheadbar") return PNLWZNMVITHEADBAR;
	if (s == "pnlwznmvitlist") return PNLWZNMVITLIST;
	if (s == "pnlwznmvitrec") return PNLWZNMVITREC;
	if (s == "qrywznmapp1nrtjob") return QRYWZNMAPP1NRTJOB;
	if (s == "qrywznmappapp1nsequence") return QRYWZNMAPPAPP1NSEQUENCE;
	if (s == "qrywznmapplist") return QRYWZNMAPPLIST;
	if (s == "qrywznmappref1nfile") return QRYWZNMAPPREF1NFILE;
	if (s == "qrywznmblk1nrtdpch") return QRYWZNMBLK1NRTDPCH;
	if (s == "qrywznmblkaitem") return QRYWZNMBLKAITEM;
	if (s == "qrywznmblklist") return QRYWZNMBLKLIST;
	if (s == "qrywznmblkref1nrtblock") return QRYWZNMBLKREF1NRTBLOCK;
	if (s == "qrywznmcal1nsensitivity") return QRYWZNMCAL1NSENSITIVITY;
	if (s == "qrywznmcallist") return QRYWZNMCALLIST;
	if (s == "qrywznmcalmnstub") return QRYWZNMCALMNSTUB;
	if (s == "qrywznmcapapar") return QRYWZNMCAPAPAR;
	if (s == "qrywznmcaplist") return QRYWZNMCAPLIST;
	if (s == "qrywznmcar1ndialog") return QRYWZNMCAR1NDIALOG;
	if (s == "qrywznmcarcar1npanel") return QRYWZNMCARCAR1NPANEL;
	if (s == "qrywznmcarhk1ncontrol") return QRYWZNMCARHK1NCONTROL;
	if (s == "qrywznmcarlist") return QRYWZNMCARLIST;
	if (s == "qrywznmchklist") return QRYWZNMCHKLIST;
	if (s == "qrywznmchkref1ncall") return QRYWZNMCHKREF1NCALL;
	if (s == "qrywznmcmp1nrelease") return QRYWZNMCMP1NRELEASE;
	if (s == "qrywznmcmplist") return QRYWZNMCMPLIST;
	if (s == "qrywznmcmpmnlibrary") return QRYWZNMCMPMNLIBRARY;
	if (s == "qrywznmcmpmnoppack") return QRYWZNMCMPMNOPPACK;
	if (s == "qrywznmconapar") return QRYWZNMCONAPAR;
	if (s == "qrywznmconfedref1nrtblock") return QRYWZNMCONFEDREF1NRTBLOCK;
	if (s == "qrywznmconlist") return QRYWZNMCONLIST;
	if (s == "qrywznmconsup1ncontrol") return QRYWZNMCONSUP1NCONTROL;
	if (s == "qrywznmctp1ntag") return QRYWZNMCTP1NTAG;
	if (s == "qrywznmctpapar") return QRYWZNMCTPAPAR;
	if (s == "qrywznmctpkkey") return QRYWZNMCTPKKEY;
	if (s == "qrywznmctpkparkey") return QRYWZNMCTPKPARKEY;
	if (s == "qrywznmctplist") return QRYWZNMCTPLIST;
	if (s == "qrywznmctptpl1ncapability") return QRYWZNMCTPTPL1NCAPABILITY;
	if (s == "qrywznmdlghk1ncontrol") return QRYWZNMDLGHK1NCONTROL;
	if (s == "qrywznmdlglist") return QRYWZNMDLGLIST;
	if (s == "qrywznmdlgmnquery") return QRYWZNMDLGMNQUERY;
	if (s == "qrywznmdlgref1ncontrol") return QRYWZNMDLGREF1NCONTROL;
	if (s == "qrywznmerrlist") return QRYWZNMERRLIST;
	if (s == "qrywznmfillist") return QRYWZNMFILLIST;
	if (s == "qrywznmiellist") return QRYWZNMIELLIST;
	if (s == "qrywznmiex1nimpexp") return QRYWZNMIEX1NIMPEXP;
	if (s == "qrywznmiexhk1nvector") return QRYWZNMIEXHK1NVECTOR;
	if (s == "qrywznmiexlist") return QRYWZNMIEXLIST;
	if (s == "qrywznmiexref1ndialog") return QRYWZNMIEXREF1NDIALOG;
	if (s == "qrywznmimehk1nvector") return QRYWZNMIMEHK1NVECTOR;
	if (s == "qrywznmimeime1nimpexpcol") return QRYWZNMIMEIME1NIMPEXPCOL;
	if (s == "qrywznmimelist") return QRYWZNMIMELIST;
	if (s == "qrywznmimesup1nimpexp") return QRYWZNMIMESUP1NIMPEXP;
	if (s == "qrywznmjob1nmethod") return QRYWZNMJOB1NMETHOD;
	if (s == "qrywznmjob1nrtjob") return QRYWZNMJOB1NRTJOB;
	if (s == "qrywznmjob1nsensitivity") return QRYWZNMJOB1NSENSITIVITY;
	if (s == "qrywznmjobacmd") return QRYWZNMJOBACMD;
	if (s == "qrywznmjobavar") return QRYWZNMJOBAVAR;
	if (s == "qrywznmjobhk1nvector") return QRYWZNMJOBHK1NVECTOR;
	if (s == "qrywznmjobjob1nstage") return QRYWZNMJOBJOB1NSTAGE;
	if (s == "qrywznmjoblist") return QRYWZNMJOBLIST;
	if (s == "qrywznmjobmnop") return QRYWZNMJOBMNOP;
	if (s == "qrywznmjobmnoppack") return QRYWZNMJOBMNOPPACK;
	if (s == "qrywznmjobref1nblock") return QRYWZNMJOBREF1NBLOCK;
	if (s == "qrywznmjobsubmnjob") return QRYWZNMJOBSUBMNJOB;
	if (s == "qrywznmjobsupmnjob") return QRYWZNMJOBSUPMNJOB;
	if (s == "qrywznmlibamakefile") return QRYWZNMLIBAMAKEFILE;
	if (s == "qrywznmlibapkglist") return QRYWZNMLIBAPKGLIST;
	if (s == "qrywznmliblist") return QRYWZNMLIBLIST;
	if (s == "qrywznmlibmncomponent") return QRYWZNMLIBMNCOMPONENT;
	if (s == "qrywznmlibmnoppack") return QRYWZNMLIBMNOPPACK;
	if (s == "qrywznmlibref1nfile") return QRYWZNMLIBREF1NFILE;
	if (s == "qrywznmloclist") return QRYWZNMLOCLIST;
	if (s == "qrywznmlocmnversion") return QRYWZNMLOCMNVERSION;
	if (s == "qrywznmmch1nrelease") return QRYWZNMMCH1NRELEASE;
	if (s == "qrywznmmchapar") return QRYWZNMMCHAPAR;
	if (s == "qrywznmmchlist") return QRYWZNMMCHLIST;
	if (s == "qrywznmmdllist") return QRYWZNMMDLLIST;
	if (s == "qrywznmmdlmdl1ncard") return QRYWZNMMDLMDL1NCARD;
	if (s == "qrywznmmdlref1npanel") return QRYWZNMMDLREF1NPANEL;
	if (s == "qrywznmmtdainvpar") return QRYWZNMMTDAINVPAR;
	if (s == "qrywznmmtdaretpar") return QRYWZNMMTDARETPAR;
	if (s == "qrywznmmtdlist") return QRYWZNMMTDLIST;
	if (s == "qrywznmmty1nmachine") return QRYWZNMMTY1NMACHINE;
	if (s == "qrywznmmtyamakefile") return QRYWZNMMTYAMAKEFILE;
	if (s == "qrywznmmtylist") return QRYWZNMMTYLIST;
	if (s == "qrywznmopk1nop") return QRYWZNMOPK1NOP;
	if (s == "qrywznmopkainvarg") return QRYWZNMOPKAINVARG;
	if (s == "qrywznmopkaretval") return QRYWZNMOPKARETVAL;
	if (s == "qrywznmopklist") return QRYWZNMOPKLIST;
	if (s == "qrywznmopkmncomponent") return QRYWZNMOPKMNCOMPONENT;
	if (s == "qrywznmopkmnjob") return QRYWZNMOPKMNJOB;
	if (s == "qrywznmopkmnlibrary") return QRYWZNMOPKMNLIBRARY;
	if (s == "qrywznmopkref1nblock") return QRYWZNMOPKREF1NBLOCK;
	if (s == "qrywznmopksqkmnstub") return QRYWZNMOPKSQKMNSTUB;
	if (s == "qrywznmopxainvarg") return QRYWZNMOPXAINVARG;
	if (s == "qrywznmopxaretval") return QRYWZNMOPXARETVAL;
	if (s == "qrywznmopxlist") return QRYWZNMOPXLIST;
	if (s == "qrywznmopxmnjob") return QRYWZNMOPXMNJOB;
	if (s == "qrywznmopxref1nblock") return QRYWZNMOPXREF1NBLOCK;
	if (s == "qrywznmopxsqkmnstub") return QRYWZNMOPXSQKMNSTUB;
	if (s == "qrywznmpnlhk1ncontrol") return QRYWZNMPNLHK1NCONTROL;
	if (s == "qrywznmpnllist") return QRYWZNMPNLLIST;
	if (s == "qrywznmpnlmnquery") return QRYWZNMPNLMNQUERY;
	if (s == "qrywznmprj1nversion") return QRYWZNMPRJ1NVERSION;
	if (s == "qrywznmprjlist") return QRYWZNMPRJLIST;
	if (s == "qrywznmprjmnperson") return QRYWZNMPRJMNPERSON;
	if (s == "qrywznmprsadetail") return QRYWZNMPRSADETAIL;
	if (s == "qrywznmprslist") return QRYWZNMPRSLIST;
	if (s == "qrywznmprsmnproject") return QRYWZNMPRSMNPROJECT;
	if (s == "qrywznmpst1nquerymod") return QRYWZNMPST1NQUERYMOD;
	if (s == "qrywznmpstlist") return QRYWZNMPSTLIST;
	if (s == "qrywznmqcolist") return QRYWZNMQCOLIST;
	if (s == "qrywznmqcoref1ncontrol") return QRYWZNMQCOREF1NCONTROL;
	if (s == "qrywznmqmdlist") return QRYWZNMQMDLIST;
	if (s == "qrywznmqry1nquerymod") return QRYWZNMQRY1NQUERYMOD;
	if (s == "qrywznmqryaclause") return QRYWZNMQRYACLAUSE;
	if (s == "qrywznmqryaorder") return QRYWZNMQRYAORDER;
	if (s == "qrywznmqrylist") return QRYWZNMQRYLIST;
	if (s == "qrywznmqrymndialog") return QRYWZNMQRYMNDIALOG;
	if (s == "qrywznmqrymnpanel") return QRYWZNMQRYMNPANEL;
	if (s == "qrywznmqrymntable") return QRYWZNMQRYMNTABLE;
	if (s == "qrywznmqryqry1nquerycol") return QRYWZNMQRYQRY1NQUERYCOL;
	if (s == "qrywznmqrysup1nquery") return QRYWZNMQRYSUP1NQUERY;
	if (s == "qrywznmrel1ntablecol") return QRYWZNMREL1NTABLECOL;
	if (s == "qrywznmrelatitle") return QRYWZNMRELATITLE;
	if (s == "qrywznmrellist") return QRYWZNMRELLIST;
	if (s == "qrywznmrelref1ncontrol") return QRYWZNMRELREF1NCONTROL;
	if (s == "qrywznmrelref1ndialog") return QRYWZNMRELREF1NDIALOG;
	if (s == "qrywznmrelref1npanel") return QRYWZNMRELREF1NPANEL;
	if (s == "qrywznmrelsup1nrelation") return QRYWZNMRELSUP1NRELATION;
	if (s == "qrywznmrlslist") return QRYWZNMRLSLIST;
	if (s == "qrywznmrtj1nrtblock") return QRYWZNMRTJ1NRTBLOCK;
	if (s == "qrywznmrtj1nrtdpch") return QRYWZNMRTJ1NRTDPCH;
	if (s == "qrywznmrtjlist") return QRYWZNMRTJLIST;
	if (s == "qrywznmrtjsup1nrtjob") return QRYWZNMRTJSUP1NRTJOB;
	if (s == "qrywznmsbs1nstub") return QRYWZNMSBS1NSTUB;
	if (s == "qrywznmsbs1ntablecol") return QRYWZNMSBS1NTABLECOL;
	if (s == "qrywznmsbsasbmnsubset") return QRYWZNMSBSASBMNSUBSET;
	if (s == "qrywznmsbsatitle") return QRYWZNMSBSATITLE;
	if (s == "qrywznmsbsbsbmnsubset") return QRYWZNMSBSBSBMNSUBSET;
	if (s == "qrywznmsbsfrs1nrelation") return QRYWZNMSBSFRS1NRELATION;
	if (s == "qrywznmsbslist") return QRYWZNMSBSLIST;
	if (s == "qrywznmsbspst1nquerymod") return QRYWZNMSBSPST1NQUERYMOD;
	if (s == "qrywznmsbstos1nrelation") return QRYWZNMSBSTOS1NRELATION;
	if (s == "qrywznmseqlist") return QRYWZNMSEQLIST;
	if (s == "qrywznmseqseq1nstate") return QRYWZNMSEQSEQ1NSTATE;
	if (s == "qrywznmsge1nsensitivity") return QRYWZNMSGE1NSENSITIVITY;
	if (s == "qrywznmsgelist") return QRYWZNMSGELIST;
	if (s == "qrywznmsgesqkmnstub") return QRYWZNMSGESQKMNSTUB;
	if (s == "qrywznmstblist") return QRYWZNMSTBLIST;
	if (s == "qrywznmstbmncall") return QRYWZNMSTBMNCALL;
	if (s == "qrywznmstbmnsquawk") return QRYWZNMSTBMNSQUAWK;
	if (s == "qrywznmstbsubmnstub") return QRYWZNMSTBSUBMNSTUB;
	if (s == "qrywznmstbsupmnstub") return QRYWZNMSTBSUPMNSTUB;
	if (s == "qrywznmsteastep") return QRYWZNMSTEASTEP;
	if (s == "qrywznmstelist") return QRYWZNMSTELIST;
	if (s == "qrywznmtaglist") return QRYWZNMTAGLIST;
	if (s == "qrywznmtbl1ncheck") return QRYWZNMTBL1NCHECK;
	if (s == "qrywznmtbl1nimpexp") return QRYWZNMTBL1NIMPEXP;
	if (s == "qrywznmtbl1nstub") return QRYWZNMTBL1NSTUB;
	if (s == "qrywznmtbl1nsubset") return QRYWZNMTBL1NSUBSET;
	if (s == "qrywznmtblaloadfct") return QRYWZNMTBLALOADFCT;
	if (s == "qrywznmtblatitle") return QRYWZNMTBLATITLE;
	if (s == "qrywznmtblfct1ntablecol") return QRYWZNMTBLFCT1NTABLECOL;
	if (s == "qrywznmtblfr1nrelation") return QRYWZNMTBLFR1NRELATION;
	if (s == "qrywznmtblhk1nvector") return QRYWZNMTBLHK1NVECTOR;
	if (s == "qrywznmtbllist") return QRYWZNMTBLLIST;
	if (s == "qrywznmtblmnquery") return QRYWZNMTBLMNQUERY;
	if (s == "qrywznmtblmnvector") return QRYWZNMTBLMNVECTOR;
	if (s == "qrywznmtblpst1nquerymod") return QRYWZNMTBLPST1NQUERYMOD;
	if (s == "qrywznmtblref1ncall") return QRYWZNMTBLREF1NCALL;
	if (s == "qrywznmtblref1ndialog") return QRYWZNMTBLREF1NDIALOG;
	if (s == "qrywznmtblref1npanel") return QRYWZNMTBLREF1NPANEL;
	if (s == "qrywznmtblref1nquerymod") return QRYWZNMTBLREF1NQUERYMOD;
	if (s == "qrywznmtblref1nrtblock") return QRYWZNMTBLREF1NRTBLOCK;
	if (s == "qrywznmtblsrc1nfeed") return QRYWZNMTBLSRC1NFEED;
	if (s == "qrywznmtbltbl1ntablecol") return QRYWZNMTBLTBL1NTABLECOL;
	if (s == "qrywznmtblto1nrelation") return QRYWZNMTBLTO1NRELATION;
	if (s == "qrywznmtco1ncheck") return QRYWZNMTCO1NCHECK;
	if (s == "qrywznmtco1nimpexpcol") return QRYWZNMTCO1NIMPEXPCOL;
	if (s == "qrywznmtco1nquerycol") return QRYWZNMTCO1NQUERYCOL;
	if (s == "qrywznmtcoatitle") return QRYWZNMTCOATITLE;
	if (s == "qrywznmtcolist") return QRYWZNMTCOLIST;
	if (s == "qrywznmtcoref1ncontrol") return QRYWZNMTCOREF1NCONTROL;
	if (s == "qrywznmtcoref1nquerymod") return QRYWZNMTCOREF1NQUERYMOD;
	if (s == "qrywznmusgaaccess") return QRYWZNMUSGAACCESS;
	if (s == "qrywznmusglist") return QRYWZNMUSGLIST;
	if (s == "qrywznmusgmnuser") return QRYWZNMUSGMNUSER;
	if (s == "qrywznmusr1nsession") return QRYWZNMUSR1NSESSION;
	if (s == "qrywznmusraaccess") return QRYWZNMUSRAACCESS;
	if (s == "qrywznmusrlist") return QRYWZNMUSRLIST;
	if (s == "qrywznmusrmnusergroup") return QRYWZNMUSRMNUSERGROUP;
	if (s == "qrywznmvecatitle") return QRYWZNMVECATITLE;
	if (s == "qrywznmvecfct1ntablecol") return QRYWZNMVECFCT1NTABLECOL;
	if (s == "qrywznmveclist") return QRYWZNMVECLIST;
	if (s == "qrywznmvecmntable") return QRYWZNMVECMNTABLE;
	if (s == "qrywznmvecpst1nquerymod") return QRYWZNMVECPST1NQUERYMOD;
	if (s == "qrywznmvecref1npanel") return QRYWZNMVECREF1NPANEL;
	if (s == "qrywznmvecsrc1nfeed") return QRYWZNMVECSRC1NFEED;
	if (s == "qrywznmvecvec1nvectoritem") return QRYWZNMVECVEC1NVECTORITEM;
	if (s == "qrywznmver1nblock") return QRYWZNMVER1NBLOCK;
	if (s == "qrywznmver1ncall") return QRYWZNMVER1NCALL;
	if (s == "qrywznmver1ncapability") return QRYWZNMVER1NCAPABILITY;
	if (s == "qrywznmver1ncomponent") return QRYWZNMVER1NCOMPONENT;
	if (s == "qrywznmver1nimpexpcplx") return QRYWZNMVER1NIMPEXPCPLX;
	if (s == "qrywznmver1njob") return QRYWZNMVER1NJOB;
	if (s == "qrywznmver1noppack") return QRYWZNMVER1NOPPACK;
	if (s == "qrywznmver1npreset") return QRYWZNMVER1NPRESET;
	if (s == "qrywznmver1nquery") return QRYWZNMVER1NQUERY;
	if (s == "qrywznmver1nrelation") return QRYWZNMVER1NRELATION;
	if (s == "qrywznmver1ntable") return QRYWZNMVER1NTABLE;
	if (s == "qrywznmver1nvector") return QRYWZNMVER1NVECTOR;
	if (s == "qrywznmverbvr1nversion") return QRYWZNMVERBVR1NVERSION;
	if (s == "qrywznmverlist") return QRYWZNMVERLIST;
	if (s == "qrywznmvermnlocale") return QRYWZNMVERMNLOCALE;
	if (s == "qrywznmverref1nfile") return QRYWZNMVERREF1NFILE;
	if (s == "qrywznmverver1napp") return QRYWZNMVERVER1NAPP;
	if (s == "qrywznmverver1nerror") return QRYWZNMVERVER1NERROR;
	if (s == "qrywznmverver1nmodule") return QRYWZNMVERVER1NMODULE;
	if (s == "qrywznmvitlist") return QRYWZNMVITLIST;
	if (s == "rootwznm") return ROOTWZNM;
	if (s == "sesswznm") return SESSWZNM;

	return(0);
};

string VecWznmVJob::getSref(
			const uint ix
		) {
	if (ix == CRDWZNMAPP) return("CrdWznmApp");
	if (ix == CRDWZNMBLK) return("CrdWznmBlk");
	if (ix == CRDWZNMCAL) return("CrdWznmCal");
	if (ix == CRDWZNMCAP) return("CrdWznmCap");
	if (ix == CRDWZNMCAR) return("CrdWznmCar");
	if (ix == CRDWZNMCHK) return("CrdWznmChk");
	if (ix == CRDWZNMCMP) return("CrdWznmCmp");
	if (ix == CRDWZNMCON) return("CrdWznmCon");
	if (ix == CRDWZNMCTP) return("CrdWznmCtp");
	if (ix == CRDWZNMDLG) return("CrdWznmDlg");
	if (ix == CRDWZNMERR) return("CrdWznmErr");
	if (ix == CRDWZNMFIL) return("CrdWznmFil");
	if (ix == CRDWZNMIEL) return("CrdWznmIel");
	if (ix == CRDWZNMIEX) return("CrdWznmIex");
	if (ix == CRDWZNMIME) return("CrdWznmIme");
	if (ix == CRDWZNMJOB) return("CrdWznmJob");
	if (ix == CRDWZNMLIB) return("CrdWznmLib");
	if (ix == CRDWZNMLOC) return("CrdWznmLoc");
	if (ix == CRDWZNMMCH) return("CrdWznmMch");
	if (ix == CRDWZNMMDL) return("CrdWznmMdl");
	if (ix == CRDWZNMMTD) return("CrdWznmMtd");
	if (ix == CRDWZNMMTY) return("CrdWznmMty");
	if (ix == CRDWZNMNAV) return("CrdWznmNav");
	if (ix == CRDWZNMOPK) return("CrdWznmOpk");
	if (ix == CRDWZNMOPX) return("CrdWznmOpx");
	if (ix == CRDWZNMPNL) return("CrdWznmPnl");
	if (ix == CRDWZNMPRJ) return("CrdWznmPrj");
	if (ix == CRDWZNMPRS) return("CrdWznmPrs");
	if (ix == CRDWZNMPST) return("CrdWznmPst");
	if (ix == CRDWZNMQCO) return("CrdWznmQco");
	if (ix == CRDWZNMQMD) return("CrdWznmQmd");
	if (ix == CRDWZNMQRY) return("CrdWznmQry");
	if (ix == CRDWZNMREL) return("CrdWznmRel");
	if (ix == CRDWZNMRLS) return("CrdWznmRls");
	if (ix == CRDWZNMRTJ) return("CrdWznmRtj");
	if (ix == CRDWZNMSBS) return("CrdWznmSbs");
	if (ix == CRDWZNMSEQ) return("CrdWznmSeq");
	if (ix == CRDWZNMSGE) return("CrdWznmSge");
	if (ix == CRDWZNMSTB) return("CrdWznmStb");
	if (ix == CRDWZNMSTE) return("CrdWznmSte");
	if (ix == CRDWZNMTAG) return("CrdWznmTag");
	if (ix == CRDWZNMTBL) return("CrdWznmTbl");
	if (ix == CRDWZNMTCO) return("CrdWznmTco");
	if (ix == CRDWZNMUSG) return("CrdWznmUsg");
	if (ix == CRDWZNMUSR) return("CrdWznmUsr");
	if (ix == CRDWZNMUTL) return("CrdWznmUtl");
	if (ix == CRDWZNMVEC) return("CrdWznmVec");
	if (ix == CRDWZNMVER) return("CrdWznmVer");
	if (ix == CRDWZNMVIT) return("CrdWznmVit");
	if (ix == DLGWZNMAPPIMPSTR) return("DlgWznmAppImpstr");
	if (ix == DLGWZNMAPPNEW) return("DlgWznmAppNew");
	if (ix == DLGWZNMAPPWRITE) return("DlgWznmAppWrite");
	if (ix == DLGWZNMFILDOWNLOAD) return("DlgWznmFilDownload");
	if (ix == DLGWZNMFILNEW) return("DlgWznmFilNew");
	if (ix == DLGWZNMNAVLOAINI) return("DlgWznmNavLoaini");
	if (ix == DLGWZNMNAVMNGLIC) return("DlgWznmNavMnglic");
	if (ix == DLGWZNMPRJIMPEX) return("DlgWznmPrjImpex");
	if (ix == DLGWZNMPRJNEW) return("DlgWznmPrjNew");
	if (ix == DLGWZNMRLSFINREPTR) return("DlgWznmRlsFinreptr");
	if (ix == DLGWZNMRLSSTAREPTR) return("DlgWznmRlsStareptr");
	if (ix == DLGWZNMRLSWRITE) return("DlgWznmRlsWrite");
	if (ix == DLGWZNMUSRMNGKEYPAIR) return("DlgWznmUsrMngkeypair");
	if (ix == DLGWZNMUTLEXTRIP) return("DlgWznmUtlExtrip");
	if (ix == DLGWZNMUTLIEXCONV) return("DlgWznmUtlIexconv");
	if (ix == DLGWZNMUTLMRGIP) return("DlgWznmUtlMrgip");
	if (ix == DLGWZNMVERBSCUI) return("DlgWznmVerBscui");
	if (ix == DLGWZNMVERCUSTJOB) return("DlgWznmVerCustjob");
	if (ix == DLGWZNMVERCUSTJTR) return("DlgWznmVerCustjtr");
	if (ix == DLGWZNMVERCUSTUI) return("DlgWznmVerCustui");
	if (ix == DLGWZNMVERDBSTR) return("DlgWznmVerDbstr");
	if (ix == DLGWZNMVERDEPLOY) return("DlgWznmVerDeploy");
	if (ix == DLGWZNMVERFINMOD) return("DlgWznmVerFinmod");
	if (ix == DLGWZNMVERGENJTR) return("DlgWznmVerGenjtr");
	if (ix == DLGWZNMVERGENUI) return("DlgWznmVerGenui");
	if (ix == DLGWZNMVERGLOBAL) return("DlgWznmVerGlobal");
	if (ix == DLGWZNMVERIMPEXP) return("DlgWznmVerImpexp");
	if (ix == DLGWZNMVERNEW) return("DlgWznmVerNew");
	if (ix == DLGWZNMVEROPPACK) return("DlgWznmVerOppack");
	if (ix == DLGWZNMVERWRSTKIT) return("DlgWznmVerWrstkit");
	if (ix == JOBWZNMIEXAPP) return("JobWznmIexApp");
	if (ix == JOBWZNMIEXBUI) return("JobWznmIexBui");
	if (ix == JOBWZNMIEXDBS) return("JobWznmIexDbs");
	if (ix == JOBWZNMIEXDPL) return("JobWznmIexDpl");
	if (ix == JOBWZNMIEXGBL) return("JobWznmIexGbl");
	if (ix == JOBWZNMIEXIEX) return("JobWznmIexIex");
	if (ix == JOBWZNMIEXINI) return("JobWznmIexIni");
	if (ix == JOBWZNMIEXJOB) return("JobWznmIexJob");
	if (ix == JOBWZNMIEXJTR) return("JobWznmIexJtr");
	if (ix == JOBWZNMIEXOPK) return("JobWznmIexOpk");
	if (ix == JOBWZNMIEXPRJ) return("JobWznmIexPrj");
	if (ix == JOBWZNMIEXUIX) return("JobWznmIexUix");
	if (ix == JOBWZNMLICENSE) return("JobWznmLicense");
	if (ix == PNLWZNMAPP1NRTJOB) return("PnlWznmApp1NRtjob");
	if (ix == PNLWZNMAPPAPP1NSEQUENCE) return("PnlWznmAppApp1NSequence");
	if (ix == PNLWZNMAPPDETAIL) return("PnlWznmAppDetail");
	if (ix == PNLWZNMAPPHEADBAR) return("PnlWznmAppHeadbar");
	if (ix == PNLWZNMAPPLIST) return("PnlWznmAppList");
	if (ix == PNLWZNMAPPREC) return("PnlWznmAppRec");
	if (ix == PNLWZNMAPPREF1NFILE) return("PnlWznmAppRef1NFile");
	if (ix == PNLWZNMBLK1NRTDPCH) return("PnlWznmBlk1NRtdpch");
	if (ix == PNLWZNMBLKAITEM) return("PnlWznmBlkAItem");
	if (ix == PNLWZNMBLKDETAIL) return("PnlWznmBlkDetail");
	if (ix == PNLWZNMBLKHEADBAR) return("PnlWznmBlkHeadbar");
	if (ix == PNLWZNMBLKLIST) return("PnlWznmBlkList");
	if (ix == PNLWZNMBLKREC) return("PnlWznmBlkRec");
	if (ix == PNLWZNMBLKREF1NRTBLOCK) return("PnlWznmBlkRef1NRtblock");
	if (ix == PNLWZNMCAL1NSENSITIVITY) return("PnlWznmCal1NSensitivity");
	if (ix == PNLWZNMCALDETAIL) return("PnlWznmCalDetail");
	if (ix == PNLWZNMCALHEADBAR) return("PnlWznmCalHeadbar");
	if (ix == PNLWZNMCALLIST) return("PnlWznmCalList");
	if (ix == PNLWZNMCALMNSTUB) return("PnlWznmCalMNStub");
	if (ix == PNLWZNMCALREC) return("PnlWznmCalRec");
	if (ix == PNLWZNMCAPAPAR) return("PnlWznmCapAPar");
	if (ix == PNLWZNMCAPDETAIL) return("PnlWznmCapDetail");
	if (ix == PNLWZNMCAPHEADBAR) return("PnlWznmCapHeadbar");
	if (ix == PNLWZNMCAPLIST) return("PnlWznmCapList");
	if (ix == PNLWZNMCAPREC) return("PnlWznmCapRec");
	if (ix == PNLWZNMCAR1NDIALOG) return("PnlWznmCar1NDialog");
	if (ix == PNLWZNMCARCAR1NPANEL) return("PnlWznmCarCar1NPanel");
	if (ix == PNLWZNMCARDETAIL) return("PnlWznmCarDetail");
	if (ix == PNLWZNMCARHEADBAR) return("PnlWznmCarHeadbar");
	if (ix == PNLWZNMCARHK1NCONTROL) return("PnlWznmCarHk1NControl");
	if (ix == PNLWZNMCARLIST) return("PnlWznmCarList");
	if (ix == PNLWZNMCARREC) return("PnlWznmCarRec");
	if (ix == PNLWZNMCHKDETAIL) return("PnlWznmChkDetail");
	if (ix == PNLWZNMCHKHEADBAR) return("PnlWznmChkHeadbar");
	if (ix == PNLWZNMCHKLIST) return("PnlWznmChkList");
	if (ix == PNLWZNMCHKREC) return("PnlWznmChkRec");
	if (ix == PNLWZNMCHKREF1NCALL) return("PnlWznmChkRef1NCall");
	if (ix == PNLWZNMCMP1NRELEASE) return("PnlWznmCmp1NRelease");
	if (ix == PNLWZNMCMPDETAIL) return("PnlWznmCmpDetail");
	if (ix == PNLWZNMCMPHEADBAR) return("PnlWznmCmpHeadbar");
	if (ix == PNLWZNMCMPLIST) return("PnlWznmCmpList");
	if (ix == PNLWZNMCMPMNLIBRARY) return("PnlWznmCmpMNLibrary");
	if (ix == PNLWZNMCMPMNOPPACK) return("PnlWznmCmpMNOppack");
	if (ix == PNLWZNMCMPREC) return("PnlWznmCmpRec");
	if (ix == PNLWZNMCONAPAR) return("PnlWznmConAPar");
	if (ix == PNLWZNMCONDETAIL) return("PnlWznmConDetail");
	if (ix == PNLWZNMCONFEDREF1NRTBLOCK) return("PnlWznmConFedRef1NRtblock");
	if (ix == PNLWZNMCONHEADBAR) return("PnlWznmConHeadbar");
	if (ix == PNLWZNMCONLIST) return("PnlWznmConList");
	if (ix == PNLWZNMCONREC) return("PnlWznmConRec");
	if (ix == PNLWZNMCONSUP1NCONTROL) return("PnlWznmConSup1NControl");
	if (ix == PNLWZNMCTP1NTAG) return("PnlWznmCtp1NTag");
	if (ix == PNLWZNMCTPAPAR) return("PnlWznmCtpAPar");
	if (ix == PNLWZNMCTPDETAIL) return("PnlWznmCtpDetail");
	if (ix == PNLWZNMCTPHEADBAR) return("PnlWznmCtpHeadbar");
	if (ix == PNLWZNMCTPKKEY) return("PnlWznmCtpKKey");
	if (ix == PNLWZNMCTPKPARKEY) return("PnlWznmCtpKParKey");
	if (ix == PNLWZNMCTPLIST) return("PnlWznmCtpList");
	if (ix == PNLWZNMCTPREC) return("PnlWznmCtpRec");
	if (ix == PNLWZNMCTPTPL1NCAPABILITY) return("PnlWznmCtpTpl1NCapability");
	if (ix == PNLWZNMDLGDETAIL) return("PnlWznmDlgDetail");
	if (ix == PNLWZNMDLGHEADBAR) return("PnlWznmDlgHeadbar");
	if (ix == PNLWZNMDLGHK1NCONTROL) return("PnlWznmDlgHk1NControl");
	if (ix == PNLWZNMDLGLIST) return("PnlWznmDlgList");
	if (ix == PNLWZNMDLGMNQUERY) return("PnlWznmDlgMNQuery");
	if (ix == PNLWZNMDLGREC) return("PnlWznmDlgRec");
	if (ix == PNLWZNMDLGREF1NCONTROL) return("PnlWznmDlgRef1NControl");
	if (ix == PNLWZNMERRDETAIL) return("PnlWznmErrDetail");
	if (ix == PNLWZNMERRHEADBAR) return("PnlWznmErrHeadbar");
	if (ix == PNLWZNMERRLIST) return("PnlWznmErrList");
	if (ix == PNLWZNMERRREC) return("PnlWznmErrRec");
	if (ix == PNLWZNMFILDETAIL) return("PnlWznmFilDetail");
	if (ix == PNLWZNMFILHEADBAR) return("PnlWznmFilHeadbar");
	if (ix == PNLWZNMFILLIST) return("PnlWznmFilList");
	if (ix == PNLWZNMFILREC) return("PnlWznmFilRec");
	if (ix == PNLWZNMIELDETAIL) return("PnlWznmIelDetail");
	if (ix == PNLWZNMIELHEADBAR) return("PnlWznmIelHeadbar");
	if (ix == PNLWZNMIELLIST) return("PnlWznmIelList");
	if (ix == PNLWZNMIELREC) return("PnlWznmIelRec");
	if (ix == PNLWZNMIEX1NIMPEXP) return("PnlWznmIex1NImpexp");
	if (ix == PNLWZNMIEXDETAIL) return("PnlWznmIexDetail");
	if (ix == PNLWZNMIEXHEADBAR) return("PnlWznmIexHeadbar");
	if (ix == PNLWZNMIEXHK1NVECTOR) return("PnlWznmIexHk1NVector");
	if (ix == PNLWZNMIEXLIST) return("PnlWznmIexList");
	if (ix == PNLWZNMIEXREC) return("PnlWznmIexRec");
	if (ix == PNLWZNMIEXREF1NDIALOG) return("PnlWznmIexRef1NDialog");
	if (ix == PNLWZNMIMEDETAIL) return("PnlWznmImeDetail");
	if (ix == PNLWZNMIMEHEADBAR) return("PnlWznmImeHeadbar");
	if (ix == PNLWZNMIMEHK1NVECTOR) return("PnlWznmImeHk1NVector");
	if (ix == PNLWZNMIMEIME1NIMPEXPCOL) return("PnlWznmImeIme1NImpexpcol");
	if (ix == PNLWZNMIMELIST) return("PnlWznmImeList");
	if (ix == PNLWZNMIMEREC) return("PnlWznmImeRec");
	if (ix == PNLWZNMIMESUP1NIMPEXP) return("PnlWznmImeSup1NImpexp");
	if (ix == PNLWZNMJOB1NMETHOD) return("PnlWznmJob1NMethod");
	if (ix == PNLWZNMJOB1NRTJOB) return("PnlWznmJob1NRtjob");
	if (ix == PNLWZNMJOB1NSENSITIVITY) return("PnlWznmJob1NSensitivity");
	if (ix == PNLWZNMJOBACMD) return("PnlWznmJobACmd");
	if (ix == PNLWZNMJOBAVAR) return("PnlWznmJobAVar");
	if (ix == PNLWZNMJOBDETAIL) return("PnlWznmJobDetail");
	if (ix == PNLWZNMJOBHEADBAR) return("PnlWznmJobHeadbar");
	if (ix == PNLWZNMJOBHK1NVECTOR) return("PnlWznmJobHk1NVector");
	if (ix == PNLWZNMJOBJOB1NSTAGE) return("PnlWznmJobJob1NStage");
	if (ix == PNLWZNMJOBLIST) return("PnlWznmJobList");
	if (ix == PNLWZNMJOBMNOP) return("PnlWznmJobMNOp");
	if (ix == PNLWZNMJOBMNOPPACK) return("PnlWznmJobMNOppack");
	if (ix == PNLWZNMJOBREC) return("PnlWznmJobRec");
	if (ix == PNLWZNMJOBREF1NBLOCK) return("PnlWznmJobRef1NBlock");
	if (ix == PNLWZNMJOBSUBMNJOB) return("PnlWznmJobSubMNJob");
	if (ix == PNLWZNMJOBSUPMNJOB) return("PnlWznmJobSupMNJob");
	if (ix == PNLWZNMLIBAMAKEFILE) return("PnlWznmLibAMakefile");
	if (ix == PNLWZNMLIBAPKGLIST) return("PnlWznmLibAPkglist");
	if (ix == PNLWZNMLIBDETAIL) return("PnlWznmLibDetail");
	if (ix == PNLWZNMLIBHEADBAR) return("PnlWznmLibHeadbar");
	if (ix == PNLWZNMLIBLIST) return("PnlWznmLibList");
	if (ix == PNLWZNMLIBMNCOMPONENT) return("PnlWznmLibMNComponent");
	if (ix == PNLWZNMLIBMNOPPACK) return("PnlWznmLibMNOppack");
	if (ix == PNLWZNMLIBREC) return("PnlWznmLibRec");
	if (ix == PNLWZNMLIBREF1NFILE) return("PnlWznmLibRef1NFile");
	if (ix == PNLWZNMLOCDETAIL) return("PnlWznmLocDetail");
	if (ix == PNLWZNMLOCHEADBAR) return("PnlWznmLocHeadbar");
	if (ix == PNLWZNMLOCLIST) return("PnlWznmLocList");
	if (ix == PNLWZNMLOCMNVERSION) return("PnlWznmLocMNVersion");
	if (ix == PNLWZNMLOCREC) return("PnlWznmLocRec");
	if (ix == PNLWZNMMCH1NRELEASE) return("PnlWznmMch1NRelease");
	if (ix == PNLWZNMMCHAPAR) return("PnlWznmMchAPar");
	if (ix == PNLWZNMMCHDETAIL) return("PnlWznmMchDetail");
	if (ix == PNLWZNMMCHHEADBAR) return("PnlWznmMchHeadbar");
	if (ix == PNLWZNMMCHLIST) return("PnlWznmMchList");
	if (ix == PNLWZNMMCHREC) return("PnlWznmMchRec");
	if (ix == PNLWZNMMDLDETAIL) return("PnlWznmMdlDetail");
	if (ix == PNLWZNMMDLHEADBAR) return("PnlWznmMdlHeadbar");
	if (ix == PNLWZNMMDLLIST) return("PnlWznmMdlList");
	if (ix == PNLWZNMMDLMDL1NCARD) return("PnlWznmMdlMdl1NCard");
	if (ix == PNLWZNMMDLREC) return("PnlWznmMdlRec");
	if (ix == PNLWZNMMDLREF1NPANEL) return("PnlWznmMdlRef1NPanel");
	if (ix == PNLWZNMMTDAINVPAR) return("PnlWznmMtdAInvpar");
	if (ix == PNLWZNMMTDARETPAR) return("PnlWznmMtdARetpar");
	if (ix == PNLWZNMMTDDETAIL) return("PnlWznmMtdDetail");
	if (ix == PNLWZNMMTDHEADBAR) return("PnlWznmMtdHeadbar");
	if (ix == PNLWZNMMTDLIST) return("PnlWznmMtdList");
	if (ix == PNLWZNMMTDREC) return("PnlWznmMtdRec");
	if (ix == PNLWZNMMTY1NMACHINE) return("PnlWznmMty1NMachine");
	if (ix == PNLWZNMMTYAMAKEFILE) return("PnlWznmMtyAMakefile");
	if (ix == PNLWZNMMTYDETAIL) return("PnlWznmMtyDetail");
	if (ix == PNLWZNMMTYHEADBAR) return("PnlWznmMtyHeadbar");
	if (ix == PNLWZNMMTYLIST) return("PnlWznmMtyList");
	if (ix == PNLWZNMMTYREC) return("PnlWznmMtyRec");
	if (ix == PNLWZNMNAVADMIN) return("PnlWznmNavAdmin");
	if (ix == PNLWZNMNAVAPPDEV) return("PnlWznmNavAppdev");
	if (ix == PNLWZNMNAVAUXFCT) return("PnlWznmNavAuxfct");
	if (ix == PNLWZNMNAVCOMP) return("PnlWznmNavComp");
	if (ix == PNLWZNMNAVDBSTR) return("PnlWznmNavDbstr");
	if (ix == PNLWZNMNAVDEPLOY) return("PnlWznmNavDeploy");
	if (ix == PNLWZNMNAVGLOBAL) return("PnlWznmNavGlobal");
	if (ix == PNLWZNMNAVHEADBAR) return("PnlWznmNavHeadbar");
	if (ix == PNLWZNMNAVJOB) return("PnlWznmNavJob");
	if (ix == PNLWZNMNAVPRE) return("PnlWznmNavPre");
	if (ix == PNLWZNMNAVPROJECT) return("PnlWznmNavProject");
	if (ix == PNLWZNMNAVUIX) return("PnlWznmNavUix");
	if (ix == PNLWZNMOPK1NOP) return("PnlWznmOpk1NOp");
	if (ix == PNLWZNMOPKAINVARG) return("PnlWznmOpkAInvarg");
	if (ix == PNLWZNMOPKARETVAL) return("PnlWznmOpkARetval");
	if (ix == PNLWZNMOPKDETAIL) return("PnlWznmOpkDetail");
	if (ix == PNLWZNMOPKHEADBAR) return("PnlWznmOpkHeadbar");
	if (ix == PNLWZNMOPKLIST) return("PnlWznmOpkList");
	if (ix == PNLWZNMOPKMNCOMPONENT) return("PnlWznmOpkMNComponent");
	if (ix == PNLWZNMOPKMNJOB) return("PnlWznmOpkMNJob");
	if (ix == PNLWZNMOPKMNLIBRARY) return("PnlWznmOpkMNLibrary");
	if (ix == PNLWZNMOPKREC) return("PnlWznmOpkRec");
	if (ix == PNLWZNMOPKREF1NBLOCK) return("PnlWznmOpkRef1NBlock");
	if (ix == PNLWZNMOPKSQKMNSTUB) return("PnlWznmOpkSqkMNStub");
	if (ix == PNLWZNMOPXAINVARG) return("PnlWznmOpxAInvarg");
	if (ix == PNLWZNMOPXARETVAL) return("PnlWznmOpxARetval");
	if (ix == PNLWZNMOPXDETAIL) return("PnlWznmOpxDetail");
	if (ix == PNLWZNMOPXHEADBAR) return("PnlWznmOpxHeadbar");
	if (ix == PNLWZNMOPXLIST) return("PnlWznmOpxList");
	if (ix == PNLWZNMOPXMNJOB) return("PnlWznmOpxMNJob");
	if (ix == PNLWZNMOPXREC) return("PnlWznmOpxRec");
	if (ix == PNLWZNMOPXREF1NBLOCK) return("PnlWznmOpxRef1NBlock");
	if (ix == PNLWZNMOPXSQKMNSTUB) return("PnlWznmOpxSqkMNStub");
	if (ix == PNLWZNMPNLDETAIL) return("PnlWznmPnlDetail");
	if (ix == PNLWZNMPNLHEADBAR) return("PnlWznmPnlHeadbar");
	if (ix == PNLWZNMPNLHK1NCONTROL) return("PnlWznmPnlHk1NControl");
	if (ix == PNLWZNMPNLLIST) return("PnlWznmPnlList");
	if (ix == PNLWZNMPNLMNQUERY) return("PnlWznmPnlMNQuery");
	if (ix == PNLWZNMPNLREC) return("PnlWznmPnlRec");
	if (ix == PNLWZNMPRJ1NVERSION) return("PnlWznmPrj1NVersion");
	if (ix == PNLWZNMPRJDETAIL) return("PnlWznmPrjDetail");
	if (ix == PNLWZNMPRJHEADBAR) return("PnlWznmPrjHeadbar");
	if (ix == PNLWZNMPRJLIST) return("PnlWznmPrjList");
	if (ix == PNLWZNMPRJMNPERSON) return("PnlWznmPrjMNPerson");
	if (ix == PNLWZNMPRJREC) return("PnlWznmPrjRec");
	if (ix == PNLWZNMPRSADETAIL) return("PnlWznmPrsADetail");
	if (ix == PNLWZNMPRSDETAIL) return("PnlWznmPrsDetail");
	if (ix == PNLWZNMPRSHEADBAR) return("PnlWznmPrsHeadbar");
	if (ix == PNLWZNMPRSLIST) return("PnlWznmPrsList");
	if (ix == PNLWZNMPRSMNPROJECT) return("PnlWznmPrsMNProject");
	if (ix == PNLWZNMPRSREC) return("PnlWznmPrsRec");
	if (ix == PNLWZNMPST1NQUERYMOD) return("PnlWznmPst1NQuerymod");
	if (ix == PNLWZNMPSTDETAIL) return("PnlWznmPstDetail");
	if (ix == PNLWZNMPSTHEADBAR) return("PnlWznmPstHeadbar");
	if (ix == PNLWZNMPSTLIST) return("PnlWznmPstList");
	if (ix == PNLWZNMPSTREC) return("PnlWznmPstRec");
	if (ix == PNLWZNMQCODETAIL) return("PnlWznmQcoDetail");
	if (ix == PNLWZNMQCOHEADBAR) return("PnlWznmQcoHeadbar");
	if (ix == PNLWZNMQCOLIST) return("PnlWznmQcoList");
	if (ix == PNLWZNMQCOREC) return("PnlWznmQcoRec");
	if (ix == PNLWZNMQCOREF1NCONTROL) return("PnlWznmQcoRef1NControl");
	if (ix == PNLWZNMQMDDETAIL) return("PnlWznmQmdDetail");
	if (ix == PNLWZNMQMDHEADBAR) return("PnlWznmQmdHeadbar");
	if (ix == PNLWZNMQMDLIST) return("PnlWznmQmdList");
	if (ix == PNLWZNMQMDREC) return("PnlWznmQmdRec");
	if (ix == PNLWZNMQRY1NQUERYMOD) return("PnlWznmQry1NQuerymod");
	if (ix == PNLWZNMQRYACLAUSE) return("PnlWznmQryAClause");
	if (ix == PNLWZNMQRYAORDER) return("PnlWznmQryAOrder");
	if (ix == PNLWZNMQRYDETAIL) return("PnlWznmQryDetail");
	if (ix == PNLWZNMQRYHEADBAR) return("PnlWznmQryHeadbar");
	if (ix == PNLWZNMQRYLIST) return("PnlWznmQryList");
	if (ix == PNLWZNMQRYMNDIALOG) return("PnlWznmQryMNDialog");
	if (ix == PNLWZNMQRYMNPANEL) return("PnlWznmQryMNPanel");
	if (ix == PNLWZNMQRYMNTABLE) return("PnlWznmQryMNTable");
	if (ix == PNLWZNMQRYQRY1NQUERYCOL) return("PnlWznmQryQry1NQuerycol");
	if (ix == PNLWZNMQRYREC) return("PnlWznmQryRec");
	if (ix == PNLWZNMQRYSUP1NQUERY) return("PnlWznmQrySup1NQuery");
	if (ix == PNLWZNMREL1NTABLECOL) return("PnlWznmRel1NTablecol");
	if (ix == PNLWZNMRELATITLE) return("PnlWznmRelATitle");
	if (ix == PNLWZNMRELDETAIL) return("PnlWznmRelDetail");
	if (ix == PNLWZNMRELHEADBAR) return("PnlWznmRelHeadbar");
	if (ix == PNLWZNMRELLIST) return("PnlWznmRelList");
	if (ix == PNLWZNMRELREC) return("PnlWznmRelRec");
	if (ix == PNLWZNMRELREF1NCONTROL) return("PnlWznmRelRef1NControl");
	if (ix == PNLWZNMRELREF1NDIALOG) return("PnlWznmRelRef1NDialog");
	if (ix == PNLWZNMRELREF1NPANEL) return("PnlWznmRelRef1NPanel");
	if (ix == PNLWZNMRELSUP1NRELATION) return("PnlWznmRelSup1NRelation");
	if (ix == PNLWZNMRLSDETAIL) return("PnlWznmRlsDetail");
	if (ix == PNLWZNMRLSHEADBAR) return("PnlWznmRlsHeadbar");
	if (ix == PNLWZNMRLSLIST) return("PnlWznmRlsList");
	if (ix == PNLWZNMRLSREC) return("PnlWznmRlsRec");
	if (ix == PNLWZNMRTJ1NRTBLOCK) return("PnlWznmRtj1NRtblock");
	if (ix == PNLWZNMRTJ1NRTDPCH) return("PnlWznmRtj1NRtdpch");
	if (ix == PNLWZNMRTJDETAIL) return("PnlWznmRtjDetail");
	if (ix == PNLWZNMRTJHEADBAR) return("PnlWznmRtjHeadbar");
	if (ix == PNLWZNMRTJLIST) return("PnlWznmRtjList");
	if (ix == PNLWZNMRTJREC) return("PnlWznmRtjRec");
	if (ix == PNLWZNMRTJSUP1NRTJOB) return("PnlWznmRtjSup1NRtjob");
	if (ix == PNLWZNMSBS1NSTUB) return("PnlWznmSbs1NStub");
	if (ix == PNLWZNMSBS1NTABLECOL) return("PnlWznmSbs1NTablecol");
	if (ix == PNLWZNMSBSASBMNSUBSET) return("PnlWznmSbsAsbMNSubset");
	if (ix == PNLWZNMSBSATITLE) return("PnlWznmSbsATitle");
	if (ix == PNLWZNMSBSBSBMNSUBSET) return("PnlWznmSbsBsbMNSubset");
	if (ix == PNLWZNMSBSDETAIL) return("PnlWznmSbsDetail");
	if (ix == PNLWZNMSBSFRS1NRELATION) return("PnlWznmSbsFrs1NRelation");
	if (ix == PNLWZNMSBSHEADBAR) return("PnlWznmSbsHeadbar");
	if (ix == PNLWZNMSBSLIST) return("PnlWznmSbsList");
	if (ix == PNLWZNMSBSPST1NQUERYMOD) return("PnlWznmSbsPst1NQuerymod");
	if (ix == PNLWZNMSBSREC) return("PnlWznmSbsRec");
	if (ix == PNLWZNMSBSTOS1NRELATION) return("PnlWznmSbsTos1NRelation");
	if (ix == PNLWZNMSEQDETAIL) return("PnlWznmSeqDetail");
	if (ix == PNLWZNMSEQHEADBAR) return("PnlWznmSeqHeadbar");
	if (ix == PNLWZNMSEQLIST) return("PnlWznmSeqList");
	if (ix == PNLWZNMSEQREC) return("PnlWznmSeqRec");
	if (ix == PNLWZNMSEQSEQ1NSTATE) return("PnlWznmSeqSeq1NState");
	if (ix == PNLWZNMSGE1NSENSITIVITY) return("PnlWznmSge1NSensitivity");
	if (ix == PNLWZNMSGEDETAIL) return("PnlWznmSgeDetail");
	if (ix == PNLWZNMSGEHEADBAR) return("PnlWznmSgeHeadbar");
	if (ix == PNLWZNMSGELIST) return("PnlWznmSgeList");
	if (ix == PNLWZNMSGEREC) return("PnlWznmSgeRec");
	if (ix == PNLWZNMSGESQKMNSTUB) return("PnlWznmSgeSqkMNStub");
	if (ix == PNLWZNMSTBDETAIL) return("PnlWznmStbDetail");
	if (ix == PNLWZNMSTBHEADBAR) return("PnlWznmStbHeadbar");
	if (ix == PNLWZNMSTBLIST) return("PnlWznmStbList");
	if (ix == PNLWZNMSTBMNCALL) return("PnlWznmStbMNCall");
	if (ix == PNLWZNMSTBMNSQUAWK) return("PnlWznmStbMNSquawk");
	if (ix == PNLWZNMSTBREC) return("PnlWznmStbRec");
	if (ix == PNLWZNMSTBSUBMNSTUB) return("PnlWznmStbSubMNStub");
	if (ix == PNLWZNMSTBSUPMNSTUB) return("PnlWznmStbSupMNStub");
	if (ix == PNLWZNMSTEASTEP) return("PnlWznmSteAStep");
	if (ix == PNLWZNMSTEDETAIL) return("PnlWznmSteDetail");
	if (ix == PNLWZNMSTEHEADBAR) return("PnlWznmSteHeadbar");
	if (ix == PNLWZNMSTELIST) return("PnlWznmSteList");
	if (ix == PNLWZNMSTEREC) return("PnlWznmSteRec");
	if (ix == PNLWZNMTAGDETAIL) return("PnlWznmTagDetail");
	if (ix == PNLWZNMTAGHEADBAR) return("PnlWznmTagHeadbar");
	if (ix == PNLWZNMTAGLIST) return("PnlWznmTagList");
	if (ix == PNLWZNMTAGREC) return("PnlWznmTagRec");
	if (ix == PNLWZNMTBL1NCHECK) return("PnlWznmTbl1NCheck");
	if (ix == PNLWZNMTBL1NIMPEXP) return("PnlWznmTbl1NImpexp");
	if (ix == PNLWZNMTBL1NSTUB) return("PnlWznmTbl1NStub");
	if (ix == PNLWZNMTBL1NSUBSET) return("PnlWznmTbl1NSubset");
	if (ix == PNLWZNMTBLALOADFCT) return("PnlWznmTblALoadfct");
	if (ix == PNLWZNMTBLATITLE) return("PnlWznmTblATitle");
	if (ix == PNLWZNMTBLDETAIL) return("PnlWznmTblDetail");
	if (ix == PNLWZNMTBLFCT1NTABLECOL) return("PnlWznmTblFct1NTablecol");
	if (ix == PNLWZNMTBLFR1NRELATION) return("PnlWznmTblFr1NRelation");
	if (ix == PNLWZNMTBLHEADBAR) return("PnlWznmTblHeadbar");
	if (ix == PNLWZNMTBLHK1NVECTOR) return("PnlWznmTblHk1NVector");
	if (ix == PNLWZNMTBLLIST) return("PnlWznmTblList");
	if (ix == PNLWZNMTBLMNQUERY) return("PnlWznmTblMNQuery");
	if (ix == PNLWZNMTBLMNVECTOR) return("PnlWznmTblMNVector");
	if (ix == PNLWZNMTBLPST1NQUERYMOD) return("PnlWznmTblPst1NQuerymod");
	if (ix == PNLWZNMTBLREC) return("PnlWznmTblRec");
	if (ix == PNLWZNMTBLREF1NCALL) return("PnlWznmTblRef1NCall");
	if (ix == PNLWZNMTBLREF1NDIALOG) return("PnlWznmTblRef1NDialog");
	if (ix == PNLWZNMTBLREF1NPANEL) return("PnlWznmTblRef1NPanel");
	if (ix == PNLWZNMTBLREF1NQUERYMOD) return("PnlWznmTblRef1NQuerymod");
	if (ix == PNLWZNMTBLREF1NRTBLOCK) return("PnlWznmTblRef1NRtblock");
	if (ix == PNLWZNMTBLSRC1NFEED) return("PnlWznmTblSrc1NFeed");
	if (ix == PNLWZNMTBLTBL1NTABLECOL) return("PnlWznmTblTbl1NTablecol");
	if (ix == PNLWZNMTBLTO1NRELATION) return("PnlWznmTblTo1NRelation");
	if (ix == PNLWZNMTCO1NCHECK) return("PnlWznmTco1NCheck");
	if (ix == PNLWZNMTCO1NIMPEXPCOL) return("PnlWznmTco1NImpexpcol");
	if (ix == PNLWZNMTCO1NQUERYCOL) return("PnlWznmTco1NQuerycol");
	if (ix == PNLWZNMTCOATITLE) return("PnlWznmTcoATitle");
	if (ix == PNLWZNMTCODETAIL) return("PnlWznmTcoDetail");
	if (ix == PNLWZNMTCOHEADBAR) return("PnlWznmTcoHeadbar");
	if (ix == PNLWZNMTCOLIST) return("PnlWznmTcoList");
	if (ix == PNLWZNMTCOREC) return("PnlWznmTcoRec");
	if (ix == PNLWZNMTCOREF1NCONTROL) return("PnlWznmTcoRef1NControl");
	if (ix == PNLWZNMTCOREF1NQUERYMOD) return("PnlWznmTcoRef1NQuerymod");
	if (ix == PNLWZNMUSGAACCESS) return("PnlWznmUsgAAccess");
	if (ix == PNLWZNMUSGDETAIL) return("PnlWznmUsgDetail");
	if (ix == PNLWZNMUSGHEADBAR) return("PnlWznmUsgHeadbar");
	if (ix == PNLWZNMUSGLIST) return("PnlWznmUsgList");
	if (ix == PNLWZNMUSGMNUSER) return("PnlWznmUsgMNUser");
	if (ix == PNLWZNMUSGREC) return("PnlWznmUsgRec");
	if (ix == PNLWZNMUSR1NSESSION) return("PnlWznmUsr1NSession");
	if (ix == PNLWZNMUSRAACCESS) return("PnlWznmUsrAAccess");
	if (ix == PNLWZNMUSRDETAIL) return("PnlWznmUsrDetail");
	if (ix == PNLWZNMUSRHEADBAR) return("PnlWznmUsrHeadbar");
	if (ix == PNLWZNMUSRLIST) return("PnlWznmUsrList");
	if (ix == PNLWZNMUSRMNUSERGROUP) return("PnlWznmUsrMNUsergroup");
	if (ix == PNLWZNMUSRREC) return("PnlWznmUsrRec");
	if (ix == PNLWZNMUTLHEADBAR) return("PnlWznmUtlHeadbar");
	if (ix == PNLWZNMVECATITLE) return("PnlWznmVecATitle");
	if (ix == PNLWZNMVECDETAIL) return("PnlWznmVecDetail");
	if (ix == PNLWZNMVECFCT1NTABLECOL) return("PnlWznmVecFct1NTablecol");
	if (ix == PNLWZNMVECHEADBAR) return("PnlWznmVecHeadbar");
	if (ix == PNLWZNMVECLIST) return("PnlWznmVecList");
	if (ix == PNLWZNMVECMNTABLE) return("PnlWznmVecMNTable");
	if (ix == PNLWZNMVECPST1NQUERYMOD) return("PnlWznmVecPst1NQuerymod");
	if (ix == PNLWZNMVECREC) return("PnlWznmVecRec");
	if (ix == PNLWZNMVECREF1NPANEL) return("PnlWznmVecRef1NPanel");
	if (ix == PNLWZNMVECSRC1NFEED) return("PnlWznmVecSrc1NFeed");
	if (ix == PNLWZNMVECVEC1NVECTORITEM) return("PnlWznmVecVec1NVectoritem");
	if (ix == PNLWZNMVER1NBLOCK) return("PnlWznmVer1NBlock");
	if (ix == PNLWZNMVER1NCALL) return("PnlWznmVer1NCall");
	if (ix == PNLWZNMVER1NCAPABILITY) return("PnlWznmVer1NCapability");
	if (ix == PNLWZNMVER1NCOMPONENT) return("PnlWznmVer1NComponent");
	if (ix == PNLWZNMVER1NIMPEXPCPLX) return("PnlWznmVer1NImpexpcplx");
	if (ix == PNLWZNMVER1NJOB) return("PnlWznmVer1NJob");
	if (ix == PNLWZNMVER1NOPPACK) return("PnlWznmVer1NOppack");
	if (ix == PNLWZNMVER1NPRESET) return("PnlWznmVer1NPreset");
	if (ix == PNLWZNMVER1NQUERY) return("PnlWznmVer1NQuery");
	if (ix == PNLWZNMVER1NRELATION) return("PnlWznmVer1NRelation");
	if (ix == PNLWZNMVER1NTABLE) return("PnlWznmVer1NTable");
	if (ix == PNLWZNMVER1NVECTOR) return("PnlWznmVer1NVector");
	if (ix == PNLWZNMVERBVR1NVERSION) return("PnlWznmVerBvr1NVersion");
	if (ix == PNLWZNMVERDETAIL) return("PnlWznmVerDetail");
	if (ix == PNLWZNMVERHEADBAR) return("PnlWznmVerHeadbar");
	if (ix == PNLWZNMVERLIST) return("PnlWznmVerList");
	if (ix == PNLWZNMVERMNLOCALE) return("PnlWznmVerMNLocale");
	if (ix == PNLWZNMVERREC) return("PnlWznmVerRec");
	if (ix == PNLWZNMVERREF1NFILE) return("PnlWznmVerRef1NFile");
	if (ix == PNLWZNMVERVER1NAPP) return("PnlWznmVerVer1NApp");
	if (ix == PNLWZNMVERVER1NERROR) return("PnlWznmVerVer1NError");
	if (ix == PNLWZNMVERVER1NMODULE) return("PnlWznmVerVer1NModule");
	if (ix == PNLWZNMVITDETAIL) return("PnlWznmVitDetail");
	if (ix == PNLWZNMVITHEADBAR) return("PnlWznmVitHeadbar");
	if (ix == PNLWZNMVITLIST) return("PnlWznmVitList");
	if (ix == PNLWZNMVITREC) return("PnlWznmVitRec");
	if (ix == QRYWZNMAPP1NRTJOB) return("QryWznmApp1NRtjob");
	if (ix == QRYWZNMAPPAPP1NSEQUENCE) return("QryWznmAppApp1NSequence");
	if (ix == QRYWZNMAPPLIST) return("QryWznmAppList");
	if (ix == QRYWZNMAPPREF1NFILE) return("QryWznmAppRef1NFile");
	if (ix == QRYWZNMBLK1NRTDPCH) return("QryWznmBlk1NRtdpch");
	if (ix == QRYWZNMBLKAITEM) return("QryWznmBlkAItem");
	if (ix == QRYWZNMBLKLIST) return("QryWznmBlkList");
	if (ix == QRYWZNMBLKREF1NRTBLOCK) return("QryWznmBlkRef1NRtblock");
	if (ix == QRYWZNMCAL1NSENSITIVITY) return("QryWznmCal1NSensitivity");
	if (ix == QRYWZNMCALLIST) return("QryWznmCalList");
	if (ix == QRYWZNMCALMNSTUB) return("QryWznmCalMNStub");
	if (ix == QRYWZNMCAPAPAR) return("QryWznmCapAPar");
	if (ix == QRYWZNMCAPLIST) return("QryWznmCapList");
	if (ix == QRYWZNMCAR1NDIALOG) return("QryWznmCar1NDialog");
	if (ix == QRYWZNMCARCAR1NPANEL) return("QryWznmCarCar1NPanel");
	if (ix == QRYWZNMCARHK1NCONTROL) return("QryWznmCarHk1NControl");
	if (ix == QRYWZNMCARLIST) return("QryWznmCarList");
	if (ix == QRYWZNMCHKLIST) return("QryWznmChkList");
	if (ix == QRYWZNMCHKREF1NCALL) return("QryWznmChkRef1NCall");
	if (ix == QRYWZNMCMP1NRELEASE) return("QryWznmCmp1NRelease");
	if (ix == QRYWZNMCMPLIST) return("QryWznmCmpList");
	if (ix == QRYWZNMCMPMNLIBRARY) return("QryWznmCmpMNLibrary");
	if (ix == QRYWZNMCMPMNOPPACK) return("QryWznmCmpMNOppack");
	if (ix == QRYWZNMCONAPAR) return("QryWznmConAPar");
	if (ix == QRYWZNMCONFEDREF1NRTBLOCK) return("QryWznmConFedRef1NRtblock");
	if (ix == QRYWZNMCONLIST) return("QryWznmConList");
	if (ix == QRYWZNMCONSUP1NCONTROL) return("QryWznmConSup1NControl");
	if (ix == QRYWZNMCTP1NTAG) return("QryWznmCtp1NTag");
	if (ix == QRYWZNMCTPAPAR) return("QryWznmCtpAPar");
	if (ix == QRYWZNMCTPKKEY) return("QryWznmCtpKKey");
	if (ix == QRYWZNMCTPKPARKEY) return("QryWznmCtpKParKey");
	if (ix == QRYWZNMCTPLIST) return("QryWznmCtpList");
	if (ix == QRYWZNMCTPTPL1NCAPABILITY) return("QryWznmCtpTpl1NCapability");
	if (ix == QRYWZNMDLGHK1NCONTROL) return("QryWznmDlgHk1NControl");
	if (ix == QRYWZNMDLGLIST) return("QryWznmDlgList");
	if (ix == QRYWZNMDLGMNQUERY) return("QryWznmDlgMNQuery");
	if (ix == QRYWZNMDLGREF1NCONTROL) return("QryWznmDlgRef1NControl");
	if (ix == QRYWZNMERRLIST) return("QryWznmErrList");
	if (ix == QRYWZNMFILLIST) return("QryWznmFilList");
	if (ix == QRYWZNMIELLIST) return("QryWznmIelList");
	if (ix == QRYWZNMIEX1NIMPEXP) return("QryWznmIex1NImpexp");
	if (ix == QRYWZNMIEXHK1NVECTOR) return("QryWznmIexHk1NVector");
	if (ix == QRYWZNMIEXLIST) return("QryWznmIexList");
	if (ix == QRYWZNMIEXREF1NDIALOG) return("QryWznmIexRef1NDialog");
	if (ix == QRYWZNMIMEHK1NVECTOR) return("QryWznmImeHk1NVector");
	if (ix == QRYWZNMIMEIME1NIMPEXPCOL) return("QryWznmImeIme1NImpexpcol");
	if (ix == QRYWZNMIMELIST) return("QryWznmImeList");
	if (ix == QRYWZNMIMESUP1NIMPEXP) return("QryWznmImeSup1NImpexp");
	if (ix == QRYWZNMJOB1NMETHOD) return("QryWznmJob1NMethod");
	if (ix == QRYWZNMJOB1NRTJOB) return("QryWznmJob1NRtjob");
	if (ix == QRYWZNMJOB1NSENSITIVITY) return("QryWznmJob1NSensitivity");
	if (ix == QRYWZNMJOBACMD) return("QryWznmJobACmd");
	if (ix == QRYWZNMJOBAVAR) return("QryWznmJobAVar");
	if (ix == QRYWZNMJOBHK1NVECTOR) return("QryWznmJobHk1NVector");
	if (ix == QRYWZNMJOBJOB1NSTAGE) return("QryWznmJobJob1NStage");
	if (ix == QRYWZNMJOBLIST) return("QryWznmJobList");
	if (ix == QRYWZNMJOBMNOP) return("QryWznmJobMNOp");
	if (ix == QRYWZNMJOBMNOPPACK) return("QryWznmJobMNOppack");
	if (ix == QRYWZNMJOBREF1NBLOCK) return("QryWznmJobRef1NBlock");
	if (ix == QRYWZNMJOBSUBMNJOB) return("QryWznmJobSubMNJob");
	if (ix == QRYWZNMJOBSUPMNJOB) return("QryWznmJobSupMNJob");
	if (ix == QRYWZNMLIBAMAKEFILE) return("QryWznmLibAMakefile");
	if (ix == QRYWZNMLIBAPKGLIST) return("QryWznmLibAPkglist");
	if (ix == QRYWZNMLIBLIST) return("QryWznmLibList");
	if (ix == QRYWZNMLIBMNCOMPONENT) return("QryWznmLibMNComponent");
	if (ix == QRYWZNMLIBMNOPPACK) return("QryWznmLibMNOppack");
	if (ix == QRYWZNMLIBREF1NFILE) return("QryWznmLibRef1NFile");
	if (ix == QRYWZNMLOCLIST) return("QryWznmLocList");
	if (ix == QRYWZNMLOCMNVERSION) return("QryWznmLocMNVersion");
	if (ix == QRYWZNMMCH1NRELEASE) return("QryWznmMch1NRelease");
	if (ix == QRYWZNMMCHAPAR) return("QryWznmMchAPar");
	if (ix == QRYWZNMMCHLIST) return("QryWznmMchList");
	if (ix == QRYWZNMMDLLIST) return("QryWznmMdlList");
	if (ix == QRYWZNMMDLMDL1NCARD) return("QryWznmMdlMdl1NCard");
	if (ix == QRYWZNMMDLREF1NPANEL) return("QryWznmMdlRef1NPanel");
	if (ix == QRYWZNMMTDAINVPAR) return("QryWznmMtdAInvpar");
	if (ix == QRYWZNMMTDARETPAR) return("QryWznmMtdARetpar");
	if (ix == QRYWZNMMTDLIST) return("QryWznmMtdList");
	if (ix == QRYWZNMMTY1NMACHINE) return("QryWznmMty1NMachine");
	if (ix == QRYWZNMMTYAMAKEFILE) return("QryWznmMtyAMakefile");
	if (ix == QRYWZNMMTYLIST) return("QryWznmMtyList");
	if (ix == QRYWZNMOPK1NOP) return("QryWznmOpk1NOp");
	if (ix == QRYWZNMOPKAINVARG) return("QryWznmOpkAInvarg");
	if (ix == QRYWZNMOPKARETVAL) return("QryWznmOpkARetval");
	if (ix == QRYWZNMOPKLIST) return("QryWznmOpkList");
	if (ix == QRYWZNMOPKMNCOMPONENT) return("QryWznmOpkMNComponent");
	if (ix == QRYWZNMOPKMNJOB) return("QryWznmOpkMNJob");
	if (ix == QRYWZNMOPKMNLIBRARY) return("QryWznmOpkMNLibrary");
	if (ix == QRYWZNMOPKREF1NBLOCK) return("QryWznmOpkRef1NBlock");
	if (ix == QRYWZNMOPKSQKMNSTUB) return("QryWznmOpkSqkMNStub");
	if (ix == QRYWZNMOPXAINVARG) return("QryWznmOpxAInvarg");
	if (ix == QRYWZNMOPXARETVAL) return("QryWznmOpxARetval");
	if (ix == QRYWZNMOPXLIST) return("QryWznmOpxList");
	if (ix == QRYWZNMOPXMNJOB) return("QryWznmOpxMNJob");
	if (ix == QRYWZNMOPXREF1NBLOCK) return("QryWznmOpxRef1NBlock");
	if (ix == QRYWZNMOPXSQKMNSTUB) return("QryWznmOpxSqkMNStub");
	if (ix == QRYWZNMPNLHK1NCONTROL) return("QryWznmPnlHk1NControl");
	if (ix == QRYWZNMPNLLIST) return("QryWznmPnlList");
	if (ix == QRYWZNMPNLMNQUERY) return("QryWznmPnlMNQuery");
	if (ix == QRYWZNMPRJ1NVERSION) return("QryWznmPrj1NVersion");
	if (ix == QRYWZNMPRJLIST) return("QryWznmPrjList");
	if (ix == QRYWZNMPRJMNPERSON) return("QryWznmPrjMNPerson");
	if (ix == QRYWZNMPRSADETAIL) return("QryWznmPrsADetail");
	if (ix == QRYWZNMPRSLIST) return("QryWznmPrsList");
	if (ix == QRYWZNMPRSMNPROJECT) return("QryWznmPrsMNProject");
	if (ix == QRYWZNMPST1NQUERYMOD) return("QryWznmPst1NQuerymod");
	if (ix == QRYWZNMPSTLIST) return("QryWznmPstList");
	if (ix == QRYWZNMQCOLIST) return("QryWznmQcoList");
	if (ix == QRYWZNMQCOREF1NCONTROL) return("QryWznmQcoRef1NControl");
	if (ix == QRYWZNMQMDLIST) return("QryWznmQmdList");
	if (ix == QRYWZNMQRY1NQUERYMOD) return("QryWznmQry1NQuerymod");
	if (ix == QRYWZNMQRYACLAUSE) return("QryWznmQryAClause");
	if (ix == QRYWZNMQRYAORDER) return("QryWznmQryAOrder");
	if (ix == QRYWZNMQRYLIST) return("QryWznmQryList");
	if (ix == QRYWZNMQRYMNDIALOG) return("QryWznmQryMNDialog");
	if (ix == QRYWZNMQRYMNPANEL) return("QryWznmQryMNPanel");
	if (ix == QRYWZNMQRYMNTABLE) return("QryWznmQryMNTable");
	if (ix == QRYWZNMQRYQRY1NQUERYCOL) return("QryWznmQryQry1NQuerycol");
	if (ix == QRYWZNMQRYSUP1NQUERY) return("QryWznmQrySup1NQuery");
	if (ix == QRYWZNMREL1NTABLECOL) return("QryWznmRel1NTablecol");
	if (ix == QRYWZNMRELATITLE) return("QryWznmRelATitle");
	if (ix == QRYWZNMRELLIST) return("QryWznmRelList");
	if (ix == QRYWZNMRELREF1NCONTROL) return("QryWznmRelRef1NControl");
	if (ix == QRYWZNMRELREF1NDIALOG) return("QryWznmRelRef1NDialog");
	if (ix == QRYWZNMRELREF1NPANEL) return("QryWznmRelRef1NPanel");
	if (ix == QRYWZNMRELSUP1NRELATION) return("QryWznmRelSup1NRelation");
	if (ix == QRYWZNMRLSLIST) return("QryWznmRlsList");
	if (ix == QRYWZNMRTJ1NRTBLOCK) return("QryWznmRtj1NRtblock");
	if (ix == QRYWZNMRTJ1NRTDPCH) return("QryWznmRtj1NRtdpch");
	if (ix == QRYWZNMRTJLIST) return("QryWznmRtjList");
	if (ix == QRYWZNMRTJSUP1NRTJOB) return("QryWznmRtjSup1NRtjob");
	if (ix == QRYWZNMSBS1NSTUB) return("QryWznmSbs1NStub");
	if (ix == QRYWZNMSBS1NTABLECOL) return("QryWznmSbs1NTablecol");
	if (ix == QRYWZNMSBSASBMNSUBSET) return("QryWznmSbsAsbMNSubset");
	if (ix == QRYWZNMSBSATITLE) return("QryWznmSbsATitle");
	if (ix == QRYWZNMSBSBSBMNSUBSET) return("QryWznmSbsBsbMNSubset");
	if (ix == QRYWZNMSBSFRS1NRELATION) return("QryWznmSbsFrs1NRelation");
	if (ix == QRYWZNMSBSLIST) return("QryWznmSbsList");
	if (ix == QRYWZNMSBSPST1NQUERYMOD) return("QryWznmSbsPst1NQuerymod");
	if (ix == QRYWZNMSBSTOS1NRELATION) return("QryWznmSbsTos1NRelation");
	if (ix == QRYWZNMSEQLIST) return("QryWznmSeqList");
	if (ix == QRYWZNMSEQSEQ1NSTATE) return("QryWznmSeqSeq1NState");
	if (ix == QRYWZNMSGE1NSENSITIVITY) return("QryWznmSge1NSensitivity");
	if (ix == QRYWZNMSGELIST) return("QryWznmSgeList");
	if (ix == QRYWZNMSGESQKMNSTUB) return("QryWznmSgeSqkMNStub");
	if (ix == QRYWZNMSTBLIST) return("QryWznmStbList");
	if (ix == QRYWZNMSTBMNCALL) return("QryWznmStbMNCall");
	if (ix == QRYWZNMSTBMNSQUAWK) return("QryWznmStbMNSquawk");
	if (ix == QRYWZNMSTBSUBMNSTUB) return("QryWznmStbSubMNStub");
	if (ix == QRYWZNMSTBSUPMNSTUB) return("QryWznmStbSupMNStub");
	if (ix == QRYWZNMSTEASTEP) return("QryWznmSteAStep");
	if (ix == QRYWZNMSTELIST) return("QryWznmSteList");
	if (ix == QRYWZNMTAGLIST) return("QryWznmTagList");
	if (ix == QRYWZNMTBL1NCHECK) return("QryWznmTbl1NCheck");
	if (ix == QRYWZNMTBL1NIMPEXP) return("QryWznmTbl1NImpexp");
	if (ix == QRYWZNMTBL1NSTUB) return("QryWznmTbl1NStub");
	if (ix == QRYWZNMTBL1NSUBSET) return("QryWznmTbl1NSubset");
	if (ix == QRYWZNMTBLALOADFCT) return("QryWznmTblALoadfct");
	if (ix == QRYWZNMTBLATITLE) return("QryWznmTblATitle");
	if (ix == QRYWZNMTBLFCT1NTABLECOL) return("QryWznmTblFct1NTablecol");
	if (ix == QRYWZNMTBLFR1NRELATION) return("QryWznmTblFr1NRelation");
	if (ix == QRYWZNMTBLHK1NVECTOR) return("QryWznmTblHk1NVector");
	if (ix == QRYWZNMTBLLIST) return("QryWznmTblList");
	if (ix == QRYWZNMTBLMNQUERY) return("QryWznmTblMNQuery");
	if (ix == QRYWZNMTBLMNVECTOR) return("QryWznmTblMNVector");
	if (ix == QRYWZNMTBLPST1NQUERYMOD) return("QryWznmTblPst1NQuerymod");
	if (ix == QRYWZNMTBLREF1NCALL) return("QryWznmTblRef1NCall");
	if (ix == QRYWZNMTBLREF1NDIALOG) return("QryWznmTblRef1NDialog");
	if (ix == QRYWZNMTBLREF1NPANEL) return("QryWznmTblRef1NPanel");
	if (ix == QRYWZNMTBLREF1NQUERYMOD) return("QryWznmTblRef1NQuerymod");
	if (ix == QRYWZNMTBLREF1NRTBLOCK) return("QryWznmTblRef1NRtblock");
	if (ix == QRYWZNMTBLSRC1NFEED) return("QryWznmTblSrc1NFeed");
	if (ix == QRYWZNMTBLTBL1NTABLECOL) return("QryWznmTblTbl1NTablecol");
	if (ix == QRYWZNMTBLTO1NRELATION) return("QryWznmTblTo1NRelation");
	if (ix == QRYWZNMTCO1NCHECK) return("QryWznmTco1NCheck");
	if (ix == QRYWZNMTCO1NIMPEXPCOL) return("QryWznmTco1NImpexpcol");
	if (ix == QRYWZNMTCO1NQUERYCOL) return("QryWznmTco1NQuerycol");
	if (ix == QRYWZNMTCOATITLE) return("QryWznmTcoATitle");
	if (ix == QRYWZNMTCOLIST) return("QryWznmTcoList");
	if (ix == QRYWZNMTCOREF1NCONTROL) return("QryWznmTcoRef1NControl");
	if (ix == QRYWZNMTCOREF1NQUERYMOD) return("QryWznmTcoRef1NQuerymod");
	if (ix == QRYWZNMUSGAACCESS) return("QryWznmUsgAAccess");
	if (ix == QRYWZNMUSGLIST) return("QryWznmUsgList");
	if (ix == QRYWZNMUSGMNUSER) return("QryWznmUsgMNUser");
	if (ix == QRYWZNMUSR1NSESSION) return("QryWznmUsr1NSession");
	if (ix == QRYWZNMUSRAACCESS) return("QryWznmUsrAAccess");
	if (ix == QRYWZNMUSRLIST) return("QryWznmUsrList");
	if (ix == QRYWZNMUSRMNUSERGROUP) return("QryWznmUsrMNUsergroup");
	if (ix == QRYWZNMVECATITLE) return("QryWznmVecATitle");
	if (ix == QRYWZNMVECFCT1NTABLECOL) return("QryWznmVecFct1NTablecol");
	if (ix == QRYWZNMVECLIST) return("QryWznmVecList");
	if (ix == QRYWZNMVECMNTABLE) return("QryWznmVecMNTable");
	if (ix == QRYWZNMVECPST1NQUERYMOD) return("QryWznmVecPst1NQuerymod");
	if (ix == QRYWZNMVECREF1NPANEL) return("QryWznmVecRef1NPanel");
	if (ix == QRYWZNMVECSRC1NFEED) return("QryWznmVecSrc1NFeed");
	if (ix == QRYWZNMVECVEC1NVECTORITEM) return("QryWznmVecVec1NVectoritem");
	if (ix == QRYWZNMVER1NBLOCK) return("QryWznmVer1NBlock");
	if (ix == QRYWZNMVER1NCALL) return("QryWznmVer1NCall");
	if (ix == QRYWZNMVER1NCAPABILITY) return("QryWznmVer1NCapability");
	if (ix == QRYWZNMVER1NCOMPONENT) return("QryWznmVer1NComponent");
	if (ix == QRYWZNMVER1NIMPEXPCPLX) return("QryWznmVer1NImpexpcplx");
	if (ix == QRYWZNMVER1NJOB) return("QryWznmVer1NJob");
	if (ix == QRYWZNMVER1NOPPACK) return("QryWznmVer1NOppack");
	if (ix == QRYWZNMVER1NPRESET) return("QryWznmVer1NPreset");
	if (ix == QRYWZNMVER1NQUERY) return("QryWznmVer1NQuery");
	if (ix == QRYWZNMVER1NRELATION) return("QryWznmVer1NRelation");
	if (ix == QRYWZNMVER1NTABLE) return("QryWznmVer1NTable");
	if (ix == QRYWZNMVER1NVECTOR) return("QryWznmVer1NVector");
	if (ix == QRYWZNMVERBVR1NVERSION) return("QryWznmVerBvr1NVersion");
	if (ix == QRYWZNMVERLIST) return("QryWznmVerList");
	if (ix == QRYWZNMVERMNLOCALE) return("QryWznmVerMNLocale");
	if (ix == QRYWZNMVERREF1NFILE) return("QryWznmVerRef1NFile");
	if (ix == QRYWZNMVERVER1NAPP) return("QryWznmVerVer1NApp");
	if (ix == QRYWZNMVERVER1NERROR) return("QryWznmVerVer1NError");
	if (ix == QRYWZNMVERVER1NMODULE) return("QryWznmVerVer1NModule");
	if (ix == QRYWZNMVITLIST) return("QryWznmVitList");
	if (ix == ROOTWZNM) return("RootWznm");
	if (ix == SESSWZNM) return("SessWznm");

	return("");
};

