/**
	* \file ApiWznm.java
	* Wznm Java API package global functionality
	* \copyright (C) 2018-2020 MPSI Technologies GmbH
	* \author Alexander Wirthmueller (auto-generation)
	* \date created: 5 Dec 2020
  */
// IP header --- ABOVE

package apiwznm;

import java.io.*;

import javax.xml.parsers.*;
import javax.xml.transform.*;
import javax.xml.transform.dom.*;
import javax.xml.transform.stream.*;

import org.w3c.dom.*;
import org.xml.sax.*;

import sbecore.*;

public class ApiWznm {

	public static final String WZNM_VERSION = "1.1.5";
	public static final int WZNM_VERSION_MAJOR = 1;
	public static final int WZNM_VERSION_MINOR = 1;
	public static final int WZNM_VERSION_SUB = 5;

	public static DpchEngWznm readDpchEng(
				String s
			) {
		DpchEngWznm dpcheng = null;

		try {
			InputSource is = new InputSource();
			is.setCharacterStream(new StringReader(s));

			Document doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(is);

			int ixWznmVDpch = VecWznmVDpch.getIx(Xmlio.extractRoot(doc));
			
			if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMAPPIMPSTRDATA) dpcheng = (new DlgWznmAppImpstr()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMAPPNEWDATA) dpcheng = (new DlgWznmAppNew()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMAPPWRITEDATA) dpcheng = (new DlgWznmAppWrite()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMFILDOWNLOADDATA) dpcheng = (new DlgWznmFilDownload()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMFILNEWDATA) dpcheng = (new DlgWznmFilNew()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMMCHWRINISCRDATA) dpcheng = (new DlgWznmMchWriniscr()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMNAVLOAINIDATA) dpcheng = (new DlgWznmNavLoaini()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMNAVMNGLICDATA) dpcheng = (new DlgWznmNavMnglic()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMPRJIMPEXDATA) dpcheng = (new DlgWznmPrjImpex()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMPRJNEWDATA) dpcheng = (new DlgWznmPrjNew()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMRLSFINREPTRDATA) dpcheng = (new DlgWznmRlsFinreptr()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMRLSSTAREPTRDATA) dpcheng = (new DlgWznmRlsStareptr()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMRLSWRITEDATA) dpcheng = (new DlgWznmRlsWrite()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMUSRMNGKEYPAIRDATA) dpcheng = (new DlgWznmUsrMngkeypair()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMUTLEXTRIPDATA) dpcheng = (new DlgWznmUtlExtrip()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMUTLMRGIPDATA) dpcheng = (new DlgWznmUtlMrgip()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERBSCUIDATA) dpcheng = (new DlgWznmVerBscui()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERCUSTJOBDATA) dpcheng = (new DlgWznmVerCustjob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERCUSTJTRDATA) dpcheng = (new DlgWznmVerCustjtr()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERCUSTUIDATA) dpcheng = (new DlgWznmVerCustui()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERDBSTRDATA) dpcheng = (new DlgWznmVerDbstr()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERDEPLOYDATA) dpcheng = (new DlgWznmVerDeploy()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERFINMODDATA) dpcheng = (new DlgWznmVerFinmod()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERGENJTRDATA) dpcheng = (new DlgWznmVerGenjtr()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERGENUIDATA) dpcheng = (new DlgWznmVerGenui()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERGLOBALDATA) dpcheng = (new DlgWznmVerGlobal()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERIMPEXPDATA) dpcheng = (new DlgWznmVerImpexp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERNEWDATA) dpcheng = (new DlgWznmVerNew()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVEROPPACKDATA) dpcheng = (new DlgWznmVerOppack()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGDLGWZNMVERWRINIMDLDATA) dpcheng = (new DlgWznmVerWrinimdl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGROOTWZNMDATA) dpcheng = (new RootWznm()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGSESSWZNMDATA) dpcheng = (new SessWznm()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMACK) dpcheng = new DpchEngWznmAck();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMALERT) dpcheng = new DpchEngWznmAlert();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMAPP1NEVENTDATA) dpcheng = (new PnlWznmApp1NEvent()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMAPP1NRTJOBDATA) dpcheng = (new PnlWznmApp1NRtjob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMAPPAPP1NSEQUENCEDATA) dpcheng = (new PnlWznmAppApp1NSequence()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMAPPDATA) dpcheng = (new CrdWznmApp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMAPPDETAILDATA) dpcheng = (new PnlWznmAppDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMAPPHEADBARDATA) dpcheng = (new PnlWznmAppHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMAPPLISTDATA) dpcheng = (new PnlWznmAppList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMAPPRECDATA) dpcheng = (new PnlWznmAppRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMAPPREF1NFILEDATA) dpcheng = (new PnlWznmAppRef1NFile()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMBLK1NRTDPCHDATA) dpcheng = (new PnlWznmBlk1NRtdpch()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMBLKAITEMDATA) dpcheng = (new PnlWznmBlkAItem()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMBLKDATA) dpcheng = (new CrdWznmBlk()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMBLKDETAILDATA) dpcheng = (new PnlWznmBlkDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMBLKHEADBARDATA) dpcheng = (new PnlWznmBlkHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMBLKLISTDATA) dpcheng = (new PnlWznmBlkList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMBLKRECDATA) dpcheng = (new PnlWznmBlkRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMBLKREF1NRTBLOCKDATA) dpcheng = (new PnlWznmBlkRef1NRtblock()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCAL1NSENSITIVITYDATA) dpcheng = (new PnlWznmCal1NSensitivity()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCALDATA) dpcheng = (new CrdWznmCal()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCALDETAILDATA) dpcheng = (new PnlWznmCalDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCALHEADBARDATA) dpcheng = (new PnlWznmCalHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCALLISTDATA) dpcheng = (new PnlWznmCalList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCALMNSTUBDATA) dpcheng = (new PnlWznmCalMNStub()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCALRECDATA) dpcheng = (new PnlWznmCalRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCAPAPARDATA) dpcheng = (new PnlWznmCapAPar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCAPDATA) dpcheng = (new CrdWznmCap()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCAPDETAILDATA) dpcheng = (new PnlWznmCapDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCAPHEADBARDATA) dpcheng = (new PnlWznmCapHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCAPLISTDATA) dpcheng = (new PnlWznmCapList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCAPRECDATA) dpcheng = (new PnlWznmCapRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCAR1NDIALOGDATA) dpcheng = (new PnlWznmCar1NDialog()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCARCAR1NPANELDATA) dpcheng = (new PnlWznmCarCar1NPanel()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCARDATA) dpcheng = (new CrdWznmCar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCARDETAILDATA) dpcheng = (new PnlWznmCarDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCARHEADBARDATA) dpcheng = (new PnlWznmCarHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCARHK1NCONTROLDATA) dpcheng = (new PnlWznmCarHk1NControl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCARLISTDATA) dpcheng = (new PnlWznmCarList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCARRECDATA) dpcheng = (new PnlWznmCarRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCHKDATA) dpcheng = (new CrdWznmChk()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCHKDETAILDATA) dpcheng = (new PnlWznmChkDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCHKHEADBARDATA) dpcheng = (new PnlWznmChkHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCHKLISTDATA) dpcheng = (new PnlWznmChkList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCHKRECDATA) dpcheng = (new PnlWznmChkRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCHKREF1NCALLDATA) dpcheng = (new PnlWznmChkRef1NCall()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCMP1NRELEASEDATA) dpcheng = (new PnlWznmCmp1NRelease()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCMPDATA) dpcheng = (new CrdWznmCmp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCMPDETAILDATA) dpcheng = (new PnlWznmCmpDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCMPHEADBARDATA) dpcheng = (new PnlWznmCmpHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCMPLISTDATA) dpcheng = (new PnlWznmCmpList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCMPMNLIBRARYDATA) dpcheng = (new PnlWznmCmpMNLibrary()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCMPMNOPPACKDATA) dpcheng = (new PnlWznmCmpMNOppack()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCMPRECDATA) dpcheng = (new PnlWznmCmpRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCONAPARDATA) dpcheng = (new PnlWznmConAPar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCONDATA) dpcheng = (new CrdWznmCon()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCONDETAILDATA) dpcheng = (new PnlWznmConDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCONFEDREF1NRTBLOCKDATA) dpcheng = (new PnlWznmConFedRef1NRtblock()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCONFIRM) dpcheng = new DpchEngWznmConfirm();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCONHEADBARDATA) dpcheng = (new PnlWznmConHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCONLISTDATA) dpcheng = (new PnlWznmConList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCONRECDATA) dpcheng = (new PnlWznmConRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCONSUP1NCONTROLDATA) dpcheng = (new PnlWznmConSup1NControl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCTP1NTAGDATA) dpcheng = (new PnlWznmCtp1NTag()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCTPAPARDATA) dpcheng = (new PnlWznmCtpAPar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCTPDATA) dpcheng = (new CrdWznmCtp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCTPDETAILDATA) dpcheng = (new PnlWznmCtpDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCTPHEADBARDATA) dpcheng = (new PnlWznmCtpHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCTPKKEYDATA) dpcheng = (new PnlWznmCtpKKey()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCTPKPARKEYDATA) dpcheng = (new PnlWznmCtpKParKey()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCTPLISTDATA) dpcheng = (new PnlWznmCtpList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCTPRECDATA) dpcheng = (new PnlWznmCtpRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMCTPTPL1NCAPABILITYDATA) dpcheng = (new PnlWznmCtpTpl1NCapability()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMDLGDATA) dpcheng = (new CrdWznmDlg()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMDLGDETAILDATA) dpcheng = (new PnlWznmDlgDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMDLGHEADBARDATA) dpcheng = (new PnlWznmDlgHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMDLGHK1NCONTROLDATA) dpcheng = (new PnlWznmDlgHk1NControl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMDLGLISTDATA) dpcheng = (new PnlWznmDlgList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMDLGMNQUERYDATA) dpcheng = (new PnlWznmDlgMNQuery()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMDLGRECDATA) dpcheng = (new PnlWznmDlgRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMDLGREF1NCONTROLDATA) dpcheng = (new PnlWznmDlgRef1NControl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMERRDATA) dpcheng = (new CrdWznmErr()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMERRDETAILDATA) dpcheng = (new PnlWznmErrDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMERRHEADBARDATA) dpcheng = (new PnlWznmErrHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMERRLISTDATA) dpcheng = (new PnlWznmErrList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMERRRECDATA) dpcheng = (new PnlWznmErrRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMEVTDATA) dpcheng = (new CrdWznmEvt()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMEVTDETAILDATA) dpcheng = (new PnlWznmEvtDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMEVTHEADBARDATA) dpcheng = (new PnlWznmEvtHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMEVTLISTDATA) dpcheng = (new PnlWznmEvtList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMEVTRECDATA) dpcheng = (new PnlWznmEvtRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMFILDATA) dpcheng = (new CrdWznmFil()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMFILDETAILDATA) dpcheng = (new PnlWznmFilDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMFILHEADBARDATA) dpcheng = (new PnlWznmFilHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMFILLISTDATA) dpcheng = (new PnlWznmFilList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMFILRECDATA) dpcheng = (new PnlWznmFilRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIELDATA) dpcheng = (new CrdWznmIel()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIELDETAILDATA) dpcheng = (new PnlWznmIelDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIELHEADBARDATA) dpcheng = (new PnlWznmIelHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIELLISTDATA) dpcheng = (new PnlWznmIelList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIELRECDATA) dpcheng = (new PnlWznmIelRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIEX1NIMPEXPDATA) dpcheng = (new PnlWznmIex1NImpexp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIEXDATA) dpcheng = (new CrdWznmIex()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIEXDETAILDATA) dpcheng = (new PnlWznmIexDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIEXHEADBARDATA) dpcheng = (new PnlWznmIexHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIEXHK1NVECTORDATA) dpcheng = (new PnlWznmIexHk1NVector()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIEXLISTDATA) dpcheng = (new PnlWznmIexList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIEXRECDATA) dpcheng = (new PnlWznmIexRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIEXREF1NDIALOGDATA) dpcheng = (new PnlWznmIexRef1NDialog()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIMEDATA) dpcheng = (new CrdWznmIme()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIMEDETAILDATA) dpcheng = (new PnlWznmImeDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIMEHEADBARDATA) dpcheng = (new PnlWznmImeHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIMEHK1NVECTORDATA) dpcheng = (new PnlWznmImeHk1NVector()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIMEIME1NIMPEXPCOLDATA) dpcheng = (new PnlWznmImeIme1NImpexpcol()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIMELISTDATA) dpcheng = (new PnlWznmImeList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIMERECDATA) dpcheng = (new PnlWznmImeRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMIMESUP1NIMPEXPDATA) dpcheng = (new PnlWznmImeSup1NImpexp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOB1NMETHODDATA) dpcheng = (new PnlWznmJob1NMethod()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOB1NRTJOBDATA) dpcheng = (new PnlWznmJob1NRtjob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOB1NSENSITIVITYDATA) dpcheng = (new PnlWznmJob1NSensitivity()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBACMDDATA) dpcheng = (new PnlWznmJobACmd()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBAVARDATA) dpcheng = (new PnlWznmJobAVar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBDATA) dpcheng = (new CrdWznmJob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBDETAILDATA) dpcheng = (new PnlWznmJobDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBHEADBARDATA) dpcheng = (new PnlWznmJobHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBHK1NVECTORDATA) dpcheng = (new PnlWznmJobHk1NVector()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBJOB1NSTAGEDATA) dpcheng = (new PnlWznmJobJob1NStage()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBLISTDATA) dpcheng = (new PnlWznmJobList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBMNOPDATA) dpcheng = (new PnlWznmJobMNOp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBMNOPPACKDATA) dpcheng = (new PnlWznmJobMNOppack()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBRECDATA) dpcheng = (new PnlWznmJobRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBREF1NBLOCKDATA) dpcheng = (new PnlWznmJobRef1NBlock()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBSUBMNJOBDATA) dpcheng = (new PnlWznmJobSubMNJob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMJOBSUPMNJOBDATA) dpcheng = (new PnlWznmJobSupMNJob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLIBAMAKEFILEDATA) dpcheng = (new PnlWznmLibAMakefile()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLIBAPKGLISTDATA) dpcheng = (new PnlWznmLibAPkglist()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLIBDATA) dpcheng = (new CrdWznmLib()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLIBDETAILDATA) dpcheng = (new PnlWznmLibDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLIBHEADBARDATA) dpcheng = (new PnlWznmLibHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLIBLISTDATA) dpcheng = (new PnlWznmLibList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLIBMNCOMPONENTDATA) dpcheng = (new PnlWznmLibMNComponent()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLIBMNOPPACKDATA) dpcheng = (new PnlWznmLibMNOppack()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLIBRECDATA) dpcheng = (new PnlWznmLibRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLIBREF1NFILEDATA) dpcheng = (new PnlWznmLibRef1NFile()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLOCDATA) dpcheng = (new CrdWznmLoc()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLOCDETAILDATA) dpcheng = (new PnlWznmLocDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLOCHEADBARDATA) dpcheng = (new PnlWznmLocHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLOCLISTDATA) dpcheng = (new PnlWznmLocList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLOCMNVERSIONDATA) dpcheng = (new PnlWznmLocMNVersion()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMLOCRECDATA) dpcheng = (new PnlWznmLocRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMCH1NRELEASEDATA) dpcheng = (new PnlWznmMch1NRelease()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMCHAMAKEFILEDATA) dpcheng = (new PnlWznmMchAMakefile()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMCHAPARDATA) dpcheng = (new PnlWznmMchAPar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMCHDATA) dpcheng = (new CrdWznmMch()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMCHDETAILDATA) dpcheng = (new PnlWznmMchDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMCHHEADBARDATA) dpcheng = (new PnlWznmMchHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMCHLISTDATA) dpcheng = (new PnlWznmMchList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMCHRECDATA) dpcheng = (new PnlWznmMchRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMCHSUP1NMACHINEDATA) dpcheng = (new PnlWznmMchSup1NMachine()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMDLDATA) dpcheng = (new CrdWznmMdl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMDLDETAILDATA) dpcheng = (new PnlWznmMdlDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMDLHEADBARDATA) dpcheng = (new PnlWznmMdlHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMDLLISTDATA) dpcheng = (new PnlWznmMdlList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMDLMDL1NCARDDATA) dpcheng = (new PnlWznmMdlMdl1NCard()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMDLRECDATA) dpcheng = (new PnlWznmMdlRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMDLREF1NPANELDATA) dpcheng = (new PnlWznmMdlRef1NPanel()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMTDAINVPARDATA) dpcheng = (new PnlWznmMtdAInvpar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMTDARETPARDATA) dpcheng = (new PnlWznmMtdARetpar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMTDDATA) dpcheng = (new CrdWznmMtd()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMTDDETAILDATA) dpcheng = (new PnlWznmMtdDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMTDHEADBARDATA) dpcheng = (new PnlWznmMtdHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMTDLISTDATA) dpcheng = (new PnlWznmMtdList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMMTDRECDATA) dpcheng = (new PnlWznmMtdRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVADMINDATA) dpcheng = (new PnlWznmNavAdmin()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVAPPDEVDATA) dpcheng = (new PnlWznmNavAppdev()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVAUXFCTDATA) dpcheng = (new PnlWznmNavAuxfct()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVCOMPDATA) dpcheng = (new PnlWznmNavComp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVDATA) dpcheng = (new CrdWznmNav()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVDBSTRDATA) dpcheng = (new PnlWznmNavDbstr()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVDEPLOYDATA) dpcheng = (new PnlWznmNavDeploy()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVGLOBALDATA) dpcheng = (new PnlWznmNavGlobal()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVHEADBARDATA) dpcheng = (new PnlWznmNavHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVJOBDATA) dpcheng = (new PnlWznmNavJob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVPREDATA) dpcheng = (new PnlWznmNavPre()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVPROJECTDATA) dpcheng = (new PnlWznmNavProject()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMNAVUIXDATA) dpcheng = (new PnlWznmNavUix()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPK1NOPDATA) dpcheng = (new PnlWznmOpk1NOp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKAINVARGDATA) dpcheng = (new PnlWznmOpkAInvarg()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKARETVALDATA) dpcheng = (new PnlWznmOpkARetval()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKDATA) dpcheng = (new CrdWznmOpk()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKDETAILDATA) dpcheng = (new PnlWznmOpkDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKHEADBARDATA) dpcheng = (new PnlWznmOpkHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKLISTDATA) dpcheng = (new PnlWznmOpkList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKMNCOMPONENTDATA) dpcheng = (new PnlWznmOpkMNComponent()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKMNJOBDATA) dpcheng = (new PnlWznmOpkMNJob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKMNLIBRARYDATA) dpcheng = (new PnlWznmOpkMNLibrary()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKRECDATA) dpcheng = (new PnlWznmOpkRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKREF1NBLOCKDATA) dpcheng = (new PnlWznmOpkRef1NBlock()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPKSQKMNSTUBDATA) dpcheng = (new PnlWznmOpkSqkMNStub()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPXAINVARGDATA) dpcheng = (new PnlWznmOpxAInvarg()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPXARETVALDATA) dpcheng = (new PnlWznmOpxARetval()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPXDATA) dpcheng = (new CrdWznmOpx()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPXDETAILDATA) dpcheng = (new PnlWznmOpxDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPXHEADBARDATA) dpcheng = (new PnlWznmOpxHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPXLISTDATA) dpcheng = (new PnlWznmOpxList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPXMNJOBDATA) dpcheng = (new PnlWznmOpxMNJob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPXRECDATA) dpcheng = (new PnlWznmOpxRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPXREF1NBLOCKDATA) dpcheng = (new PnlWznmOpxRef1NBlock()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMOPXSQKMNSTUBDATA) dpcheng = (new PnlWznmOpxSqkMNStub()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPNLDATA) dpcheng = (new CrdWznmPnl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPNLDETAILDATA) dpcheng = (new PnlWznmPnlDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPNLHEADBARDATA) dpcheng = (new PnlWznmPnlHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPNLHK1NCONTROLDATA) dpcheng = (new PnlWznmPnlHk1NControl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPNLLISTDATA) dpcheng = (new PnlWznmPnlList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPNLMNQUERYDATA) dpcheng = (new PnlWznmPnlMNQuery()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPNLRECDATA) dpcheng = (new PnlWznmPnlRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRJDATA) dpcheng = (new CrdWznmPrj()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRJDETAILDATA) dpcheng = (new PnlWznmPrjDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRJHEADBARDATA) dpcheng = (new PnlWznmPrjHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRJLISTDATA) dpcheng = (new PnlWznmPrjList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRJMNPERSONDATA) dpcheng = (new PnlWznmPrjMNPerson()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRJPRJ1NVERSIONDATA) dpcheng = (new PnlWznmPrjPrj1NVersion()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRJRECDATA) dpcheng = (new PnlWznmPrjRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRSADETAILDATA) dpcheng = (new PnlWznmPrsADetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRSDATA) dpcheng = (new CrdWznmPrs()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRSDETAILDATA) dpcheng = (new PnlWznmPrsDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRSHEADBARDATA) dpcheng = (new PnlWznmPrsHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRSLISTDATA) dpcheng = (new PnlWznmPrsList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRSMNPROJECTDATA) dpcheng = (new PnlWznmPrsMNProject()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPRSRECDATA) dpcheng = (new PnlWznmPrsRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPST1NQUERYMODDATA) dpcheng = (new PnlWznmPst1NQuerymod()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPSTDATA) dpcheng = (new CrdWznmPst()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPSTDETAILDATA) dpcheng = (new PnlWznmPstDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPSTHEADBARDATA) dpcheng = (new PnlWznmPstHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPSTLISTDATA) dpcheng = (new PnlWznmPstList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMPSTRECDATA) dpcheng = (new PnlWznmPstRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQCODATA) dpcheng = (new CrdWznmQco()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQCODETAILDATA) dpcheng = (new PnlWznmQcoDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQCOHEADBARDATA) dpcheng = (new PnlWznmQcoHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQCOLISTDATA) dpcheng = (new PnlWznmQcoList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQCORECDATA) dpcheng = (new PnlWznmQcoRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQCOREF1NCONTROLDATA) dpcheng = (new PnlWznmQcoRef1NControl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQMDDATA) dpcheng = (new CrdWznmQmd()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQMDDETAILDATA) dpcheng = (new PnlWznmQmdDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQMDHEADBARDATA) dpcheng = (new PnlWznmQmdHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQMDLISTDATA) dpcheng = (new PnlWznmQmdList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQMDRECDATA) dpcheng = (new PnlWznmQmdRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRY1NQUERYMODDATA) dpcheng = (new PnlWznmQry1NQuerymod()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYACLAUSEDATA) dpcheng = (new PnlWznmQryAClause()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYAORDERDATA) dpcheng = (new PnlWznmQryAOrder()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYDATA) dpcheng = (new CrdWznmQry()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYDETAILDATA) dpcheng = (new PnlWznmQryDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYHEADBARDATA) dpcheng = (new PnlWznmQryHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYLISTDATA) dpcheng = (new PnlWznmQryList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYMNDIALOGDATA) dpcheng = (new PnlWznmQryMNDialog()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYMNPANELDATA) dpcheng = (new PnlWznmQryMNPanel()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYMNTABLEDATA) dpcheng = (new PnlWznmQryMNTable()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYQRY1NQUERYCOLDATA) dpcheng = (new PnlWznmQryQry1NQuerycol()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYRECDATA) dpcheng = (new PnlWznmQryRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMQRYSUP1NQUERYDATA) dpcheng = (new PnlWznmQrySup1NQuery()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMREL1NTABLECOLDATA) dpcheng = (new PnlWznmRel1NTablecol()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRELATITLEDATA) dpcheng = (new PnlWznmRelATitle()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRELDATA) dpcheng = (new CrdWznmRel()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRELDETAILDATA) dpcheng = (new PnlWznmRelDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRELHEADBARDATA) dpcheng = (new PnlWznmRelHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRELLISTDATA) dpcheng = (new PnlWznmRelList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRELRECDATA) dpcheng = (new PnlWznmRelRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRELREF1NCONTROLDATA) dpcheng = (new PnlWznmRelRef1NControl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRELREF1NDIALOGDATA) dpcheng = (new PnlWznmRelRef1NDialog()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRELREF1NPANELDATA) dpcheng = (new PnlWznmRelRef1NPanel()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRELSUP1NRELATIONDATA) dpcheng = (new PnlWznmRelSup1NRelation()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRLSDATA) dpcheng = (new CrdWznmRls()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRLSDETAILDATA) dpcheng = (new PnlWznmRlsDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRLSHEADBARDATA) dpcheng = (new PnlWznmRlsHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRLSLISTDATA) dpcheng = (new PnlWznmRlsList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRLSRECDATA) dpcheng = (new PnlWznmRlsRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRTJ1NRTBLOCKDATA) dpcheng = (new PnlWznmRtj1NRtblock()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRTJ1NRTDPCHDATA) dpcheng = (new PnlWznmRtj1NRtdpch()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRTJDATA) dpcheng = (new CrdWznmRtj()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRTJDETAILDATA) dpcheng = (new PnlWznmRtjDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRTJHEADBARDATA) dpcheng = (new PnlWznmRtjHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRTJLISTDATA) dpcheng = (new PnlWznmRtjList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRTJRECDATA) dpcheng = (new PnlWznmRtjRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMRTJSUP1NRTJOBDATA) dpcheng = (new PnlWznmRtjSup1NRtjob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBS1NSTUBDATA) dpcheng = (new PnlWznmSbs1NStub()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBS1NTABLECOLDATA) dpcheng = (new PnlWznmSbs1NTablecol()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSASBMNSUBSETDATA) dpcheng = (new PnlWznmSbsAsbMNSubset()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSATITLEDATA) dpcheng = (new PnlWznmSbsATitle()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSBSBMNSUBSETDATA) dpcheng = (new PnlWznmSbsBsbMNSubset()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSDATA) dpcheng = (new CrdWznmSbs()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSDETAILDATA) dpcheng = (new PnlWznmSbsDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSFRS1NRELATIONDATA) dpcheng = (new PnlWznmSbsFrs1NRelation()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSHEADBARDATA) dpcheng = (new PnlWznmSbsHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSLISTDATA) dpcheng = (new PnlWznmSbsList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSPST1NQUERYMODDATA) dpcheng = (new PnlWznmSbsPst1NQuerymod()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSRECDATA) dpcheng = (new PnlWznmSbsRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSBSTOS1NRELATIONDATA) dpcheng = (new PnlWznmSbsTos1NRelation()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSEQDATA) dpcheng = (new CrdWznmSeq()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSEQDETAILDATA) dpcheng = (new PnlWznmSeqDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSEQHEADBARDATA) dpcheng = (new PnlWznmSeqHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSEQLISTDATA) dpcheng = (new PnlWznmSeqList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSEQRECDATA) dpcheng = (new PnlWznmSeqRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSEQSEQ1NSTATEDATA) dpcheng = (new PnlWznmSeqSeq1NState()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSGE1NSENSITIVITYDATA) dpcheng = (new PnlWznmSge1NSensitivity()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSGEDATA) dpcheng = (new CrdWznmSge()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSGEDETAILDATA) dpcheng = (new PnlWznmSgeDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSGEHEADBARDATA) dpcheng = (new PnlWznmSgeHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSGELISTDATA) dpcheng = (new PnlWznmSgeList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSGERECDATA) dpcheng = (new PnlWznmSgeRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSGESQKMNSTUBDATA) dpcheng = (new PnlWznmSgeSqkMNStub()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTBDATA) dpcheng = (new CrdWznmStb()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTBDETAILDATA) dpcheng = (new PnlWznmStbDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTBHEADBARDATA) dpcheng = (new PnlWznmStbHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTBLISTDATA) dpcheng = (new PnlWznmStbList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTBMNCALLDATA) dpcheng = (new PnlWznmStbMNCall()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTBMNSQUAWKDATA) dpcheng = (new PnlWznmStbMNSquawk()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTBRECDATA) dpcheng = (new PnlWznmStbRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTBSUBMNSTUBDATA) dpcheng = (new PnlWznmStbSubMNStub()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTBSUPMNSTUBDATA) dpcheng = (new PnlWznmStbSupMNStub()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTEAACTIONDATA) dpcheng = (new PnlWznmSteAAction()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTEATRIGDATA) dpcheng = (new PnlWznmSteATrig()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTEDATA) dpcheng = (new CrdWznmSte()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTEDETAILDATA) dpcheng = (new PnlWznmSteDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTEHEADBARDATA) dpcheng = (new PnlWznmSteHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTELISTDATA) dpcheng = (new PnlWznmSteList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSTERECDATA) dpcheng = (new PnlWznmSteRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMSUSPEND) dpcheng = new DpchEngWznmSuspend();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTAGDATA) dpcheng = (new CrdWznmTag()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTAGDETAILDATA) dpcheng = (new PnlWznmTagDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTAGHEADBARDATA) dpcheng = (new PnlWznmTagHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTAGLISTDATA) dpcheng = (new PnlWznmTagList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTAGRECDATA) dpcheng = (new PnlWznmTagRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBL1NCHECKDATA) dpcheng = (new PnlWznmTbl1NCheck()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBL1NIMPEXPDATA) dpcheng = (new PnlWznmTbl1NImpexp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBL1NSTUBDATA) dpcheng = (new PnlWznmTbl1NStub()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBL1NSUBSETDATA) dpcheng = (new PnlWznmTbl1NSubset()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLALOADFCTDATA) dpcheng = (new PnlWznmTblALoadfct()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLATITLEDATA) dpcheng = (new PnlWznmTblATitle()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLDATA) dpcheng = (new CrdWznmTbl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLDETAILDATA) dpcheng = (new PnlWznmTblDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLFCT1NTABLECOLDATA) dpcheng = (new PnlWznmTblFct1NTablecol()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLFR1NRELATIONDATA) dpcheng = (new PnlWznmTblFr1NRelation()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLHEADBARDATA) dpcheng = (new PnlWznmTblHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLHK1NVECTORDATA) dpcheng = (new PnlWznmTblHk1NVector()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLLISTDATA) dpcheng = (new PnlWznmTblList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLMNQUERYDATA) dpcheng = (new PnlWznmTblMNQuery()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLMNVECTORDATA) dpcheng = (new PnlWznmTblMNVector()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLPST1NQUERYMODDATA) dpcheng = (new PnlWznmTblPst1NQuerymod()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLRECDATA) dpcheng = (new PnlWznmTblRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLREF1NCALLDATA) dpcheng = (new PnlWznmTblRef1NCall()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLREF1NDIALOGDATA) dpcheng = (new PnlWznmTblRef1NDialog()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLREF1NPANELDATA) dpcheng = (new PnlWznmTblRef1NPanel()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLREF1NQUERYMODDATA) dpcheng = (new PnlWznmTblRef1NQuerymod()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLREF1NRTBLOCKDATA) dpcheng = (new PnlWznmTblRef1NRtblock()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLSRC1NFEEDDATA) dpcheng = (new PnlWznmTblSrc1NFeed()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLTBL1NTABLECOLDATA) dpcheng = (new PnlWznmTblTbl1NTablecol()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTBLTO1NRELATIONDATA) dpcheng = (new PnlWznmTblTo1NRelation()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCO1NCHECKDATA) dpcheng = (new PnlWznmTco1NCheck()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCO1NIMPEXPCOLDATA) dpcheng = (new PnlWznmTco1NImpexpcol()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCO1NQUERYCOLDATA) dpcheng = (new PnlWznmTco1NQuerycol()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCOATITLEDATA) dpcheng = (new PnlWznmTcoATitle()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCODATA) dpcheng = (new CrdWznmTco()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCODETAILDATA) dpcheng = (new PnlWznmTcoDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCOHEADBARDATA) dpcheng = (new PnlWznmTcoHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCOLISTDATA) dpcheng = (new PnlWznmTcoList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCORECDATA) dpcheng = (new PnlWznmTcoRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCOREF1NCONTROLDATA) dpcheng = (new PnlWznmTcoRef1NControl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMTCOREF1NQUERYMODDATA) dpcheng = (new PnlWznmTcoRef1NQuerymod()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSGAACCESSDATA) dpcheng = (new PnlWznmUsgAAccess()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSGDATA) dpcheng = (new CrdWznmUsg()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSGDETAILDATA) dpcheng = (new PnlWznmUsgDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSGHEADBARDATA) dpcheng = (new PnlWznmUsgHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSGLISTDATA) dpcheng = (new PnlWznmUsgList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSGMNUSERDATA) dpcheng = (new PnlWznmUsgMNUser()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSGRECDATA) dpcheng = (new PnlWznmUsgRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSR1NSESSIONDATA) dpcheng = (new PnlWznmUsr1NSession()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSRAACCESSDATA) dpcheng = (new PnlWznmUsrAAccess()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSRDATA) dpcheng = (new CrdWznmUsr()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSRDETAILDATA) dpcheng = (new PnlWznmUsrDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSRHEADBARDATA) dpcheng = (new PnlWznmUsrHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSRLISTDATA) dpcheng = (new PnlWznmUsrList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSRMNUSERGROUPDATA) dpcheng = (new PnlWznmUsrMNUsergroup()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUSRRECDATA) dpcheng = (new PnlWznmUsrRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUTLDATA) dpcheng = (new CrdWznmUtl()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMUTLHEADBARDATA) dpcheng = (new PnlWznmUtlHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECATITLEDATA) dpcheng = (new PnlWznmVecATitle()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECDATA) dpcheng = (new CrdWznmVec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECDETAILDATA) dpcheng = (new PnlWznmVecDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECFCT1NTABLECOLDATA) dpcheng = (new PnlWznmVecFct1NTablecol()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECHEADBARDATA) dpcheng = (new PnlWznmVecHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECLISTDATA) dpcheng = (new PnlWznmVecList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECMNTABLEDATA) dpcheng = (new PnlWznmVecMNTable()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECPST1NQUERYMODDATA) dpcheng = (new PnlWznmVecPst1NQuerymod()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECRECDATA) dpcheng = (new PnlWznmVecRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECREF1NPANELDATA) dpcheng = (new PnlWznmVecRef1NPanel()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECSRC1NFEEDDATA) dpcheng = (new PnlWznmVecSrc1NFeed()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVECVEC1NVECTORITEMDATA) dpcheng = (new PnlWznmVecVec1NVectoritem()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NBLOCKDATA) dpcheng = (new PnlWznmVer1NBlock()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NCALLDATA) dpcheng = (new PnlWznmVer1NCall()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NCAPABILITYDATA) dpcheng = (new PnlWznmVer1NCapability()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NCOMPONENTDATA) dpcheng = (new PnlWznmVer1NComponent()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NIMPEXPCPLXDATA) dpcheng = (new PnlWznmVer1NImpexpcplx()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NJOBDATA) dpcheng = (new PnlWznmVer1NJob()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NOPPACKDATA) dpcheng = (new PnlWznmVer1NOppack()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NPRESETDATA) dpcheng = (new PnlWznmVer1NPreset()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NQUERYDATA) dpcheng = (new PnlWznmVer1NQuery()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NRELATIONDATA) dpcheng = (new PnlWznmVer1NRelation()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NTABLEDATA) dpcheng = (new PnlWznmVer1NTable()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVER1NVECTORDATA) dpcheng = (new PnlWznmVer1NVector()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERBVR1NVERSIONDATA) dpcheng = (new PnlWznmVerBvr1NVersion()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERDATA) dpcheng = (new CrdWznmVer()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERDETAILDATA) dpcheng = (new PnlWznmVerDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERHEADBARDATA) dpcheng = (new PnlWznmVerHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERLISTDATA) dpcheng = (new PnlWznmVerList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERMNLOCALEDATA) dpcheng = (new PnlWznmVerMNLocale()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERRECDATA) dpcheng = (new PnlWznmVerRec()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERREF1NFILEDATA) dpcheng = (new PnlWznmVerRef1NFile()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERVER1NAPPDATA) dpcheng = (new PnlWznmVerVer1NApp()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERVER1NERRORDATA) dpcheng = (new PnlWznmVerVer1NError()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVERVER1NMODULEDATA) dpcheng = (new PnlWznmVerVer1NModule()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVITDATA) dpcheng = (new CrdWznmVit()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVITDETAILDATA) dpcheng = (new PnlWznmVitDetail()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVITHEADBARDATA) dpcheng = (new PnlWznmVitHeadbar()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVITLISTDATA) dpcheng = (new PnlWznmVitList()).new DpchEngData();
			else if (ixWznmVDpch == VecWznmVDpch.DPCHENGWZNMVITRECDATA) dpcheng = (new PnlWznmVitRec()).new DpchEngData();

			if (dpcheng != null) dpcheng.readXML(doc,  "",  true);

		} catch (IOException e) {
			System.out.println(e.toString());
		} catch (ParserConfigurationException e) {
			System.out.println(e.toString());
		} catch (SAXException e) {
			System.out.println(e.toString());
		};

		return dpcheng;
	};

	public static String writeDpchApp(
				DpchAppWznm dpchapp
			) {
		Document doc;
		StringWriter str = new StringWriter();

		try {
			doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().newDocument();
	
			dpchapp.writeXML(doc, null);
	
			Transformer tr = TransformerFactory.newInstance().newTransformer();
	
			tr.transform(new DOMSource(doc), new StreamResult(str));
	
			return(str.toString());

		} catch (ParserConfigurationException e) {
			System.out.println(e.toString());
		} catch (TransformerConfigurationException e) {
			System.out.println(e.toString());
		} catch (TransformerException e) {
			System.out.println(e.toString());
		};
		
		return "";
	};
};
