# file Makefile.inc
# make file paths for Wznm operation daemon, release wznmopd1_jack
# author Alexander Wirthmueller
# date created: 25 Aug 2020
# modified: 25 Aug 2020

SRCROOT = /home/mpsitech/src
LIBROOT = /home/mpsitech/lib
BINROOT = /home/mpsitech/bin

