# file Makefile.inc
# make file paths for Wznm operation daemon, release wznmopd2_awsubt
# author Alexander Wirthmueller
# date created: 27 Aug 2020
# modified: 27 Aug 2020

SRCROOT = /home/ubuntu/src
LIBROOT = /home/ubuntu/lib
BINROOT = /home/ubuntu/bin

