# file Makefile.inc
# make file paths for Wznm combined daemon, release wznmcmbd_genio
# author Alexander Wirthmueller
# date created: 11 Jul 2020
# modified: 11 Jul 2020

SRCROOT = /home/mpsitech/src
LIBROOT = /home/mpsitech/lib
BINROOT = /home/mpsitech/bin

